### ISSUE TITLE
Add an explicit alias for zap()

### ISSUE THREAD

**Issue by DanChaltiel** [tidyverse/purrr#1000]
As with the (awesome) purrr v1.0.0 upcoming, one bit of the `News.md` hit me a bit: 

> `pluck<-/assign_in()` now sets elements to `NULL` rather than removing them (636). Now use the explicit `zap()` if you want to remove elements.

While the term "explicit" obviously refers to code style, I think it doesn't fit `zap()` very well. IMHO, I find the `zap()` name to be rather unclear and, more importantly, very hard to remember when I need it. 

For example, I would expect a name like `list_discard_null()`,  `list_remove_null()`, or maybe  `list_keep_nonnull()`.

Wouldn't something like this be acceptable as an alias?

**Comment by hadley** [comment]
To me, none of those suggestion would read correctly in code like `pluck(x, "a", "b", "c") <- zap()`. 

We don't have any plans to consider the name at this time; it's hard to find a word that clearly conveys removal/deletion that doesn't have existing meaning or implementation within R.
