### ISSUE TITLE
Soft deprecation warnings of `vctrs_vec_compat()` don't bubble up

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/purrr#1004]
i.e. should see a warning here

``` r
purrr::map(pairlist(1, 2), identity)
#> [[1]]
#> [1] 1
#> 
#> [[2]]
#> [1] 2
```

I think we need to pass the `user_env` down to `vctrs_vec_compat()`, which may be annoying

grep for any usage of `deprecate_soft()` to make sure we get them all

**Comment by hadley** [comment]
Two other functions need similar tweaks: `deprec_rerun()` and `where_at()`.
