### ISSUE TITLE
map result orderly?

### ISSUE THREAD

**Issue by asmlgkj** [tidyverse/purrr#1006]
Thanks a lot for your help.

I want to know  map function  result orderly or not in 

purrr::map (all the related map function )
furrr::map (all the related map function )

**Comment by hadley** [comment]
I don't understand the question, sorry.

**Comment by asmlgkj** [comment]
sorry for that.
because can map a argument like list, also for purrr::map and furrr::map, so if a function return a number,
will the number is the same order of the element in the list.  like a corresponding pair

**Comment by hadley** [comment]
Yes
