### ISSUE TITLE
`list_cbind()` does not handle names as well as did `map_dfc()`

### ISSUE THREAD

**Issue by DanChaltiel** [tidyverse/purrr#1007]
Hi,

> `*_dfc()` and `*_dfr()` have been superseded in favour of using the appropriate map function along with `list_rbind()` or `list_cbind()` (912).

I am trying to understand how I should write this code now that `map_dfc()` is superseded.

``` r
library(tidyverse)
list(x=1, y=2) %>% 
  map_dfc(~.x)
#> # A tibble: 1 x 2
#>       x     y
#>   <dbl> <dbl>
#> 1     1     2

list(x=1, y=2) %>% 
  map(~as_tibble(.x)) %>% 
  list_cbind()
#> # A tibble: 1 x 2
#>   x$value y$value
#>     <dbl>   <dbl>
#> 1       1       2
```

<sup>Created on 2022-11-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Shouldn't all columns be `tidyr::unpack()`ed in the end (with proper naming)?

Also, as user feedback, I have to admit that having to convert to a dataframe is a bit tedious and seems rather unnecessary. I will probably miss `*_dfc()` and `*_dfr()` when they will be deprecated.

**Comment by hadley** [comment]
If you already have a list, you can use `as.data.frame()`/`as_tibble()`.  `list_cbind()` is definitely more restrictive because it leads to fewer edge cases, which we believe is a net positive.

**Comment by francisbarton** [comment]
I'm really in favour of the changes and rationalisations brought in in purrr v1.0.

But I just wanted to add a note to highlight another way in which `list_rbind()`'s restrictiveness results in less useful outcomes compared to `map_df()` or `dplyr::bind_rows()` -- when you are trying to rectangle the kinds of nested list data one often gets back from APIs.

I know this issue has been closed, and I don't want to open a new issue for this, but just to illustrate.

Here's a reprex:

``` r
my_list <- list(
  resp_1 = list(fruit = "apple",
                source = "Somerset",
                details = list(colour = "red", drink = "scrumpy"),
                sweetness = 4),
  resp_2 = list(fruit = "lemon",
                source = "Seville",
                details = list(colour = "yellow", drink = "lemonade"),
                sweetness = NULL)
)


my_list |>
  purrr::map_df(purrr::list_flatten)
#> # A tibble: 2 × 5
#>   fruit source   details_colour details_drink sweetness
#>   <chr> <chr>    <chr>          <chr>             <dbl>
#> 1 apple Somerset red            scrumpy               4
#> 2 lemon Seville  yellow         lemonade             NA

# equivalent to the above, but clearly demonstrates difference between bind_rows() and list_rbind()
my_list |>
  purrr::map(purrr::list_flatten) |>
  dplyr::bind_rows()
#> # A tibble: 2 × 5
#>   fruit source   details_colour details_drink sweetness
#>   <chr> <chr>    <chr>          <chr>             <dbl>
#> 1 apple Somerset red            scrumpy               4
#> 2 lemon Seville  yellow         lemonade             NA

my_list |>
  purrr::map(purrr::list_flatten) |>
  purrr::list_rbind()
#> Error in `purrr::list_rbind()`:
#> ! Each element of `x` must be either a data frame or `NULL`.
#> ℹ Elements 1 and 2 are not.

# try converting each response to a tibble first:
my_list |>
  purrr::map(purrr::list_flatten) |>
  purrr::map(tibble::as_tibble) |>
  purrr::list_rbind()
#> Error in `purrr::map()` at purrr-1.0.0/R/list-combine.R:72:2:
#> ℹ In index: 2.
#> Caused by error:
#> ! All columns in a tibble must be vectors.
#> ✖ Column `sweetness` is NULL.

```

<sup>Created on 2023-01-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

`map_df()` works pretty much perfectly here. By comparison the last two approaches don't handle the `NULL` value in the way one would hope they would. `NULL`s are quite common in API responses; it's useful to be able to rectangle list data without this throwing an error.

I know `map_df()` isn't going away, but like the OP, I am not quite sure what approach I would take with code from the new paradigm that would replicate the functionality of `map_df()` in this kind of case.

**Comment by hadley** [comment]
@francisbarton FWIW it's generally better to open a new issue than comment on a closed issue; it's quite possible that no one will ever see a comment on a closed issue.

Here I think you got luckily that the quirks of `map_df()`/`bind_rows()` just happened to work with your dataset; if the structure had been a little different it probably wouldn't have worked. These days, I'd recommend handling these problems with the functions designed specifically for rectangling in tidyr:

``` r
library(tidyr)

my_list <- list(
  resp_1 = list(
    fruit = "apple",
    source = "Somerset",
    details = list(colour = "red", drink = "scrumpy"),
    sweetness = 4
  ),
  resp_2 = list(
    fruit = "lemon",
    source = "Seville",
    details = list(colour = "yellow", drink = "lemonade"),
    sweetness = NULL
  )
)
tibble(list = my_list) |> 
  unnest_wider(list) |> 
  unnest_wider(details, names_sep = "_")
#> # A tibble: 2 × 5
#>   fruit source   details_colour details_drink sweetness
#>   <chr> <chr>    <chr>          <chr>             <dbl>
#> 1 apple Somerset red            scrumpy               4
#> 2 lemon Seville  yellow         lemonade             NA
```

<sup>Created on 2023-01-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I think that code makes the transformation much more clear.
