### ISSUE TITLE
Map, walk and friends doesn't preserve names from named vectors.

### ISSUE THREAD

**Issue by KasperThystrup** [tidyverse/purrr#1029]
First off. Thanks for a very tight collection of 'applying' tools, for me its very usefull that I can skip a lot of redundant step from the `apply` family!

When entering a function through map or the like, names are not preserved from input vectors. This may seem a bit inconsistent in my eyes, as I would expect the input object to maintain its structure and properties.

```r
a <- function(x){print(names(x))}
b <- c("A" = 1, "b" = "c")
purrr::walk(.x = a, .f = b)
```
>NULL
>NULL

**Comment by hadley** [comment]
All of the purrr tools use `[[` to access the individual elements. If you want to work simultaneously with values and names, you'll need to use `iwalk()` and friends.
