### ISSUE TITLE
When() should not be depreciated until R 4.3 or later

### ISSUE THREAD

**Issue by mlane3** [tidyverse/purrr#1031]
Continuing the discussion from: [https://github.com/tidyverse/purrr/issues/1001](https://github.com/tidyverse/purrr/issues/1001)
from mlane
> Why are rbernoulii and when being depreciated and not moved to separate package? In particular "when()" does not have a replacement prior to 4.2.2 because there are bugs in gsub that were only recently patched in the last few months. Why don't simple make a wrapper to the proper function until the next major release of base R? We have strong concerns about the development of R packages and whether users have a voice or if everything has become developer focused. It does not feel like the depreciation is gradual at all. When myself and my teammates read the new changes, we truly felt that the developer of the packages either doesn't understand or they simple don't care how non-developers use there open source package.

from hadley
> I don't understand the connection between when() and gsub()

Gsub did not properly find an replace for 1Gb+ worth of data. 
 https://bugs.r-project.org/show_bug.cgi?id=18346

In May 2022 a bug was found with gsub/grepl that while it may seem low level basically prevents the data clean up of certain large human resources databases and IOT databases where certain special fields can exceed about 4000 characters.   This is a problem for data clean up of things like--primary spatial database key (PBkey) in [MapInfoPro](https://www.pitneybowes.com/us) map files, the asset_description in [EJWard](https://www.ejward.com/fuel-management-software/), the customer issue description/resolution in [Salesforce](https://www.salesforce.com) can all do this.  Each have unique reasons for how those fields are they way they are such as the fact in the world there are over 42 billion doors and 100 million buildings, so the PBkey needs to handle key size of of true addresses or doors x buildings (42*10^18 combinations).

At my organization we figured out a work around using when and stringr fixed the issue neither if_else nor case_when fixed it.  The code was very messy.  However, I noticed that when "when" was depreciated, it did not go through the typical error checks.  These is why I am concerned about even a soft depreciation of when.

Both these two threads have brought up the causes listed here: https://github.com/tidyverse/purrr/issues/1004 and https://github.com/tidyverse/purrr/issues/1027

I am glad you found the cause for my concern especially with chain errors needing to bubble up.   However, I am still uncertain what version of 4.2 will come with the patch that fixes [https://bugs.r-project.org/show_bug.cgi?id=18346](https://bugs.r-project.org/show_bug.cgi?id=18346).  So until issue 1004 and 1027 are resolved, I would like to ask that when be un-depreciated.

**Comment by hadley** [comment]
What is the connection between `when()` and `gsub()`?

**Comment by hadley** [comment]
I still don't understand the connection between `when()` and your problem. `gsub()` is not a purrr/tidyverse function and `when()` will continue to work for some time.
