### ISSUE TITLE
multiarch build on Windows 10, R-4.1.3?

### ISSUE THREAD

**Issue by gwd666** [tidyverse/purrr#1039]
Brief description of the problem

I am currently having issues installing purrr version 1.0.0, which afaik needs to be build from source, on a Windows 10 machine for R-4.1.3 version.
It will only build the package (from source) for the "main" architecture ie the active R session ie if I am running R 64 bit it will build 64-bit DLL and vice versa. Which means that other packages that have a (even 2nd degree etc) purrr dependency will now "also" fail multiarch builds, erroring on purrr's missing other architecture DLL.
I can work around this for now eg by devtools::install_local(INSTALL_opts = c("--no-multiarch")) but my guess is that this is more of a bug than a feature of the WIndows OS purrr installation process, or?

```r
install.packages("purrr", type = "source")

* installing *source* package 'purrr' ...
** package 'purrr' successfully unpacked and MD5 sums checked
** using staged installation
** libs
Warning: this package has a non-empty 'configure.win' file,
so building only the main architecture
....
```
Each architecture's build succeeds "on its own" but, 
if I want/need both architectures "side-by-side", what would be the appropriate method here? 
Thanks on advice

**Comment by hadley** [comment]
This should be fixed in the dev version and we'll have a new release on CRAN in the near future.

**Comment by gwd666** [comment]
> This should be fixed in the dev version and we'll have a new release on CRAN in the near future.

wow - the speed of that reply was unearthly
thanks
