### ISSUE TITLE
Error in the doc for `list_modify()`

### ISSUE THREAD

**Issue by DanChaltiel** [tidyverse/purrr#1053]
In the doc https://purrr.tidyverse.org/reference/list_modify.html, an example is wrong:

![image](https://user-images.githubusercontent.com/15105152/215874441-709cb3fa-2a43-4e19-9997-7ff730624a49.png)

Obviously, the correct output is:
``` r
library(tidyverse)
x <- list(x = 1:10, y = 4, z = list(a = 1, b = 2))
str(list_modify(x, z = zap()))
#> List of 2
#>  $ x: int [1:10] 1 2 3 4 5 6 7 8 9 10
#>  $ y: num 4
```

<sup>Created on 2023-01-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Tested with `purrr` version 1.0.1, sorry if it is corrected in the dev (I cannot install it now for an obscure local proxy reason).

**Comment by hadley** [comment]
That's because the current doc file is https://purrr.tidyverse.org/reference/list_assign.html, and that file exists due to a limitation in our pages deploy workflow that we haven't yet figured out how to overcome.
