### ISSUE TITLE
update failed

### ISSUE THREAD

**Issue by jingydz** [tidyverse/purrr#1054]
I want to update the R package `purrr` to  the newest version(>=1.0.1), but it failed.

```r
update.packages("purrr")
```
![image](https://user-images.githubusercontent.com/45711930/216906910-4c430a19-b98c-413c-b75e-46c3c35fe864.png)

**Comment by batpigandme** [comment]
What happens if you try to freshly install purrr (preferably in a clean R workspace)? (`install.packages("purrr")`)
