### ISSUE TITLE
FR: recursive option for `list_rbind()`

### ISSUE THREAD

**Issue by DanChaltiel** [tidyverse/purrr#1055]
Hi,

Could it be considered to make `list_rbind()` recursive?

I often encounter nested lists that need to be "dataframed", for instance:

``` r
library(tidyverse)
x = list(
  a = list(a1=sample_n(iris, 1), a2=sample_n(iris, 1)),
  b = list(b1=sample_n(iris, 1), b2=sample_n(iris, 1))
)

list_rbind(x)
#> Error in `list_rbind()`:
#> ! Each element of `x` must be either a data frame or `NULL`.
#> i Elements 1 and 2 are not.
```

In this simple case, this can be dealt with using `map()`, although it is less elegant:

``` r
x %>% map(list_rbind) %>% list_rbind()
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width    Species
#> 1          5.8         2.8          5.1         2.4  virginica
#> 2          6.9         3.1          5.4         2.1  virginica
#> 3          4.4         3.2          1.3         0.2     setosa
#> 4          5.1         2.5          3.0         1.1 versicolor
``` 

However, in more complicated cases, it can get more complex to get a single dataframe in the end:

``` r
x2 = list(
  a = sample_n(iris, 1),
  b = list(b1=sample_n(iris, 1), b2=sample_n(iris, 1))
)
x2 %>% map(list_rbind) %>% list_rbind()
#> Error in `map()`:
#> i In index: 1.
#> i With name: a.
#> Caused by error in `.f()`:
#> ! `x` must be a list, not a <data.frame> object.
```

Also, in more deep nested lists, mapping several times can get tedious and error-prone.

Is this something that would belong in purrr?

Maybe with a `recursive=TRUE` option?

**Comment by hadley** [comment]
Definitely out of scope, sorry. Our experience is that doing to do this sort of thing 100% automatically inevitably leads to weird edge cases.
