### ISSUE TITLE
Deprecation of when: can documentation show the equivalent code to previous `when()` use?

### ISSUE THREAD

**Issue by MatthieuStigler** [tidyverse/purrr#1059]
A convenient use of `when()` was as a conditional pipe, as was shown in the example, and as was advocated on Stack ([R Conditional evaluation when using the pipe operator %>%](https://stackoverflow.com/questions/30604107/r-conditional-evaluation-when-using-the-pipe-operator)).

Unfortunately, with the deprecation of `when()` in purrr 1.0.0, while the documentation mentions that one should use `if` instead, the replacement example does does not correspond to the previous example, where `when` was used as conditional pipe? Could the documentation seek to provide an equivalent code suggestion?

Thanks!

**Comment by steffen-stell** [comment]
Can you provide an example where this does not work? The example in the [answer advocating the use of `when()`](https://stackoverflow.com/a/44995741/11932936)  is:

```r
1:3 %>% 
  purrr::when(sum(.) < 25 ~ sum(.), ~0)
```

and can easily be replaced with

```r
1:3 %>%
  {if (sum(.) < 25) sum(.) else 0}
```

**Comment by MatthieuStigler** [comment]
thanks @steffen-stell 
My point was not about code "working" but the recommended alternative/best practice being documented. Unfortunately, the current documentation does not provide an equivalent code example for what I believe was a common use of `when`

**Comment by hadley** [comment]
I don't think there currently is a good alternative for that very specific use case. In my opinion, once you start adding branching to a pipe, you're starting to make a pipe that's going to be hard for other people to understand.
