### ISSUE TITLE
list_rbind() loses spatial class

### ISSUE THREAD

**Issue by francisbarton** [tidyverse/purrr#1076]
When binding a list of spatial data frames, the `sf` class is lost from the result.
(Perhaps this is where the `ptype` argument to `list_rbind()` is useful, but I don't know what I would need to use there.)

This feels like a loss of functionality, or at least an unexpected result, compared to using `dplyr::bind_rows()`, or a workflow using `map_dfr` that I might have used previously.

I'm sure you'll say this is behaving as desired, not a bug, but as a user of `purrr` this felt like an unexpected behaviour.

``` r
nc <- sf::st_read(system.file("shape/nc.shp", package="sf"), quiet = TRUE)

test_list <- list(ashe = dplyr::slice(nc, 1), surry = dplyr::slice(nc, 3))

purrr::list_rbind(test_list) |>
  class()
#> [1] "data.frame"

dplyr::bind_rows(test_list) |>
  class()
#> [1] "sf"         "data.frame"
```

<sup>Created on 2023-05-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by francisbarton** [comment]
Seems more odd, since a few years ago when `dplyr::bind_rows()` started handling binding `sf` data frames, which was a great. And this was due to `bind_rows()` starting to use `vctrs::vec_rbind()` - which I believe is also the basis for `list_rbind()`
https://github.com/tidyverse/dplyr/issues/2457#issuecomment-558962592

**Comment by hadley** [comment]
Tracking in related vctrs issue.

**Comment by francisbarton** [comment]
Maybe this one https://github.com/r-lib/vctrs/issues/1741
