### ISSUE TITLE
Support nested progressbars

### ISSUE THREAD

**Issue by DanChaltiel** [tidyverse/purrr#1077]
Hi,

It would be very nice if progress bars could be nested.

For instance, consider this code:

```r
library(purrr)
pb_out = list(format="Outer: {pb_current}/{pb_total} {pb_bar} {pb_percent}")
pb_in = list(format="\tInner: {pb_current}/{pb_total} {pb_bar} {pb_percent}")

walk(1:10, ~{
  walk(1:5, ~{
    Sys.sleep(1)
  }, .progress=pb_in)
}, .progress=pb_out)
```

As for purrr 1.0.1, each progress bar appears on the same line and overwrites the other one.

If the `inner` could be on the next row and leave the `outer` be, it would be a great feature!

**Comment by hadley** [comment]
Unfortunately this isn't possible due to limited support for consoles to change lines in this way.
