### ISSUE TITLE
GH tag `v1.0.1` points at pkg ver `1.0.0.9000`

### ISSUE THREAD

**Issue by pawelru** [tidyverse/purrr#1083]
Right now `v1.0.1` points at `6c02f4f43f8e4c5d2d4e40afbc73cd8fa555ae1c` and there we have:

https://github.com/tidyverse/purrr/blob/6c02f4f43f8e4c5d2d4e40afbc73cd8fa555ae1c/DESCRIPTION#L3

Installing package using GH tag `v1.0.1` gives non corresponding package version `1.0.0.9000`. 
This is an evidence of erroneous release process / CI - please double check it. Would it be possible to move the tag to the commit with appropriate package version?

**Comment by hadley** [comment]
I don't see any easy way to fix it, sorry.
