### ISSUE TITLE
`imap_vec()` is missing

### ISSUE THREAD

**Issue by arnaudgallou** [tidyverse/purrr#1084]
I'm looking for `imap_vec()` which [doesn't seem to exist](https://github.com/tidyverse/purrr/blob/main/R/imap.R) although the function is mentioned in the [deprecation warning of `imap_raw()`](https://github.com/tidyverse/purrr/blob/fd5a7320e37f7301c2dcc1668d032ee0d35acc9c/tests/testthat/_snaps/map-raw.md?plain=1#L20).

Is this a mistake?

**Comment by hadley** [comment]
Oops, yup.

**Comment by hadley** [comment]
Implementing this should be straightforward following the pattern of `imap_lgl()`, `imap_int()` etc.
