### ISSUE TITLE
`set_names` conflict with magrittr

### ISSUE THREAD

**Issue by clandinq** [tidyverse/purrr#1091]
I just updated to R 4.3.1 and updated all my packages to the latest version. I started receiving a warning from package conflicted warning about a function found in two packages: `set_names` is in magrittr and purrr. This is clearly a recent issue and will affect every user of tidyverse, since both packages are included there.

Here's a small example:

```r
# Load packages
library(tidyverse)
library(conflicted)
df <- tibble(a = 1, b = 2)
df %<>% set_names(c("c", "d"))
```

Result:
![Screen Shot 2023-07-13 at 11 10 06 AM](https://github.com/tidyverse/purrr/assets/44073393/8a9730a7-7240-4308-a5c0-e37f0eb92208)

**Comment by hadley** [comment]
We don't generally recommend attaching magrittr, but if you do, you can use the suggested conflicted call.
