### ISSUE TITLE
FR: New `keep_empty = FALSE` argument to `list_c()` and `list_rbind()`

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/purrr#1096]
I'm looking for the following behavior so that I can use `pivot_wider() %>% mutate(across(..., ~ list_c(.x, keep_empty = TRUE)))` as a more robust replacement for `tidyr::spread(convert = TRUE)` .

I can achieve it today with the lower-level `list_unchop()`, in a very clumsy way.

``` r
library(purrr)

# Existing behavior:
list_c(list("a", NULL, "b"))
#> [1] "a" "b"
vctrs::list_unchop(list("a", NULL, "b"))
#> [1] "a" "b"
vctrs::list_unchop(list("a", NULL, "b"), indices = as.list(1:3))
#> [1] "a" NA  "b"

# I'd like to write this:
list_c(list("a", NULL, "b"), keep_empty = TRUE)
#> [1] "a" NA  "b"
```

<sup>Created on 2023-08-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hadley** [comment]
Hmmmm, this doesn't feel quite right for purrr, but maybe it's the least worst place?

**Comment by hadley** [comment]
I think the way to implement this for both `list_c()` and `list_rbind()` is to replace any list elements that are identical to `NULL` with `NA`. Then the vctrs machinery can take over and ensure that the output gets a missing value of the correct type.

**Comment by krlmlr** [comment]
The original use case was a data set with a column with varying-type data.

``` r
library(tidyverse)

variant_data <- tibble(
  key = c(1, 1, 2, 2),
  name = letters[c(1:2, 1:2)],
  value = list("a", 1, NULL, NULL)
)

variant_data |>
  pivot_wider()
#> # A tibble: 2 × 3
#>     key a         b        
#>   <dbl> <list>    <list>   
#> 1     1 <chr [1]> <dbl [1]>
#> 2     2 <NULL>    <NULL>

# How to achieve this output:
tibble(
  key = c(1, 2),
  a = c("a", NA),
  b = c(1, NA),
)
#> # A tibble: 2 × 3
#>     key a         b
#>   <dbl> <chr> <dbl>
#> 1     1 a         1
#> 2     2 <NA>     NA
```

<sup>Created on 2024-07-16 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by DavisVaughan** [comment]
I've come back to look at @krlmlr's original example. It's just `unchop(keep_empty = TRUE)`

``` r
library(tidyverse)

variant_data <- tibble(
  key = c(1, 1, 2, 2),
  name = letters[c(1:2, 1:2)],
  value = list("a", 1, NULL, NULL)
)

variant_data |>
  pivot_wider() |>
  unchop(c(a, b), keep_empty = TRUE)
#> # A tibble: 2 × 3
#>     key a         b
#>   <dbl> <chr> <dbl>
#> 1     1 a         1
#> 2     2 <NA>     NA
```

So now I'm questioning if `list_c()` and friends really should get this argument or not.

The other thing that is nice about `unchop()` over forcing `list_c()` here is that `list_c(keep_empty = TRUE)` would only work on this:

```r
variant_data |>
  pivot_wider()
#> # A tibble: 2 × 3
#>     key a         b        
#>   <dbl> <list>    <list>   
#> 1     1 <chr [1]> <dbl [1]>
#> 2     2 <NULL>    <NULL>
```

If those list elements are size `1`. Otherwise it won't recycle to the right size. `unchop()` is a better tool for the job here because it gets the whole data frame and can handle any recycling that's required (like if it was `<chr [2]>` for example).

**Comment by DavisVaughan** [comment]
See https://github.com/tidyverse/purrr/pull/1144#issuecomment-2315597473
