### ISSUE TITLE
Documentation of `reduce` refers to `map`

### ISSUE THREAD

**Issue by phish108** [tidyverse/purrr#1103]
The documentation of the `...` attribute refers to the `map()` function. It would be a bit nicer if the reference for `reduce` would point to `reduce()` instead of `map()` ;)

**Comment by hadley** [comment]
Yeah, `reduce()` should document `...` itself, rather than inheriting the docs from map. 

While looking at this, I also noticed that the documentation for `.y` mentions `accumulate2()` which should also be removed.
