### ISSUE TITLE
Unexpected behavior of map() and pluck()

### ISSUE THREAD

**Issue by Dannyzhd** [tidyverse/purrr#1108]
Dear developers.

I was doing exercise of [Advanced R 9.2.7](https://advanced-r-solutions.rbind.io/functionals). Question2.

_[map(1:3, ~ runif(2))](https://purrr.tidyverse.org/reference/map.html) is a useful pattern for generating random numbers, but [map(1:3, runif(2))](https://purrr.tidyverse.org/reference/map.html) is not. Why not? Can you explain why it returns the result that it does?_

for the `map(1:3, runif(2))` my understanding is that since runif(2) is not a function-type variable, it is instead turned by `as_mapper()` as a indexing function driven by `purrr::pluck()` with the index series being provided by runif(2)

without lost of generality let's say runif(2) returns us
<img width="225" alt="Screen Shot 2023-11-10 at 3 26 47 PM" src="https://github.com/tidyverse/purrr/assets/68090582/5d86cb0b-cfa9-48ff-8965-fd41ae4739be">

Thus `map(1:3, runif(2))` is essentially equivalent to 

map(1:3,  function(x){pluck(x, 0.05562636, 0.70005192)})

which, in my understanding, should give an integer(0) as r basically truncate the index by using only the integer part, which in this case is 0.

However it seems, instead the function is automatically rounding the indices into 1 while performing the index. 
Resulting in for each iteration we index it by 1 twice, resulting in itself.

<img width="210" alt="Screen Shot 2023-11-10 at 3 46 27 PM" src="https://github.com/tidyverse/purrr/assets/68090582/5db7da1b-1fc9-429b-a9e2-b67dbd4f0666">
<img width="178" alt="Screen Shot 2023-11-10 at 3 46 59 PM" src="https://github.com/tidyverse/purrr/assets/68090582/86ee244c-1da3-4086-a615-7b93347198ee">

I guess maybe this is due to the as_mapper actually using `pluck_raw `instead of `pluck` as the `as_mapper(runif(2)) `indicates
<img width="607" alt="Screen Shot 2023-11-10 at 3 35 39 PM" src="https://github.com/tidyverse/purrr/assets/68090582/90674825-04c6-440e-aca8-e02c426a9b38">

But for this pluck_raw I could not find the document so it is hard to predict its behavior.

Could you guide my to the document for this behaviour of rounding performed by purrr::map when .f is treated as indexing function by as_mapper()? 

Thanks in advance for reviewing my qeustion.

**Comment by hadley** [comment]
I think this is just inherited from base R which truncates doubles when indexing:

``` r
c(1, 2, 3)[1.5]
#> [1] 1
```

<sup>Created on 2024-07-15 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
