### ISSUE TITLE
Progress bar not visible when script is run from the command line 

### ISSUE THREAD

**Issue by anjelinejeline** [tidyverse/purrr#1113]
Hi!
I have included the option .progress=TRUE within the map function and I can see the bar when I lrun the script from Rstudio but not when I launch it  in the command line (windows system). 
Can anyone help?
Thak you

**Comment by hadley** [comment]
Is it possible that your code takes less than 3 seconds to run? By default, non-iteractive shells display less frequent updates: https://cli.r-lib.org/articles/progress-advanced.html#non-interactive-r-sessions

**Comment by anjelinejeline** [comment]
Hi @hadley.
You are right the code took less than 3 seconds. 
Since December I have been using this option in other scripts and it works beautifully ( the progress bar is visible when running from the command line)
