### ISSUE TITLE
warning on superseded functions

### ISSUE THREAD

**Issue by latot** [tidyverse/purrr#1114]
Hi all, I was checking some things on R, and someone tell me, "did you notice map_dfr is superseded?" then checking the docs in fact, it is, is not only that function, I think is good the reasons why they are, is confusing yes, and the new functions are a lot more clear.

Now, is hard, to ppl how already knows how works a function, to go and read again the docs, just because there is no reason for it.

I think would be good, in cases like this, get a warning or message where we can know the function is obsolete to replace it (as doc says, still will get critical fixes).

No idea which functions are superseded, but this would helps a lot to update and detect this changes.

Thx!

**Comment by hadley** [comment]
There's no need to update superseded functions as they'll never go away. Functions that you definitely need to update are labelled as deprecated and do emit warnings when you use them.
