### ISSUE TITLE
FR: list_rbind - keep 0-row tibbles if in named list

### ISSUE THREAD

**Issue by werkstattcodes** [tidyverse/purrr#1116]
First, once again many thanks for all the wonderful packages you've been contributing.

I was wondering whether an option like `keep_empty=T` would make sense for `list_rbind`.

The use case is the following: 

Let's say I have a list with named elements. The elements are tibbles.
I would like to convert the list into one single tibble. purrr's `list_rbind` works, with the critical shortcoming (at least for my purpose) that it drops the element which is a 0-row tibble (although it is a named element).

``` r
library(tidyverse)

li <- list("a"=tibble(x=1), "b"=tibble(x=2), "c"=tibble(x=NULL))
li
#> $a
#> # A tibble: 1 × 1
#>       x
#>   <dbl>
#> 1     1
#> 
#> $b
#> # A tibble: 1 × 1
#>       x
#>   <dbl>
#> 1     2
#> 
#> $c
#> # A tibble: 0 × 0


li %>% purrr::list_rbind(., names_to="element_names")

#> # A tibble: 2 × 2
#>   element_names     x
#>   <chr>         <dbl>
#> 1 a                 1
#> 2 b                 2
```

The outcome I am looking for would be
```
#>   element_names     x
#>   <chr>         <dbl>
#> 1 a                 1
#> 2 b                 2
#> 3 c                 NA
```

I am aware that there are several ways to achieve this result (I had a pertaining question on SO [here](https://stackoverflow.com/questions/77866061/how-to-keep-named-but-0-row-tibbles-in-a-list-with-list-rbind?noredirect=1#comment137273357_77866061)), but think a `keep_empty` argument would make the entire procedure more elegant and less prone to the unintended loss of rows.

In my mental model it's a bit like with `unnest_longer`. I see that there is already a somewhat related  FR [here](https://github.com/tidyverse/purrr/issues/1096).

Many thanks.

**Comment by hadley** [comment]
Yeah, agreed. I'm going to merge this with #1096 since I think it'll be easiest to fix both at once.
