### ISSUE TITLE
Does purrr need to support backends?

### ISSUE THREAD

**Issue by hadley** [tidyverse/purrr#121]
Potential backends:
- In memory list
- Sharded list, spread over multiple cores
- NoSQL databases?

**Comment by hadley** [comment]
Implies we need to be looking at specified verbs as commonly implemented by noSQL dbs

**Comment by hadley** [comment]
First place to start would with ddR

**Comment by dandermotj** [comment]
If this splits out into a package 'purrrallel' would be a great name...

**Comment by hadley** [comment]
It would be natural to build these out for the `modify()` family, since that verb implies modification "in place", i.e. leaving the data on the remote compute engines. That will likely require making `modify()` an S3 generic, and only using `[<-` for the default method.

**Comment by lorenzwalthert** [comment]
Are there any plans to implement any of the potential backends listed at the top of this issue in the near future?

**Comment by lionel-** [comment]
Yes we'll start working on this soon(ish).

**Comment by lorenzwalthert** [comment]
Awesome.

**Comment by pat-s** [comment]
@lionel- Meanwhile its fall 2019 - could you give an update on the current status and plans?

**Comment by lionel-** [comment]
Other things have higher priorities currently. We're working on switching the tidyverse to vctrs.

**Comment by hadley** [comment]
We've decided not to do this in purrr, and we instead recommend [furrr](https://furrr.futureverse.org).
