### ISSUE TITLE
Special class for list output?

### ISSUE THREAD

**Issue by hadley** [tidyverse/purrr#144]
Could use `lst` and then provide methods for common base R functions, e.g.

``` R
resid.lst <- function(x, ...) map(x, resid, ...)
predict.lst <- function(x, newdata, ...) map2(x, newdata, predict, ...)
```

**Comment by lionel-** [comment]
When would that class be added to lists?

S3 will dispatch based on mode when no class is found so `resid.list()` would work as well.

**Comment by hadley** [comment]
You could, but it doesn't work for internal generics, and in general it's bad practice to define a method if you don't own either the class or the generic.

**Comment by hadley** [comment]
We could also provide a better default print method (analagous to `tbl_df`/`data_frame`).

**Comment by jennybc** [comment]
Better `print()` and `str()` for lists would bring such joy.

**Comment by hadley** [comment]
Would need some way to restrict the total number of items printed per element, combined over both depth and breadth. Want to truncate both very long lists and very deep lists.

**Comment by hadley** [comment]
Maybe this should go in lobstr?

**Comment by hadley** [comment]
Could also provide `[[` method that uses `extract()`.

Somewhat tempted to call these "libbles"

**Comment by hadley** [comment]
If we mapped `[[` to extract, we'd also want to provide a strict mode for `extract()`, throwing an error (?) when the index is not found. Base R isn't exactly consistent here:

``` r
x <- list()

x[[1]]
#> Error in x[[1]]: subscript out of bounds
x[["a"]]
#> NULL
x[["a"]][["b"]]
#> NULL
x[[c("a", "b")]]
#> Error in x[[c("a", "b")]]: no such index at level 1
```

**Comment by hadley** [comment]
Now pretty sure that we don't want such a class. (e.g.) I think the special printing provided by glue has ended up creating more trouble than it's worth.
