### ISSUE TITLE
Provide execution engines for map functions

### ISSUE THREAD

**Issue by hadley** [tidyverse/purrr#219]
The R6 object would have `init(n)`, `process(x)` and `complete()` methods, which would be called at the appropriate times, e.g.:

``` R
map <- function(.x, .f, ...) {
   .f$init(length(.x))

   .fun <- .f$process
   out <- .Call(map_impl, environment(), ".x", ".fun", "list")

   .f$complete(.x)
}
```

(in real code would either need to switch on type of `.f`, or tweak `as_function()` to always return R6 object)

Then you could easily implement progress bars as an adverb.

Worth considering if we should just use the identical callback interface to readr (i.e. https://github.com/hadley/readr/blob/master/R/callback.R). In some sense the map functions provide an API that is always chunked (where a chunk = 1 element).

cc @jcheng5, @lionel-

**Comment by hadley** [comment]
You could also imagine `.x` supporting a similar interface so that we could support arbitrary iterators/streams etc.

**Comment by lionel-** [comment]
Could belong in a package called impurrr ;)

This OO solution nicely structured and easy to use, my guess is that a purely functional approach would probably involve complicated monadic reasoning.

Maybe it's better to implement this as an adverb:

```{r}
ticked <- function(..x, .map, ..f, ..., .tick) {
  .tick$init(..x)

  fun <- function(`_x`, ...) {
    .tick$tick(`_x`)
    ..f(`_x`, ...)
  }
  res <- .map(..x, fun, ...)

  .tick$complete(..x)
  res
}

x %>% ticked(map, some_fun, .tick = my_counter)
```

This should work with other mapping functions such as `reduce()`.

**Comment by lionel-** [comment]
And `.tick` would be assigned a counter R6 object by default so that `ticked()` is directly useful for the end user with minimal typing.

**Comment by hadley** [comment]
@lionel- I think it's nicer to do `x %>% map(ticker(some_fun))` - i.e. the progress is a property of the low-level function, not the high-level map. That way it would compose more nicely with `safely()` etc.

**Comment by lionel-** [comment]
> the progress is a property of the low-level function, not the high-level map.

I think it's conceptually a property of the high-level map since the tickling needs to know about the collection rather than the individual elements. That's why your approach requires the tickling to be implemented inside every map function, as in the implementation you suggested.

> That way it would compose more nicely with safely()

Hmm I think `safely()` should still work as expected, so with the high-level adverb we have composability at both the higher and lower levels.

**Comment by hadley** [comment]
Let's think more about the goals here: the primary goal is generalise all existing map functions to support both parallel execution (at least on multicore), provide progress bars, and parallel execution with progress bars. We need to figure out how we will expose this to the user, how we'll implement internally, and whether or not we want to try and generalise.

From the user's perspective, I think parallel and progress should be implemented as arguments to the map functions, a la plyr. This is easy to understand, easy to find in the documentation, and doesn't involve adding any new functions to the namespace. 

From our perspective, we'll probably still want to implement these as adverbs to reduce code duplication internally (and to support potential future generalisations). I suspect we'll need three: progress, parallel, and progress + parallel, as progress bars for parallel computations will have to work in a completely different way compared to purely local computation. We may need more if we implement multiple styles of parallel (e.g. preschedule vs. live scheduling). This is somewhat orthogonal to #121, although we could possibly rely on distributed objects for pre-scheduled parallel, and an argument to map for live-scheduled parallel.

The question then is should they be adverbs over the map functions or over the mapped functions? Thinking about it now, adverbs over the map functions do seem more natural, since they are the interface that we want to modify.

**Comment by hadley** [comment]
I'm now leaning more towards the idea of execution engines (i.e. serial, parallel-queue, parallel-scheduled), each of which would have the ability to display a progress bar.  It's now feeling to me that that distributed data structures belongs somewhere else, although we still might want to make purrr  functions generic in order to facilitate implementation in another package (possibility one package could provide distributed objects for both purrr and dplyr).

**Comment by dleutnant** [comment]
Since this issue isn't updated for a while I'm just wondering if there are any news about a parallel version of `purrr::map()`, such as `purrr::map(.x, .f, cl, ...)` (assuming cl is a cluster object)?

**Comment by hadley** [comment]
This issue will be updated once there is news. I've deleted your comment to avoid cluttering the discussion.

**Comment by hadley** [comment]
We've decided not to do this in purrr, and we instead recommend [furrr](https://furrr.futureverse.org).
