### ISSUE TITLE
Propagate signatures in function operators

### ISSUE THREAD

**Issue by lionel-** [tidyverse/purrr#235]
Would involve parsing for `...` in function bodies and replacing it with expanded arguments.

**Comment by lionel-** [comment]
still nebulous to me ;) I'd have to start experimenting to see more clearly. Maybe we could make something simple like this work:

```r
with_signature(fn, function(.x) {
    invoke(fn, list(.x, formals(fn)[-1])
  }
)
```

This replace the first argument by position (a common occurrence in purrr), and would add a `.x <- real_first_arg_name` statement at the start of the function. We might also want to match by name.

**Comment by hadley** [comment]
It seems like it's going to be hard to do this while preserving the existing `as_function()` semantics

**Comment by hadley** [comment]
This almost works:

```R
negate <- function(.p) {
  p <- tidy_capture(.p)

  if (is.function(.p)) {
    f <- formals(.p)
    tidy_interp(function(... = UQS(f)) !UQE(p)(UQS(f)))
  } else {
    .p <- as_mapper(.p)
    function(...) !.p(...)
  }
}
```

**Comment by hadley** [comment]
Oh, finishing it off is pretty simple:

```R
negate <- function(.p) {
  p <- tidy_capture(.p)

  if (is.function(.p)) {
    args <- map(names(formals(.p)), as_symbol)
    n <- tidy_interp(function() !UQE(p)(UQS(args)))
    formals(n) <- formals(.p)
    environment(n) <- f_env(p)
    n
  } else {
    .p <- as_mapper(.p)
    function(...) !.p(...)
  }
}

negate(mean)
#> function (x, ...) 
#> !mean(x, ...)
```

**Comment by hadley** [comment]
But then you might as well make the function from scratch:

```R
negate <- function(.p) {
  p <- tidy_capture(.p)

  if (is.function(.p)) {
    args <- map(names(formals(.p)), as_symbol)
    body <- tidy_quote({
      !UQE(p)(UQS(args))
    })
    new_fn(formals(.p), f_rhs(body), f_env(p))
  } else {
    .p <- as_mapper(.p)
    function(...) !.p(...)
  }
}
```

**Comment by hadley** [comment]
And a nicer branch for formula:

```R
negate <- function(.p, ...) {
  p <- tidy_capture(.p)

  if (is.function(.p)) {
    args <- map(names(formals(.p)), as_symbol)
    body <- tidy_quote({
      !UQE(p)(UQS(args))
    })
    new_fn(formals(.p), f_rhs(body), f_env(p))
  } else if (is_formula(.p)) {
    p <- tidy_quote(!(UQ(f_rhs(p))))
    as_mapper(p)
  } else {
    .p <- as_mapper(.p)
    function(...) !.p(...)
  }
}
```

**Comment by hadley** [comment]
The same approach isn't going to work for (e.g.) `safely()`:

```R
safely <- function(.f, otherwise = NULL, quiet = TRUE) {
  .f <- as_mapper(.f)

  body(.f) <- tidy_interp(quote({
    capture_error(!!body(.f), otherwise = !!(otherwise), quiet = !!(quiet))
  }))

  .f
}
```

Because we're preserving the environment of `.f` so it can't find `capture_error()`.

**Comment by hadley** [comment]
Functions that need similar treatment are `safely()`, `quietly()`, `possibly()`, `partial()`, `compose()`, and possibly the `lift()` family.

**Comment by egnha** [comment]
Currently, `partial()` will produce functions with runtime error, e.g., `partial(function(x) NULL, a = "nonexistent")`, or worse, allow coding errors to pass silently, e.g., `partial(function(x, ...) NULL, a = "part of dots?")` — is `a` meant to be an argument of the function or is it really meant to be passed along with the dots?

Will the proposed change address this, say by signaling an error if an argument is not a named arguments of the function?

**Comment by hadley** [comment]
@egnha no, that's a totally discussion.

**Comment by hadley** [comment]
For possibly, one approach is:

```R
possibly <- function(.f, otherwise, quiet = TRUE) {
  .f <- as_mapper(.f)
  force(otherwise)

  `__args` <- formals(.f)
  `__args_matched` <- map(set_names(names(`__args`)), as_symbol)

  body <- expr({
    tryCatch(.f(!!!`__args_matched`),
      error = function(e) {
        if (!quiet)
          message("Error: ", e$message)
        otherwise
      }
    )
  })
  
  new_function(`__args`, body)
}
```

The downside is that the default arguments will get evaluated in a different environment, so if they depend on internal variables, they will fail (this is bad style IMO, but is not uncommon in base R functions).  

Eliminating this downside would require wrapping the default arguments with something like ``  `_fwd` <- function(x) eval_tidy(enquo(x))``.

**Comment by hadley** [comment]
I think the downsides of doing this for the more complicated function operators outweigh the benefits, so I'm going to close.
