### ISSUE TITLE
lift function to operate on list arguments in parallel

### ISSUE THREAD

**Issue by dgrtwo** [tidyverse/purrr#244]
I'd be interested in a `lift_` function that would convert functions to operate on parallel lists. 

Right now I use map if there's one argument or map2 if there are two, but would like an alternative with more flexibility for several named arguments.

One start is lifting `pmap` with `lift_ld`:

``` r
library(purrr)

lift_pmap <- function(.f) {
  lift_ld(pmap, .f = .f)
}
```

This works pretty well when every input is a vector or a list:

``` r
lift_pmap(sum)(1:2, 3:4)
#> [[1]]
#> [1] 4
#> 
#> [[2]]
#> [1] 6
lift_pmap(sum)(1:2, list(3, 4))
#> [[1]]
#> [1] 4
#> 
#> [[2]]
#> [1] 6

# works for individual vector inputs
lift_pmap(sum)(1:2, c(3, NA), na.rm = TRUE)
#> [[1]]
#> [1] 4
#> 
#> [[2]]
#> [1] 2
```

There's an important variation where it fails, which is if certain arguments are not lists (or vectors of length 1/same length), but should be consistent for everything. For example:

``` r
mtcars_spl <- split(mtcars, mtcars$cyl)
fits <- lift_pmap(lm)(formula = mpg ~ cyl, data = mtcars_spl)
#> Error: Element 1 is not a vector (language)
```

(Imagine there were multiple list arguments besides the formula). This is manageable with `pmap` but I find it a very counterintuitive order:

``` r
pmap(list(data = mtcars_spl), lm, formula = mpg ~ cyl)
```

Here is a start towards such a function that handles the above case. It suffers from the problem that argument order may be reshuffled and therefore need names. (That could be handled by instead converting non-list arguments to a list but there may be better ways; just leaving it here).

```
lift_pmap <- function(.f) {
  function(...) {
    lst <- list(...)

    is_vec_lst <- map_lgl(lst, ~ is.vector(.) || is.list(.))
    lst_args <- lst[is_vec_lst]
    same_args <- lst[!is_vec_lst]

    do.call(pmap, c(list(lst_args, .f), same_args))
  }
}

fits <- lift_pmap(lm)(formula = mpg ~ cyl, data = mtcars_spl)
```

**Comment by dgrtwo** [comment]
In retrospect I realize treating arguments as "same for all" if they're not lists isn't enough, since data frames and S3 objects are all lists (e.g. if I want to pass the same data frame in every function call, I'm out of luck). There are some clumsy ways I could think of to distinguish "static" arguments (e.g. wrapping it with some kind of sentinel function) but can see a lot of challenges along the way.

**Comment by jennybc** [comment]
Maybe I don't follow, but it feels like this is what `pmap()` already does. You can use it to, say, apply `lm()` to several lists or vectors in parallel and use a static argument (`x = TRUE` in my example). But is your point that this just feels weird or the syntax is awkward?

``` r
library(tibble)
z <- tibble(
  formula = list(mpg ~ disp, mpg ~ hp, mpg ~ wt),
  data = split(mtcars, mtcars$cyl),
  y = c(TRUE, FALSE, TRUE)
)
fits <- pmap(z, lm, x = TRUE)
fits[[1]][["y"]]
#>     Datsun 710      Merc 240D       Merc 230       Fiat 128    Honda Civic 
#>           22.8           24.4           22.8           32.4           30.4 
#> Toyota Corolla  Toyota Corona      Fiat X1-9  Porsche 914-2   Lotus Europa 
#>           33.9           21.5           27.3           26.0           30.4 
#>     Volvo 142E 
#>           21.4
coef(fits[[1]])
#> (Intercept)        disp 
#>  40.8719553  -0.1351418
fits[[2]][["y"]]
#> NULL
coef(fits[[2]])
#>  (Intercept)           hp 
#> 20.673851133 -0.007613269
fits[[3]][["x"]]
#>                     (Intercept)    wt
#> Hornet Sportabout             1 3.440
#> Duster 360                    1 3.570
#> Merc 450SE                    1 4.070
#> Merc 450SL                    1 3.730
#> Merc 450SLC                   1 3.780
#> Cadillac Fleetwood            1 5.250
#> Lincoln Continental           1 5.424
#> Chrysler Imperial             1 5.345
#> Dodge Challenger              1 3.520
#> AMC Javelin                   1 3.435
#> Camaro Z28                    1 3.840
#> Pontiac Firebird              1 3.845
#> Ford Pantera L                1 3.170
#> Maserati Bora                 1 3.570
#> attr(,"assign")
#> [1] 0 1
coef(fits[[3]])
#> (Intercept)          wt 
#>   23.868029   -2.192438
```

**Comment by jennybc** [comment]
Having read the twitter discussion now, I have a better sense of what you're after .... You don't want to put these args into a list/data.frame first. I think I just like the neatness/safety of putting them into a tibble.

**Comment by lionel-** [comment]
This seems relevant: https://github.com/hadley/dplyr/issues/968#issuecomment-168774099

**Comment by dgrtwo** [comment]
@jennybc That's a really good question- I do like the neatness of keeping them together first, but I'm put off when they're already together, but need to be renamed or ignored. The example (from Twitter) is something like:

```
library(dplyr)
library(ISLR)
library(purrr)
library(modelr)

Smarket %>%
  crossv_kfold(k = 20) %>%
  mutate(model = pmap(list(data = train), lm, formula = Today ~ Lag1 + Lag2))
```

In a normal lm call, the order might be **function**, **fixed args**, **list args** (like data). Here it is **list args**, **function**, **fixed args**. 

I'm starting to realize what I really want is a version of `invoke_rows` that allows one to rename input arguments. If I could do:

```r
Smarket %>%
  crossv_kfold(k = 20) %>%
  invoke_rows(lm, ., Today ~ Lag1 + Lag2, data = train)
```

I'd be quite happy. Instead I'd have to do something more like

```r
Smarket %>%
  crossv_kfold(k = 20) %>%
  invoke_rows(function(train, ...) lm(Today ~ Lag1 + Lag2, train), .)
```

**Comment by jennybc** [comment]
> I'm put off when they're already together, but need to be renamed or ignored

Agree. I recently asked specifically about the "ignored" issue and @hadley advised use of `...`:

``` r
library(purrr)

df <- data.frame(x = 1:3, y = 3:1, z = letters[1:3])
f <- function(x, y, ...) x + y
pmap_dbl(df, f)
#> [1] 4 4 4
```

but this does add a new bit of friction, because you need to define `f` yourself.

The question you're raising seems different from what @lionel- links to. You've got heterogenous inputs in your lists. But that [`dplyr` issue](https://github.com/hadley/dplyr/issues/968#issuecomment-168774099) seems more about homogenous inputs. Of course reading that comment made me realize I have a current good example of that problem as well, so now I care about both!

**Comment by lionel-** [comment]
The parallelise function from the dplyr thread should work with heterogenous inputs. It's very close to what @dgrtwo proposes here. I'm not sure that we want the `.type` argument though, this doesn't seem to fit purrr's spirit anymore. E.g. we'd rather require an additional vector flatten at the end.

I think it'd make sense to have `pmap()` wrap non-vector inputs in a list and recycle those, that would solve the issue encountered by David.

The lifting functions could be `lift_dp()`, `lift_lp()`, and would it make sense to have `lift_vp()`? The latter would require homogenous inputs.

**Comment by hadley** [comment]
Another approach would be to have a variant of `pmap()` that uses `...` for all arguments, and requires a special call to indicate scalar arguments that should be passed to every call

```R
pmap(list(data = mtcars_spl), lm, formula = mpg ~ cyl)

# vs

qmap(lm, fixed(mpg ~ cyl), data = mtcars_spl)
```

**Comment by lionel-** [comment]
>  I find it a very counterintuitive order

Note that there's an easy fix:

```r
pmap(lm, formula = mpg ~ cyl, .l = list(data = mtcars_spl))
```

If the only issue is the argument order (and `lm()` is at fault here), maybe it's not worth making things more complicated. Having to wrap arguments in a list does make `pmap()` more difficult to reason about though.

**Comment by hadley** [comment]
Per #871, we do longer see the `lift_` functions as a core part of purrr, and hence won't be making any major changes to them.
