### ISSUE TITLE
Adverb that starts browser() on failure

### ISSUE THREAD

**Issue by hadley** [tidyverse/purrr#281]
Like this but in correct environment

```R
hopefully <- function(f) {
  function(...) {
    tryCatch(
      f(...),
      error = function(e) browser()
    )
  }
  
}
```

**Comment by robertness** [comment]
Your welcome!

**Comment by Deleetdk** [comment]
I've been using this function:

```
try_browse = function(expr) {
  #try
  .trial = try({
    y = eval(substitute(expr), parent.frame())
  })
  
  #catch
  if (inherits(.trial, "try-error")) eval(quote(browser()), parent.frame(n = 1))
  
  y
}
```

So basically encapsulate the error prone call in that and when it fails, you step right into where you want to be, including when inside implicit loops like `ddply` or `map_df`.

[I've also suggested trying to make a pipe version of this](https://github.com/tidyverse/magrittr/issues/133), but I couldn't figure out how to do that.

**Comment by hadley** [comment]
This works:

```R
hopefully <- function(f) {
  function(...) {
    withCallingHandlers(
      f(...),
      error = function(e) {
        # 1: h(simpleError(msg, call))
        # 2: .handleSimpleError(function (e)  <...>
        # 3: stop(...)
        ef <- eval_frame(4)
        eval(quote(browser()), env = ef$env)
      }
    )
  }
}

f <- function(x) {
  y <- 20
  if (x > 5) {
    stop("!") 
  } else {
    x
  }
}

map(1:6, hopefully(f))
```

But is fragile:

```R
options(warn = 2)
f <- function(x) {
  y <- 20
  if (x > 5) {
    warning("!") 
  } else {
    x
  }
}

map(1:6, hopefully(f))
```

@lionel- is there a better way here?

**Comment by lionel-** [comment]
This doesn't work in ESS because of some limitations of how it handles step-debugging.

I don't think it's that fragile, this just needs another handler for warnings that checks for `options("warn")`. The R code establishing restarts and handlers hasn't changed for 15 years, so in practice it's not as bad as it feels to just count the frames. Here is a version that works with warnings and in ESS:

```r
hopefully <- function(f) {
  function(...) {
    withCallingHandlers(
      f(...),
      error = function(e) {
        # 1: h(simpleError(msg, call))
        # 2: .handleSimpleError(function (e)  <...>
        # 3: stop(...)
        with_env(frame$env, on.exit({
          browser()
          NULL # Workaround ESS issue
        }))
        return_from(frame)
      },
      warning = function(e) {
        if (getOption("warn") == 2) {
          frame <- eval_frame(7)
          with_env(frame$env, on.exit({ browser(); NULL }))
          return_from(frame)
        }
      }
    )
  }
}
```

**Comment by hadley** [comment]
Unfortunately your work around doesn't work in RStudio. I think we'll have to switch based on`.Platform$GUI`. What does ESS use? 

For reasons I don't understand it no longer works when I extract the `browser()` logic into a separate function:

```R
browse_in_frame <- function(frame) {
  if (.Platform$GUI == "ESS") {
    # Workaround ESS issue
    with_env(frame$env, on.exit({
      browser()
      NULL
    }))
    return_from(frame)
  } else {
    eval(quote(browser()), envir = frame$env)
  }
}
```

**Comment by hadley** [comment]
Complete code in #304
