### ISSUE TITLE
map_df fails on character vector as .f when .x contains null

### ISSUE THREAD

**Issue by Yeedle** [tidyverse/purrr#306]
Suppose I have a list with the following structure:
```r
ls <- list(NULL, 
           list("foo"=data_frame(bar=c(1, 2, 3))), 
           list("foo"=data_frame(bar=c(4,5,6))))
```
using `map_df` to extract as a dataframe works well:
```r
map_df(ls, ~.x[["foo"]])
```
```r
## # A tibble: 6 × 1
##     bar
##   <dbl>
## 1     1
## 2     2
## 3     3
## 4     4
## 5     5
## 6     6
```

But if I pass in the name as an atomic character vector, I get an error:
```r
map_df(ls, "foo")
```
```r
## Error: `x` must be a vector (not a NULL)
```

**Comment by hadley** [comment]
This is fixed in the dev version. (And in the future, can you please use the reprex package to create reprexes)

**Comment by hadley** [comment]
(Not sure whether it's the dev version of purrr or dplyr, but it definitely works for me)

**Comment by Yeedle** [comment]
Installed the dev version of purrr and it works for me too now. Thanks!
