### ISSUE TITLE
rlang reconciliation

### ISSUE THREAD

**Issue by hadley** [tidyverse/purrr#320]
Need to resolve inconsistencies, and make sure only lives in one place.  (purrr should probably re-export)

* [x] `set_names()`
* [x] `invoke()`
* [x] `rep_along()`
* [x] predicate functions
* [x] `%||%`
* [ ] `purrr::as_function()` (defunct in purrr 0.3.0)
* [ ] `%@%` (soft-deprecated in purrr 0.3.0)
* [ ] `list_along()` (soft-deprecated in rlang 0.2.0)
* [ ] `modify()` (questioning in rlang 0.3.0)
* [ ] `prepend()` (questioning in rlang 0.3.0)
* [ ] `flatten()` (vctrs milestone)
* [ ] `squash()` (vctrs milestone)
* [ ] `splice()`

**Comment by lionel-** [comment]
Also `invoke()` is now in rlang as well.

**Comment by lionel-** [comment]
There's also the `flatten()` functions, which have slightly richer semantics in rlang. And purrr could gain the `squash()` family as well (recursive flattening).

**Comment by lionel-** [comment]
purrr's `%@%` needs to be soft-deprecated instead of reexported because unlike rlang's, it uses a non-NSE implementation.

**Comment by hadley** [comment]
As of today:

``` r
conflicted::conflict_scout(c("purrr", "rlang"))
#> 10 conflicts:
#> * `%@%`        : purrr, rlang
#> * `as_function`: purrr, rlang
#> * `flatten`    : purrr, rlang
#> * `flatten_chr`: purrr, rlang
#> * `flatten_dbl`: purrr, rlang
#> * `flatten_int`: purrr, rlang
#> * `flatten_lgl`: purrr, rlang
#> * `flatten_raw`: purrr, rlang
#> * `invoke`     : purrr, rlang
#> * `splice`     : purrr, rlang
```

<sup>Created on 2022-08-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
* `%@%` is deprecated
* `as_function()` has been removed
* `flatten_*()` will be deprecated in #912 
* `invoke()` will be deprecated in #911.
* `splice()` is deprecated

So I think we're done here.
