### ISSUE TITLE
else clause in map_if

### ISSUE THREAD

**Issue by GuiMarthe** [tidyverse/purrr#324]
I fell that i order for the map_if function to be really useful should have the possibility of calling an "else" function if the outcome of .predicate is false.

By default it should leave the object iterated alone, and not return anything.

**Comment by lionel-** [comment]
I don't think that will happen because `...` can only be forwarded in one function. To deal with this I usually do it that way:

```r
cnd <- map_lgl(x, predicate)
x <- map_if(x, cnd, fun1)
x <- map_if(x, !cnd, fun2)
```

**Comment by GuiMarthe** [comment]
Yes yes that is a possible solution. But it would be more concise if one could do it in one line, like>
` x <- map_if(x, cnd, fun1, fun2)`
Also, it makes sense since it sort of resembles `ifelse` and `if_else`

**Comment by lionel-** [comment]
in purrr's syntax, `fun2` is passed to `fun1` in your example.

**Comment by hadley** [comment]
We could have `map_if_else(.x, .cnd, .true, .false, ...)`

**Comment by lionel-** [comment]
without the dots?

**Comment by hadley** [comment]
We could still have dots, but they'd be passed to both `.true` and `.false` so they wouldn't be that useful.  Should probably have `.na` too, for completeness.

**Comment by Athospd** [comment]
Why the following solution is not viable?

`
map_if_else <- function (.x, .p, .true, .false, .na = identity, ...) {
  
  sel <- purrr:::probe(.x, .p)
  out <- list_along(.x)
  out[which(sel)] <- map(.x[which(sel)], .true, ...)
  out[which(!sel)] <- map(.x[which(!sel)], .false, ...)
  out[is.na(sel)] <- map(.x[is.na(sel)], .na, ...)
  
  set_names(out, names(.x))
}`

regards
