### ISSUE TITLE
purrr 0.2.2.2 Error message with map function

### ISSUE THREAD

**Issue by stephLH** [tidyverse/purrr#325]
With the last update of purrr, when I use the map function on a table, I get this error message :

`> map(table, class)`
`Error in map(table, class) : object 'map_impl' not found`

It is a simple table with two character columns.

**Comment by lionel-** [comment]
could you post your `devtools::session_info()` please. Did you restart your session after install?

**Comment by stephLH** [comment]
Sorry for this report...
After a session restart, everything's fine.
Thanks very much!
