### ISSUE TITLE
map_df() still calls dplyr::bind_rows()

### ISSUE THREAD

**Issue by jennybc** [tidyverse/purrr#328]
Even though the NEWS says that dplyr is no longer dependency, I get test failures on another package that uses purrr, because `there is no package called 'dplyr'`.

It appears that `map_df()` still relies on `dplyr::bind_rows()`:

``` r
library(purrr)
packageVersion("purrr")
#> [1] '0.2.2.9000'
map_df
#> function (.x, .f, ..., .id = NULL) 
#> {
#>     .f <- as_mapper(.f, ...)
#>     res <- map(.x, .f, ...)
#>     dplyr::bind_rows(res, .id = .id)
#> }
#> <environment: namespace:purrr>
```

There are other uses of dplyr too. Am I just missing something?

**Comment by lionel-** [comment]
While dplyr is no longer a hard dependency, purrr still relies on it for binding data frames. So you need to be explicit about the dependency in the description file by adding dplyr to `Imports:`.

**Comment by lionel-** [comment]
We should probably mention that dplyr needs to be installed in the documentation of those functions.
