### ISSUE TITLE
purrr::isolate conflicts with shiny::isolate

### ISSUE THREAD

**Issue by t-kalinowski** [tidyverse/purrr#329]
Would it be possible to rename the `purrr::isolate` to something else?

**Comment by hadley** [comment]
Yeah we should. I think @lionel- had a better name.

**Comment by t-kalinowski** [comment]
Also, seems equivalent to dplyr::pull....

**Comment by lionel-** [comment]
we were going to rename it to `pluck()` I think

@t-kalinowski it's actually quite different, it doesn't do NSE and it allows to extract several elements levels deep

**Comment by hadley** [comment]
Renamed to pluck.
