### ISSUE TITLE
docs: explain use of magrittr with purrr

### ISSUE THREAD

**Issue by lsloan** [tidyverse/purrr#331]
The purrr docs need to better explain the use of magrittr with purrr.

The ["Usage" section of `README.md`](/tidyverse/purrr/blob/master/README.md#usage) uses the magrittr `%>%` pipe operator without explanation.  I'm lucky that I'd just read about magrittr, so I understood what it was.  However, anyone with only basic R experience would probably get the impression that operator is provided by purrr as well.

**Comment by hadley** [comment]
Well, it's re-exported by purrr, so you don't need to install or load magrittr.
