### ISSUE TITLE
Values as constant functions

### ISSUE THREAD

**Issue by egnha** [tidyverse/purrr#334]
It is occasionally useful to treat values as constant functions.

While it is trivial to do this oneself, might the following verb nonetheless have a place in purrr's vocabulary?:
```R
as_const_function <- function(x) {
  force(x)
  function(...) x
}
```

**Comment by amarchin** [comment]
@egnha could you make some examples? In which occasion is it useful?

**Comment by lionel-** [comment]
If the functional calls `as_function()`, you can use the lambda notation: `~ 1L`.

**Comment by egnha** [comment]
@amarchin For example, if you want a function to return a certain value upon failure, then that value would be viewed as a constant function, e.g., `tryCatch(expr, error = function(e) NA)`.

@lionel- `as_function()` fits the bill. Thanks for bringing that to my attention.
