### ISSUE TITLE
update_list does not allow "mutation"

### ISSUE THREAD

**Issue by amarchin** [tidyverse/purrr#335]
Reading the documentation of `update_list` I thought that the user was allowed to "mutate" one of the list elements, but it does not seem to be the correct interpretation according to the following example:

```r
my_list <- list(x = list(1, 2, 3), y = list(4, 5, 6))
update_list(my_list, x = ~ keep(x, ~ .x < 2))
```
> $x
> $x[[1]]
> [1] 1
>
> $x[[2]]
> [1] 2
>
> $x[[3]]
> [1] 3
>
>
> $y
> $y[[1]]
> [1] 4
>
> $y[[2]]
> [1] 5
>
> $y[[3]]
> [1] 6

Doing this with data frames raises erros:

```r
my_list_df <- list(x = iris, y = mtcars)
update_list(my_list_df, x = ~ filter(x, Petal.Width > 0.3))
``` 

> Error in `[[<-.data.frame`(`*tmp*`, v, value = c(5.4, 5.7, 5.4, 5.1, 5.1,  : 
  replacement has 109 rows, data has 150

Since the the function produces a new list we are handling the object as it would be immutable. Do you think it is acceptable to allow this kind of behavior?

**Comment by hadley** [comment]
In its current form, this function is rather ill-formed, as it doesn't adhere the either the principles of tidy evaluation or function shortcuts exposed in the rest of purrr.

**Comment by lionel-** [comment]
We'll probably provide a `dplyr::mutate()` method in one of our packages. Maybe in tibble since this method is a natural complement to `tibble::lst()`. `update_list()` will likely be deprecated sometime next year.

**Comment by hadley** [comment]
Or the libble package 😉

**Comment by amarchin** [comment]
That sounds interesting 😃
