### ISSUE TITLE
Could as_vector() and simplify() have some notion of .default?

### ISSUE THREAD

**Issue by jennybc** [tidyverse/purrr#336]
I want to promote elements of a list-column into a top-level variable, atomic if possible. But w/o having to say exactly which type I expect. `simplify()` comes really close, but there's no way to finesse NULLs.

Is there some better way to do this with current technology?

``` r
library(purrr)
library(tibble)
library(dplyr)

## imagine a tibble with a list-column that is homogeneous in the sense
## that, if an element is present, it has consistent type
(x <- tribble(
  ~ name, ~ stuff,
  "alpha", list(letter = "a", logical = TRUE),
  "beta", list(integer = 2L, logical = FALSE),
  "gamma", list(letter = "c", integer = 3L)
))
#> # A tibble: 3 x 2
#>    name      stuff
#>   <chr>     <list>
#> 1 alpha <list [2]>
#> 2  beta <list [2]>
#> 3 gamma <list [2]>

## to "promote" elements from the list-column into top-level vars
## I have to inject lots of info about type and NULL handling
x %>% 
  mutate(letter = map_chr(stuff, "letter", .default = NA_character_),
         integer = map_int(stuff, "integer", .default = NA_integer_),
         logical = map_lgl(stuff, "logical", .default = NA))
#> # A tibble: 3 x 5
#>    name      stuff letter integer logical
#>   <chr>     <list>  <chr>   <int>   <lgl>
#> 1 alpha <list [2]>      a      NA    TRUE
#> 2  beta <list [2]>   <NA>       2   FALSE
#> 3 gamma <list [2]>      c       3      NA
```

``` r
## I wish I could do this
x %>% 
  mutate(letter = simplify(map(stuff, "letter")),
         integer = simplify(map(stuff, "integer")),
         logical = simplify(map(stuff, "logical")))
```

``` r
## also tantalizingly close, but again the NULLs ruin everything
transpose(x$stuff, .names = c("letter", "integer", "logical")) %>%
  as_tibble()
#> # A tibble: 3 x 3
#>      letter   integer   logical
#>      <list>    <list>    <list>
#> 1 <chr [1]>    <NULL> <lgl [1]>
#> 2    <NULL> <int [1]> <lgl [1]>
#> 3 <chr [1]> <int [1]>    <NULL>
```

**Comment by dleutnant** [comment]
I ran into a similar problem for the [influxdbr Package](https://github.com/dleutnant/influxdbr/).
Maybe this helps:

```
x %>% 
  mutate(letter = simplify(map(stuff, "letter")),
            integer = simplify(map(stuff, "integer")),
            logical = simplify(map(stuff, "logical"))) %>% 
  # select vars
  select(letter:logical) %>% 
  # convert NULL to NA
  map( ~ map(., ~ . %||% NA)) %>% 
  # unlist to get type
  map( ~ unlist(.)) %>% 
  # create tibble
  bind_cols(.)
```

**Comment by dleutnant** [comment]
or eventually this:

```r
> x$stuff %>% dplyr::bind_rows(.)
# A tibble: 3 x 3
  letter logical integer
   <chr>   <lgl>   <int>
1      a    TRUE      NA
2   <NA>   FALSE       2
3      c      NA       3
```

**Comment by lionel-** [comment]
It seems reasonable for `simplify()` to treat `NULL` as type-agnostic, and promote them to `NA`s if the list is otherwise simplifiable to a vector.

I wonder if this should also be handled by something like the vector constructors of rlang, e.g. `chr()`, `int()`, `lgl()`, which have implicit splicing semantics and so are happy to handle lists. Should we have `full_chr()` etc that treat `NULL` as `NA`? Or maybe that's the job of coercers like `as_character()`?

**Comment by lionel-** [comment]
I was thinking that eventually `simplify(x)` would be an alias for `vec_c(!!!x)`, but that means `NULL` would be treated as empty. Maybe that suggests it should be `vec_cast(x, vec_common_type(!!!x))` instead?

I currently see:

```r
vctrs::vec_cast(list(1L, NULL), int())
#> [1]  1 NA
#> Warning message:
#> Lossy cast from list to integer
#> Locations: 2 
```

However that's probably an overlook. `NULL` elements should be treated as `NA` when casting from list to atomic.

**Comment by lionel-** [comment]
> Maybe that suggests it should be vec_cast(x, vec_common_type(!!!x)) instead?

Thinking more about it, it makes sense for the result to have the same length as the input, so yes.

**Comment by jennybc** [comment]
`simplify()` should also be willing to downcast `NA`s, I think. I suspect we get this "for free" with vctrs anyway, but I'll record it. Maybe it will make a good test.

``` r
library(purrr)

class(simplify(list(1:2, 3:4)))
#> [1] "integer"
simplify(list(1:2, 3:4, NA))
#> [[1]]
#> [1] 1 2
#> 
#> [[2]]
#> [1] 3 4
#> 
#> [[3]]
#> [1] NA
class(simplify(list(1:2, 3:4, NA)))
#> [1] "list"

class(simplify(list("a", "b")))
#> [1] "character"
simplify(list("a", "b", NA))
#> [[1]]
#> [1] "a"
#> 
#> [[2]]
#> [1] "b"
#> 
#> [[3]]
#> [1] NA
class(simplify(list("a", "b", NA)))
#> [1] "list"
```

<sup>Created on 2019-08-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by hadley** [comment]
The motivating example is now better solved by tidyr:

``` r
library(tidyr)

df <- tribble(
  ~ name, ~ stuff,
  "alpha", list(letter = "a", logical = TRUE),
  "beta", list(integer = 2L, logical = FALSE),
  "gamma", list(letter = "c", integer = 3L)
)

df |> unnest_wider(stuff)
#> # A tibble: 3 × 4
#>   name  letter logical integer
#>   <chr> <chr>  <lgl>     <int>
#> 1 alpha a      TRUE         NA
#> 2 beta  <NA>   FALSE         2
#> 3 gamma c      NA            3
```

<sup>Created on 2022-08-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

But I think we still need to re-consider the role of `simplify()` and friends now that we have vctrs.

**Comment by hadley** [comment]
But I'll do that in a separate issue.
