### ISSUE TITLE
Could map_dbl return empty vector for empty elements?

### ISSUE THREAD

**Issue by strengejacke** [tidyverse/purrr#337]
```
unlist(lapply(list(1), function(x) x[-1]))
#> numeric(0)

purrr::map_dbl(list(1), ~ .x[-1])
#> Error: Result 1 is not a length 1 atomic vector
```

I'm not sure if this would violate the design philosophy or so, but I sometimes have lists with empty elements, where `map_dbl` stops. Returning an empty vector, at least as option, would be nice here (and probably also useful for other `map_*()`-functions)

**Comment by amarchin** [comment]
A possible solution could be creating your own version of the function using `safely`

```r
safe_map_dbl <- safely(map_dbl, otherwise = rlang::dbl())
```

**Comment by strengejacke** [comment]
That's a clever solution and would fit my needs! Maby it's still worth thinking about this issue for users in general who don't think of this solution (just like me)?

**Comment by amarchin** [comment]
Because `safely` return a list that contains the returned value and the error (or NULL if there is no error). If you want only the value you should use `possibly`.

```r
safe_map_dbl <- possibly(map_dbl, otherwise = rlang::dbl())
```

**Comment by amarchin** [comment]
@strengejacke I didn't read correctly your reply. Of course my proposal in that case doesn't work. Sorry for that.

**Comment by strengejacke** [comment]
Yes, I know that you can catch errors with safely (as alternative to trycatch), however, I just wanted a simple equivalent to the `lapply()`-command. I _could_ write an own function with safely, that would finally return the requested result, but that's of course no benefit in terms of typing ;-)

**Comment by hadley** [comment]
Use `.default = NA`

**Comment by strengejacke** [comment]
`map_dbl()` has no `.default`-argument.

**Comment by hadley** [comment]
It does in the dev version

**Comment by strengejacke** [comment]
strange, then something with installing the dev-version went wrong. I'll check tomorrow on my other machine and get back if I still have these issues.

**Comment by strengejacke** [comment]
Still not resolved yet:

```
unlist(lapply(list(1), function(x) x[-1]))
#> numeric(0)

purrr::map_dbl(list(1), ~ .x[-1], .default = NA)
#> Error: Result 1 is not a length 1 atomic vector
```

```
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] httr_1.2.1       compiler_3.4.1   magrittr_1.5     R6_2.2.2         tools_3.4.1      withr_1.0.2     
 [7] curl_2.7         memoise_1.1.0    knitr_1.16       git2r_0.18.0     digest_0.6.12    rlang_0.1.1     
[13] devtools_1.13.2  purrr_0.2.2.9000
```

**Comment by strengejacke** [comment]
Another example:

```
l <- list(1, 4, c(4, 5))
l[[2]] <- l[[2]][-1]
purrr::map_dbl(l, ~ .x, .default = NA)
unlist(lapply(l, function(x) x))
```

**Comment by hadley** [comment]
Oh this is a different problem - it's your function returning the empty vector, so it's your responsibility.

**Comment by strengejacke** [comment]
It's just that the behaviour is slightly different to `lapply()`, which simply returns an empty element, and does not throw an error. It would be great to have (at least as an option) a similar behaviour for `map_*()` as well, so you don't need to mix your code with `lapply()` and `map*()`.

**Comment by hadley** [comment]
If you want the same behaviour as `lapply()`, use `map()`.

**Comment by strengejacke** [comment]
Ok, so I would use 

```
purrr::map(list(1), ~ .x[-1]) %>% purrr::flatten_dbl()
```

I just thought that `map_dlb()` also works as shortcut for `map()` and `flatten()` (or `unlist()`).

**Comment by hadley** [comment]
`map_dbl()` checks that each of the function outputs is a double. It is designed to be strict so that you are quickly alerted to type problems in your code, instead of them emerging several steps later in a confusing way.

**Comment by milescoi** [comment]
` list_with _some_NULL's %>% map(function(x){ ifelse(is.null(x) == T, NA, as.numeric(x))}) %>% unlist()`

This helped me

**Comment by jzadra** [comment]
Would be great to have a couple examples of how `.default` works in the map2 help documentation.  It's not even listed as an argument currently.
