### ISSUE TITLE
purrr::map and return datatype

### ISSUE THREAD

**Issue by GuiMarthe** [tidyverse/purrr#340]
I think that having `map` always return a list and having `map_*` for returning specific data types is an awesome idea.

However, what is the preferred approach to having arbitrary data types, such as datetime, or objects?

Shouldn't there be a way of telling `map` (or idk, `map_type`) that a pre-determined type will be returned?

**Comment by david-jankoski** [comment]
as far as i know dates/datetimes are just doubles underneath and fancier objects are built up from lists.

**Comment by jankislinger** [comment]
@david-jankoski that is true, but `map_dbl` omits the class

```
purrr::map_dbl(1:5, as.POSIXct, origin = "1970-01-01")
#> [1] 1 2 3 4 5
purrr::map(1:5, as.POSIXct, origin = "1970-01-01")
#> [[1]]
#> [1] "1970-01-01 01:00:01 CET"
#> 
#> [[2]]
#> [1] "1970-01-01 01:00:02 CET"
#> 
#> [[3]]
#> [1] "1970-01-01 01:00:03 CET"
#> 
#> [[4]]
#> [1] "1970-01-01 01:00:04 CET"
#> 
#> [[5]]
#> [1] "1970-01-01 01:00:05 CET"
```

**Comment by GuiMarthe** [comment]
Precisely what I've experienced @jankislinger. I'm not saying this is not the intended behavior, which it is.
But i feel (and perhaps I am wrong) that with all the functions in  purrr (`modify`, `modify_if`, `modify_depth`, `map_*`, `map2_*`) this ability to handle arbitrary datatypes might be needed.

I see two options:

- either a `.return_type` argument is passed onto all functions (this breaks the whole idea of `map` only returning a list, and seems to much work)

- have a reliable function the simplifies the return list but coerces/keeps the elements as an specified data type (this might be a little focused on my problem of handling datetime/"POSIXct" "POSIXt" objects withing purrr, but this might generalize generic, user crafted datatypes.

**Comment by GuiMarthe** [comment]
Currently, using @jankislinger little example, this is how `as_vector` and `simplify` work, when a `.type` is not passed:

**Comment by amarchin** [comment]
I can share with you Hadley's reply to a question of mine on a similar topic:

https://github.com/tidyverse/purrr/issues/295
