### ISSUE TITLE
purrr over matrix columns and rows

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/purrr#341]
Sometimes we have matrices and for sure there's `apply( , 1)` and `apply( , 2) ` but it might be useful to have something to `map` over columns and rows of a matrix, e.g. 

```
columns <- function(m){ map(seq_len(ncol(m)), ~m[,.] ) }
rows <- function(m){ map(seq_len(nrow(m)), ~m[.,] ) }
```

so that we could do: 

```
> m <- matrix( 1:20, nc = 2 )
> map_int( columns(m), sum )
[1]  55 155
> map_int( rows(m), sum )
 [1] 12 14 16 18 20 22 24 26 28 30
```

**Comment by LaDilettante** [comment]
With > 10 thumbs up, is this something considered within purrr's scope? 

I'm evaluating whether I can 100% move away from `apply` to `purrr`, and this is one thing `purrr` can't do yet.

Happy to contribute if it's considered within scope.

**Comment by dppalomar** [comment]
I totally agree. I would like to move from apply to purrr but this detail is missing... 
Two things I don't like about apply:
1) Say I have an nxm matrix and I apply some operation row-wise like sorting the elements. Then the output is a matrix of size mxn!!!  What the heck!!!  I don't like this.
2) Similarly, say I have an nxm matrix and I use apply to get the maximum row-wise, then the output is a vector of length n. Shouldn't it be a matrix of size nx1? Why is the type different? I don't like that either.

purrr is supposed to respect the types... So I hope purrr can deal with that... But don't know how...

Thanks!

**Comment by lionel-** [comment]
> this is one thing purrr can't do yet.

The current idea is to use `array_branch()` or `array_tree()` to transform the matrix/array to a list that you can map over:

```r
map_int(array_branch(m, 2), sum)
#> [1]  55 155

map_int(array_branch(m, 1), sum)
#> [1] 12 14 16 18 20 22 24 26 28 30
```

**Comment by hadley** [comment]
For now, matrices are still out of scope for purrr.

**Comment by NathanSiemers** [comment]
I find myself moving more and more with advanced matrix formats (sparse Matrix, h5ad, etc) in order to deal with very large data sets that would otherwise not fit in memory.  Support for these generally in the tidyverse would be wonderful.
