### ISSUE TITLE
Conflict between purrr::contains and dplyr::contains

### ISSUE THREAD

**Issue by ropolomx** [tidyverse/purrr#343]
I noticed that when I want to use `dplyr`'s  select helper `contains()` (version 0.7.0), there is a conflict with the `contains` function of `purrr` (version 0.2.2.2). 

For example:

``` r
library(dplyr)
library(purrr)

iris %>% select(contains("Petal"))

Error in .p(.x[[i]], ...) : argument ".y" is missing, with no default
```

My goal was to use `purrr::map` and `dplyr::contains` to select certain columns for each data frame in a list of data frames. Although I can specify the package namespace or use other select helpers to achieve this, I thought you would be interested in knowing about this conflict.

**Comment by david-jankoski** [comment]
when you load the libraries in that order - you do get a warning that `dplyr`'s `contains` is masked though.

**Comment by lionel-** [comment]
`contains()` has been renamed to `has_element()` to avoid that conflict.

**Comment by ropolomx** [comment]
Thank you so much for working on that, @lionel- . 
@david-jankoski: Yes, I could have included the namespace before the function, like `dplyr::contains` or `purrr::contains`. Glad to see the function has been renamed.
