### ISSUE TITLE
partial() fails for functions that introspect context

### ISSUE THREAD

**Issue by egnha** [tidyverse/purrr#349]
Example:
```R
ls_all <- purrr::partial(ls, all.names = TRUE)

ls(all.names = TRUE)
#> [1] ".Random.seed" "ls_all"

# ought to match ls(all.names = TRUE)
ls_all()
#> [1] "..."

ls_all(.GlobalEnv)
#> [1] ".Random.seed" "ls_all" 
```
The problem is that `ls_all()` doesn't faithfully mimic calling `ls()` (with `all.names = TRUE`), because it doesn't call `ls()` from the calling environment.

Here’s a first pass at a work-around (ignoring the `.lazy`, `.env` arguments):
```R
# rename '.first' to '...first' to allow '.first' in '...'?
partial <- function(...f, ..., .first = TRUE) {
  defvals <- rlang::dots_list(...)
  if (rlang::is_empty(defvals))
    return(...f)
  ...subst_defvals <- function(call) {
    if (.first)
      fcall <- c(...f, defvals, rlang::node_cdr(call))
    else
      fcall <- c(...f, rlang::node_cdr(call), defvals)
    as.call(fcall)
  }
  
  rlang::set_attrs(
    function(...) {
      call <- ...subst_defvals(sys.call())
      rlang::eval_bare(call, parent.frame())
    },
    class = "partial_function"
  )
}
```
A minimal print method could be something like this:
```R
print.partial_function <- function(x, ...) {
  cat("<partial_function>\n")
  cat("\n* Default values:\n")
  cat(itemize_vals(environment(x)$defvals), "\n", sep = "")
  cat("\n* Original function:\n")
  print(environment(x)$...f)
  invisible(x)
}
itemize_vals <- function(vals) {
  vals <- lapply(vals, rlang::expr_label)
  paste(sprintf("%s = %s", names(vals), vals), collapse = "\n")
}
```

**Comment by egnha** [comment]
Here‘s a simpler implementation of `partial()`, that has the advantage of preserving the formals of `...f`, so far as that is possible:
```R
library(rlang)

partial <- function(...f, ..., .lazy = TRUE) {
  if (.lazy) {
    env <- child_env(environment(...f))
    env_bind_exprs(.env = env, ...)    
  } else {
    env <- child_env(.parent = environment(...f), ...)
  }

  f <- as_closure(...f)
  fmls <- formals(f)
  fmls <- fmls[!names(fmls) %in% names(env)]
  
  new_function(fmls, body(f), env)
}
```
The idea here is to excise the arguments that are set via `...` from the formals of `...f`, and bind them to an ad hoc environment immediately “above” the environment of `...f`, possibly in a lazy manner.

Returning to the `ls()` example, we get, as before,
```R
ls_all <- partial(ls, all.names = TRUE)

ls_all()
#> [1] ".Random.seed" "ls_all"       "partial"
```
but now the formals are also preserved:
```R
args(ls_all)
#> function (name, pos = -1L, envir = as.environment(pos), pattern, 
#>     sorted = TRUE) 
#> NULL
```
I cannot easily think of a typical situation where this variation of `partial()` would break.

**Comment by egnha** [comment]
Generally, the second implementation of `partial()` will break if the body of `...f` invokes a function that only works against function arguments, e.g., `missing()`.

**Comment by egnha** [comment]
In the first implementation, it would be more efficient for the switch on `.first` to apply to the function `...subst_defvals()`, itself:
```R
partial <- function(...f, ..., .first = TRUE) {
  defvals <- dots_list(...)
  if (is_empty(defvals))
    return(...f)
  
  f <- as_closure(...f)
  if (.first)
    ...subst_defvals <- function(call)
      as.call(c(f, defvals, node_cdr(call)))
  else
    ...subst_defvals <- function(call)
      as.call(c(f, node_cdr(call), defvals))
  
  set_attrs(
    function(...) {
      call <- ...subst_defvals(sys.call())
      eval_bare(call, parent.frame())
    },
    class = "partial_function"
  )
}
```
(Moreover, interpret `...f` as a closure, cf. #360).

**Comment by egnha** [comment]
The approach I've suggested is flawed:

- it's incompatible with byte-code-compiled functions (the offending line is `eval_bare(call, parent.frame())`)
- either the environment of the original function or the original function itself must be in scope when the partialised function is called; but then it is impossible for the final function call to be evaluated in the environment in which the partialized function is called

The upshot is that there is an impasse: either `partial()` maintains compatibility with byte-code compiled functions (as the current `purrr::partial()` does), or it address the problem of this issue. But not both.

It would be undesirable to forgo the former (an infrequent occurrence, anyway) to satisfy the latter, so I am closing this issue.

**Comment by egnha** [comment]
Actually, the method proposed in this issue will work. :-) Thanks to @lionel- for pointing out my mistake!

Indeed, inlining the original function when evaluating in the calling environment will in fact invoke a byte-complied function, even though `str()` seems to imply the contrary:
```R
foo <- function() {
  f <- compiler::cmpfun(function() NULL)
  function(...) {
    # Inline f (as was being done)
    call <- sys.call()
    call[[1]] <- f
    call
  }
}

str(foo()())
#> language (function ()  NULL)()

foo()()[[1]]
#> function() NULL
#> <bytecode: 0x1022597f8>
#> <environment: 0x1029c3eb0>
```

**Comment by lionel-** [comment]
Thanks for exploring this. This feature would be at odds with supporting quosures, which I think is needed once you support quasiquotation. Also it seems more important to support functions using `missing()` than context sensitive functions.
