### ISSUE TITLE
Should purrr re-export zeallot::%<-% ?

### ISSUE THREAD

**Issue by hadley** [tidyverse/purrr#357]
Because a destructuring bind is very useful `safely()` and friends:

```R
c(res, err) %<-% safe_log(10)
```

**Comment by nteetor** [comment]
I think vctrs has the right approach and zeallot is at most suggested not re-exported. Perhaps create a new, short vignette demonstrating purrr and zeallot together?

**Comment by hadley** [comment]
Yeah, I think in the interests of keeping purrr simple we'll leave this for now.
