### ISSUE TITLE
Naming and interfaces of map and pmap are confusing

### ISSUE THREAD

**Issue by michaelbarton** [tidyverse/purrr#364]
Apologies for a subjective issue title, but I've been struggling with how to
switch from using `map` to `pmap`. I've tried reading the documentation several
times, and tried refactoring my code on different occaisons to use `pmap` but I
haven't been able to get `pmap` to work similarly to how I've been using `map`.

Specifically in clojure `pmap` has an identical interface to `map` except that
[it runs in parallel][clj]. I was expecting the similar thing for purrr where I could
switch my `map` function for `pmap` and it would do the same thing but run in
parallel. Here is some example code:

[clj]: https://clojuredocs.org/clojure.core/pmap

```
fit_models <- function(y_variable) {
    model_table %>%
        purrr::map(~ magrittr::inset2(., "model", fit_model(y_variable, .))) %>%
        purrr::map(~ splice(., as.list(broom::glance(.$model))))
}
```

I'm using `fit_models` to fit multiple models at once, and store them as a
field in a list. I tried using pmap but realised that this needed a list of
lists, rather than the list input to `map`. This left me confused, do I have to
my convert my existing list to a list of lists, only then to access the first
item of each list and run the same function? Something like the following:

```
fit_models <- function(y_variable) {
    model_table %>%
        purrr::map(.f = list)
        purrr::pmap(~ magrittr::inset2(.[[1]], "model", fit_model(y_variable, .[[1]]))) %>%
        purrr::map(~ splice(., as.list(broom::glance(.$model))))
}
```

I tried this approach but I ended up getting bogged down in trying to debug
where exactly `pmap` is trying to access each list entry, and also debugging
list/vector operator invalid errors.

So far I've given up trying to use `pmap` in my code, because of this
confusion. I'm writing this issue because I find purrr a very useful library
and have been using it regularly, however if I find `map`/`pmap` confusing then
perhaps others might have a similar stuggle. A suggestion might be to rename
`pmap` to something else, and provide an implementation of `pmap` that is
exactly the parallel implementation of `map`. Alternatively adding
documentation for converting between `map` and `pmap` could also be helpful.

Thank you.

**Comment by lionel-** [comment]
hmm yes we need to expand the documentation for `pmap()`. It has nothing to do with computation parallelism. It takes a rectangular list of lists and apply each "row" to a function. Each "column" is mapped to an argument. So the following:

```r
purrr::pmap(mtcars, function(...) mean(c(...)))
```

is equivalent to `rowMeans(mtcars)` or `apply(mtcars, 1, mean)`.
