### ISSUE TITLE
[INQUIRY] Optimization in map/map2 

### ISSUE THREAD

**Issue by ckatsulis** [tidyverse/purrr#373]
## Problem
I'm trying to query data from an influxdb with `influxdbr`.  I have fairly large data pulls (5-20GB) to preform which I'm looking to speed up vs my current implementation.  The actually receipt of the data happens quite quickly, however after profiling the function, I have pinpointed most of the burden to `purrr::map2`.

![image](https://user-images.githubusercontent.com/7516330/29498177-5acb702a-85bc-11e7-80f6-4dfb3dc73440.png)

## Request
*  Are there any `Rcpp` optimizations that could be tucked into this package that would make the processing of strings more robust/optimal?
*  Has anyone else had performance issues with this package and would benefit?

**Comment by lionel-** [comment]
It looks like `map2()` is not involved, it's the function being mapped. It's spending most of its time capturing dots and we need to rewrite dots manipulation in C to avoid that overhead (that's an rlang issue).

Could you provide a small reprex that reproduce the performance behaviour you see there?

**Comment by ckatsulis** [comment]
Thanks for your response.  The package owner @dleutnant made some very impact changes to his implementation that fixed everything right up.  I will close the issue unless you see fit to leave it open.
