### ISSUE TITLE
flatten_dfr drops all elements except the first

### ISSUE THREAD

**Issue by expersso** [tidyverse/purrr#374]
Consider this:

```
> nrow(iris)
[1] 150
> nrow(flatten_dfr(list(iris, iris, iris)))
[1] 150
> nrow(bind_rows(iris, iris, iris))
[1] 450
```

I would expect `flatten_dfr` to simply concatenate the data frame like `bind_rows`, but it appears to just drop all elements except the first.

**Comment by batpigandme** [comment]
Assume it's the same reason the flatten test is failing. (So, test works, that's good news!)
```r
  > test_check("purrr")
  [31m──[39m [31m1. Failure: can flatten to a data frame with named lists [39m
  `flatten_dfc(list(1))` did not throw an error.
  
  ══ testthat results  ═══════════════════════════════════════
  OK: 433 SKIPPED: 0 FAILED: 1
  1. Failure: can flatten to a data frame with named lists (@test-flatten.R#78) 
```

**Comment by lionel-** [comment]
Using `rlang::flatten()` instead of `purrr::flatten()` would fix this because it only flattens inner lists. For instance, the following all return the same results:

```r
list(mtcars, mtcars))
rlang::flatten(list(mtcars, mtcars)))           # No inner list
rlang::flatten(list(mtcars, list(mtcars))))     # Flattened inner list
```

We're still not sure what the proper flattening semantics are...

**Comment by hadley** [comment]
This seems to be the same problem as #757 — in this case `flatten_dfr()` appears to be column-binding, not row-binding.
