### ISSUE TITLE
get_attr() was renamed attr_getter() but is still referenced in a number of places

### ISSUE THREAD

**Issue by elinw** [tidyverse/purrr#378]
During the 2.2.9 process get_attr() became attr_getter() but it still seems like there are a number of places in documentation that refer to it by the original name.
https://github.com/tidyverse/purrr/search?utf8=%E2%9C%93&q=get_attr&type=

**Comment by hadley** [comment]
Any interest in doing a PR? That would be a very useful contribution!

**Comment by elinw** [comment]
Sure I'd be happy to.
