### ISSUE TITLE
transpose does not work

### ISSUE THREAD

**Issue by stla** [tidyverse/purrr#379]
Hello, 
This is an example given in `?transpose`:
```
> x <- list(list(a = 1, b = 2), list(a = 3, b = 4), list(a = 5, b = 6))
> x %>% transpose()
Error in .Call(transpose_impl, .l, .names) : 
  Incorrect number of arguments (2), expecting 1 for 'transpose_impl'
> 
> packageVersion("purrr")
[1] ‘0.2.3’
```

**Comment by lionel-** [comment]
Are you using Windows? If so can you please reinstall purrr on a fresh session? There are issues on Windows when you're updating packages that are already loaded.

**Comment by stla** [comment]
Yes I'm using Windows. You're right, this works after reinstalling. Probably I installed purrr when it was loaded in another opened RStudio session. Thank you.
