### ISSUE TITLE
`at_depth` still useful

### ISSUE THREAD

**Issue by the-knife** [tidyverse/purrr#381]
Hello,

Because input and output of _modify_depth_ have now to be the same, some powerful feature was lost.

Let's say we want unique values of data-frame columns stored in a list. With the newest purrr release, we have to repeat _map_ n times, whereas in previous releases, _at_depth(n, ...)_ did the job .

With _modify_depth_, the result is no more what we expect. Here is an example with only one data.frame in the list :

```R
library(dplyr)

dfs <- list(
  df1 = data.frame(x = c(1, 2), y = c(1, 1))
)

## Expected ##
dfs %>% map(~ .x %>% map(unique)) # <=> at_depth(2, unique) in previous release
#> $df1
#> $df1$x
#> [1] 1 2
#> 
#> $df1$y
#> [1] 1

## Not expected ##
dfs %>% modify_depth(2, unique)
#> $df1
#>   x y
#> 1 1 1
#> 2 2 1
```

I understand the purpose of _modify_depth_, but maybe it should not replace _at_depth_?
(they could coexist?)

**Comment by lmwang9527** [comment]
I have another use case for `at_depth` that is not fulfilled by `modify_depth`: https://github.com/tidyverse/purrr/issues/363

**Comment by lionel-** [comment]
We could restore it as `map_depth()`?

**Comment by the-knife** [comment]
Would be great !
