### ISSUE TITLE
pluck<-

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/purrr#382]
Now that we are spoiled with `pluck`

``` r
obj1 <- list("a", list(1, elt = "foobar"))
pluck( obj1, 2, "elt")
#> [1] "foobar"
```

can we have a setter version, i.e.

```r
pluck(obj1, 2, "elt" ) <- emo::ji("tada") 
```

**Comment by lionel-** [comment]
Relevant: https://clojuredocs.org/clojure.core/update-in

**Comment by hadley** [comment]
Probably also want prefix version - maybe `stick()`?

**Comment by romainfrancois** [comment]
That makes sense, at the time I don't think I had looked at what `pluck` means in English. 

There are probably issues with things like `attr_getter` if we want consistent syntax between `pluck` and `stick`. This would look odd: ?

```
x <- list( structure("obj", obj_attr = "foo") )

pluck( x, 1, attr_getter("obj_attr") ) <- "bar"
stick(x, "bar", 1, attr_getter("obj_attr") )
```

**Comment by vspinu** [comment]
Would it be possible to allow any extractor `foo` there and pigiback on already existing `foo<-`?
