### ISSUE TITLE
map inside mutate stopped working

### ISSUE THREAD

**Issue by VectorPosse** [tidyverse/purrr#385]
This code (for simulating sample regressions) used to work:

```
library(tidyverse)
library(broom)
set.seed(373)
x <- rnorm(50, mean = 5, sd =  1)
sims_lm <- map(1:1000, ~ 3 + 0.3 * x + rnorm(50, mean = 0, sd = 0.5)) %>%
    enframe() %>%
    mutate(model = map(value, ~ tidy(lm(.x ~ x))),
           slope = map_dbl(model, ~ .$estimate[2]),
           intercept = map_dbl(model, ~ .$estimate[1]))
```

The error is
```
Error in mutate_impl(.data, dots) : 
  Evaluation error: object '.x' not found.
```

Why would map not recognize its own .x argument?

**Comment by cderv** [comment]
Hi, 
Just for helping as I do not know if it is a bug or not. I think it has to do with how `lm` formula is working. `lm(.x ~x)` uses the formula argument which looks for `.x` and `x` first in the optional `data` argument, then in the environnement of the call (and parent env I think). `x` is found in .GlobalEnv but `.x` is not found in any of the environnement. If a `data` argument is provided using `.x`, it is working. A possible solution while waiting for more answer.

``` r
library(tidyverse)
#> Loading tidyverse: ggplot2
#> Loading tidyverse: tibble
#> Loading tidyverse: tidyr
#> Loading tidyverse: readr
#> Loading tidyverse: purrr
#> Loading tidyverse: dplyr
#> Conflicts with tidy packages ----------------------------------------------
#> filter(): dplyr, stats
#> lag():    dplyr, stats
library(broom)
set.seed(373)
x <- rnorm(50, mean = 5, sd =  1)
sims_lm <- map(1:1000, ~ 3 + 0.3 * x + rnorm(50, mean = 0, sd = 0.5)) %>%
  enframe() %>%
  mutate(model = map(value, ~ tidy(lm(y ~ x, data = list(y = .x)))),
         slope = map_dbl(model, ~ .$estimate[2]),
         intercept = map_dbl(model, ~ .$estimate[1]))
sims_lm
#> # A tibble: 1,000 x 5
#>     name      value                model     slope intercept
#>    <int>     <list>               <list>     <dbl>     <dbl>
#>  1     1 <dbl [50]> <data.frame [2 x 5]> 0.3873807  2.447217
#>  2     2 <dbl [50]> <data.frame [2 x 5]> 0.3533183  2.881996
#>  3     3 <dbl [50]> <data.frame [2 x 5]> 0.2569140  3.142239
#>  4     4 <dbl [50]> <data.frame [2 x 5]> 0.4295727  2.370021
#>  5     5 <dbl [50]> <data.frame [2 x 5]> 0.3721455  2.642544
#>  6     6 <dbl [50]> <data.frame [2 x 5]> 0.3386692  2.819105
#>  7     7 <dbl [50]> <data.frame [2 x 5]> 0.2529940  3.134394
#>  8     8 <dbl [50]> <data.frame [2 x 5]> 0.3141017  2.905524
#>  9     9 <dbl [50]> <data.frame [2 x 5]> 0.2774913  3.157526
#> 10    10 <dbl [50]> <data.frame [2 x 5]> 0.3399563  2.845459
#> # ... with 990 more rows
```

I thought it may help to know if this behaviour is intended or not.

**Comment by VectorPosse** [comment]
Thanks for the sample code. That absolutely fixes my problem!

The only reason I suspect it's a bug that has nothing to do with lm is that the code worked until recently. So updates to `map` (or possibly to `mutate`, I'm not sure) seem like the more likely culprit.

**Comment by hadley** [comment]
The semantics of `lm()` are complex, and generally I would recommend avoiding using variables from the environment, rather than variables stored in a data frame.

**Comment by lionel-** [comment]
It's because the nested formula is not evaluated as the outer formula that you use for creating a purrr lambda quotes it. Since it's not evaluated it does not carry an environment:

```
library("rlang")

f <- ~~foo
get_env(f)
#> <environment: R_GlobalEnv>

# Nested formula does carry an environment:
get_env(f_rhs(f))
#> Error: Can't extract an environment from formula
```

The problem is that `lm()` ignores the caller environment and relies on the formula env, even if it's not there. This should be considered as a bug in `lm()`:

```
f <- quote(.x ~ cyl)

local({
  .x <- mtcars$disp
  lm(f, mtcars)
})
#> Error in eval(predvars, data, env) : object '.x' not found
```
