### ISSUE TITLE
rerun is unexpectedly slow

### ISSUE THREAD

**Issue by cwickham** [tidyverse/purrr#388]
Compared to the equivalent `replicate()` call, `rerun()` seems exceptionally slow.

``` r
library(microbenchmark)

n_sim <- 1000

microbenchmark(
  replicate(n_sim, rnorm(10)),
  purrr::rerun(n_sim, rnorm(10)),
  times = 20
)
#> Unit: milliseconds
#>                            expr        min        lq       mean    median
#>     replicate(n_sim, rnorm(10))   2.072379   2.26638   3.160941   2.81277
#>  purrr::rerun(n_sim, rnorm(10)) 499.693895 519.79976 543.337626 529.41209
#>          uq        max neval
#>    3.462063   6.895747    20
#>  573.383384 608.891142    20
```

**Comment by lionel-** [comment]
That's because we haven't optimised tidy evaluation yet.

**Comment by cwickham** [comment]
Got it.  And I'm hoping "yet" means its happening at some point... :)

**Comment by lionel-** [comment]
It's planned for the next version which should be out within a couple of months. It'll still be slower than `substitute()` + `eval()` but should be much faster once we've moved all the R code to C.
