### ISSUE TITLE
Use of .id in map functions

### ISSUE THREAD

**Issue by ruaridhw** [tidyverse/purrr#393]
I'm struggling to understand how to use the `.id` variable in `pmap()` as I can't find any examples of its use.

The doc states

> If not NULL a variable with this name will be created giving either the name or the index of the data frame.

So from this I gathered you can access the object name via whatever `.id` is set to...?

Here's a reprex where I'm trying to access the object name of the first list element:
``` r
library(purrr)

dfs <- list(mtcars = mtcars,
            iris = iris)

desc <- list(mtcars = "Dataset one",
             iris = "Dataset two")

inner_func <- function(df, desc, dfname){
  sprintf("%1$s: This dataset is %1$s with description %2$s. Its columns are %3$s",
          dfname,
          desc,
          paste(names(df), collapse = ", ")
          )
}
pmap(list(dfs, desc), inner_func, .id = "dfname")
#> Error in .f(.l[[c(1L, i)]], .l[[c(2L, i)]], ...): unused argument (.id = "dfname")
```

Also, similarly to `lapply` you can't access the names using `deparse(substitute(df))`
``` r
inner_func <- function(df, desc, dfname = deparse(substitute(df))) ...

pmap(list(dfs, desc), inner_func)
#> $mtcars
#> [1] ".l[[c(1L, i)]]: This dataset is .l[[c(1L, i)]] with description Dataset one. Its columns are mpg, cyl, disp, hp, drat, wt, qsec, vs, am, gear, carb"
#> 
#> $iris
#> [1] ".l[[c(1L, i)]]: This dataset is .l[[c(1L, i)]] with description Dataset two. Its columns are Sepal.Length, Sepal.Width, Petal.Length, Petal.Width, Species"
```

Is this what `.id` is intended for or is it better just to pass the object names as another list argument?
```r
pmap(list(dfs, desc, names(dfs)), inner_func)
```

**Comment by lionel-** [comment]
This is probably for `pmap_df()`. This is passed to `dplyr::bind_rows()`. It looks like this needs to be clearer in the documentation.

**Comment by ruaridhw** [comment]
Great, thanks. I'll go with the last example
