### ISSUE TITLE
isS4() fails in map()

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/purrr#411]
This is not a bug of purrr, but I'm reporting this in case you don't know this peculiar behaviour.

`isS4()` fails as shown bellow. The reason seems that the prototype of `isS4()` shows the argument is `object` while the actual argument is `x`. I don't know there are more horrible primitive functions other than this...

``` r
reprex::reprex_info()
#> Created by the reprex package v0.1.1.9000 on 2017-11-14

# error
purrr::map_lgl(iris, isS4)
#> Error in isS4(object = object): supplied argument name 'object' does not match 'x'

# prototype says the argument is "object", but...
isS4
#> function (object)  .Primitive("isS4")

# error
purrr::map_lgl(iris, ~ isS4(object = .))
#> Error in isS4(object = .): supplied argument name 'object' does not match 'x'

# ok
purrr::map_lgl(iris, ~ isS4(x = .))
#> Sepal.Length  Sepal.Width Petal.Length  Petal.Width      Species 
#>        FALSE        FALSE        FALSE        FALSE        FALSE
```

**Comment by lionel-** [comment]
Hmm, I'd have thought the mapper implementation would rely on positional matching but it seems to create a named call.

**Comment by yutannihilation** [comment]
Maybe `as_closure()` does harm? Should I move the issue to rlang repo?

```r
rlang::as_closure(isS4)
#> function (object) 
#> isS4(object = object)
#> <environment: base>
```

**Comment by lionel-** [comment]
Yes you're right, thanks! You can keep this issue open I'll close it from the rlang commit.

**Comment by yutannihilation** [comment]
Sure 👍

**Comment by yutannihilation** [comment]
> I don't know there are more horrible primitive functions other than this...

Ah, sorry. I was wrong on this part, mismatches between the prototype and the actual argument are usual headache with primitive functions. I've forgotten for a moment...
