### ISSUE TITLE
case_when semantics 

### ISSUE THREAD

**Issue by t-kalinowski** [tidyverse/purrr#413]
Hello,

`case_when` is great. As I've been using it more and more, I have two minor requests for changes that I think would make it easier to use.

can `case_when` get fall-through for missing supplied values similar to `base::switch`?

example usage: 
``` r
x <- letters[1:5]
case_when(
   x == "a" ~ "case a", 
   x == "b" ~ , 
   x == "c" ~ "case b or c", 
            ~ "all other cases")
```
would give
``` r
[1] "case a"          "case b or c"     "case b or c"     "all other cases" "all other cases"
```
Essentially what I'm proposing is that `case_when` supplies a `TRUE` if the last argument has a missing left hand side, and for earlier arguments missing a right hand side, the logical vector(s) on the left hand side keep getting `reduce`'d with `|` until an argument with a supplied right-hand-side is encountered.

**Comment by jennybc** [comment]
@t-kalinowski Can you close and re-open on dplyr? That's where `case_when()` lives.

**Comment by t-kalinowski** [comment]
oh, woops! Sorry, got confused there. Thanks!
