### ISSUE TITLE
map_chr returns date when converting bad POSIXct to date?

### ISSUE THREAD

**Issue by pgensler** [tidyverse/purrr#415]
I'm not really sure if this a bug, but is purrr intended to work like this, or should you be using dplyr?

```

> #' Goal: POSIX column should have date time stored in it
> #' We want to convert bad POSIXct column to date for further use
> library(magrittr)
> library(tibble)
> library(purrr)
> df <-tibble::tibble(
+   order_date = as.POSIXct("25072013", format = "%d%m%Y"),
+   row_id = c(1)
+ )
> str(df)
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	1 obs. of  2 variables:
 $ order_date: POSIXct, format: "2013-07-25"
 $ row_id    : num 1
> 
> #Option 1- using purrr
> clean <- map_chr(df$order_date, is.POSIXct, as.Date)
Error in .f(.x[[i]], ...) : unused argument (function (x, ...) 
UseMethod("as.Date"))
> str(clean)
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	1 obs. of  2 variables:
 $ order_date: Date, format: "2013-07-25"
 $ row_id    : num 1

> #Option 2--using dplyr
> clean <- mutate_if(df, is.POSIXct, as.Date)
> str(clean)
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	1 obs. of  2 variables:
 $ order_date: Date, format: "2013-07-25"
 $ row_id    : num 1
> #########

> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS: /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.19.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] lubridate_1.7.1   repurrrsive_0.1.0 glue_1.2.0        purrrlyr_0.0.2    bindrcpp_0.2     
 [6] selectr_0.3-1     XML_3.98-1.9      RCurl_1.95-4.8    bitops_1.0-6      magrittr_1.5     
[11] rvest_0.3.2       xml2_1.1.1        forcats_0.2.0     stringr_1.2.0     dplyr_0.7.4      
[16] purrr_0.2.4       readr_1.1.1       tidyr_0.7.2       tibble_1.3.4      ggplot2_2.2.1    
[21] tidyverse_1.2.0   pacman_0.4.6     

loaded via a namespace (and not attached):
 [1] reshape2_1.4.2   haven_1.1.0      lattice_0.20-35  colorspace_1.3-2 yaml_2.1.14     
 [6] rlang_0.1.4      foreign_0.8-69   modelr_0.1.1     readxl_1.0.0     bindr_0.1       
[11] plyr_1.8.4       munsell_0.4.3    gtable_0.2.0     cellranger_1.1.0 psych_1.7.8     
[16] parallel_3.4.2   broom_0.4.2      Rcpp_0.12.13     scales_0.5.0     jsonlite_1.5    
[21] mnormt_1.5-5     hms_0.3          stringi_1.1.5    grid_3.4.2       cli_1.0.0       
[26] tools_3.4.2      lazyeval_0.2.1   crayon_1.3.4     pkgconfig_2.0.1  assertthat_0.2.0
[31] httr_1.3.1       rstudioapi_0.7   R6_2.2.2         nlme_3.1-131     compiler_3.4.2 
```

**Comment by pgensler** [comment]
Expanding on this....
```
> # this works for each element, but I get a one length vector?
> df <- df %>%
+   mutate(new_col = map_chr(df$order_date, ~is.POSIXct(.x), as.Date))
> str(df)
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	1 obs. of  3 variables:
 $ order_date: POSIXct, format: "2013-07-25"
 $ row_id    : num 1
 $ new_col   : chr "TRUE"
> #does not work
> df <- df %>%
+   mutate(new_col = map_chr(df$order_date, ~is.POSIXct, as.Date))
Error in mutate_impl(.data, dots) : 
  Evaluation error: Can't coerce element 1 from a closure to a character.
> str(df)
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	1 obs. of  3 variables:
 $ order_date: POSIXct, format: "2013-07-25"
 $ row_id    : num 1
 $ new_col   : chr "TRUE"
```

So for each element I get a one length vector in the first approach, but when I don't specify the .x I get an error? Like I get it that a date is not a chr, but still....

**Comment by cderv** [comment]
Hi, 
first all your examples are not crystal clear to me but from what I have understood I think I could give you some hints. Tell me if I misunderstood.

First, you want date vector at the end. You can't use `map_chr` for that. It will always try to return a character vector or will fail trying. Secondly, `map` functions and friends take a list as input and a function to apply on each element. `map_chr(df$order_date, ~is.POSIXct, as.Date)` is not correct (too many arguments) and it won't return a date vector.

It seems you want to apply a function only on some columns of a dataframe. `dplyr::mutate_if` is a good solution. With `purrr`, you could use `map_if` which take a list, a predicate and a function, or `modify_if` to get back an object same class as input. Here is an example of  use for those: 
``` r
reprex::reprex_info()
#> Created by the reprex package v0.1.1.9000 on 2017-11-18

# Goal: POSIX column should have date time stored in it
# We want to convert bad POSIXct column to date for further use
library(magrittr)
library(tibble)
library(purrr)
#> 
#> Attachement du package : 'purrr'
#> The following object is masked from 'package:magrittr':
#> 
#>     set_names
df <-tibble::tibble(
  order_date = as.POSIXct("25072013", format = "%d%m%Y"),
  row_id = c(1)
)
glimpse(df)
#> Observations: 1
#> Variables: 2
#> $ order_date <dttm> 2013-07-25
#> $ row_id     <dbl> 1

# using dplyr is correct for this use
df %>% dplyr::mutate_if(lubridate::is.POSIXct, as.Date) %>% glimpse
#> Observations: 1
#> Variables: 2
#> $ order_date <date> 2013-07-24
#> $ row_id     <dbl> 1
# with purrr: return a list
df %>% map_if(lubridate::is.POSIXct, as.Date) %>% glimpse
#> List of 2
#>  $ order_date: Date[1:1], format: "2013-07-24"
#>  $ row_id    : num 1
# with purrr: return an object same as input: a dataframe object
df %>% modify_if(lubridate::is.POSIXct, as.Date) %>% glimpse
#> Observations: 1
#> Variables: 2
#> $ order_date <date> 2013-07-24
#> $ row_id     <dbl> 1
```

As you linked in your post, `purrr` does not play well with date. Others solutions in tidyverse could help but right now, you have to do with existing solution. For your use case, it seems to work well with `mutate_if`. 

Hopes it helps.

**Comment by pgensler** [comment]
@cderv thanks for the comments, maybe my examples are simply edge cases of the package.

map functions take a list or a vector as input, and then iterate on that with a given set of instructions. You can store a date as a character vector, but I would expect that using map_chr would be the nicest way of doing this, as if you wanted to do more preprocessing before actually converting to a date in R.

Maybe this is me, but if mutate_if takes a predicate, and so does map_chr....then shouldn't this work?

```
df <-tibble::tibble(
   order_date = as.POSIXct("25072013" ,"25072013", format = "%d%m%Y"),
   row_id = c(1,2)
  )

clean <- map_chr(df$order_date, ~is.POSIXct[[.x]], .p = as.Date)
```

**Comment by david-jankoski** [comment]
i don't think the examples are edge cases, i think maybe you are misinterpreting the help page for `map_chr` - it says  
`map_chr(.x, .f, ...)`  
where `.x` is your list/vector, `.f` the function you want to apply to each element and the dots are for any additional args you want to pass to `.f`. Notice there is no `.p` here.  
As @cderv pointed out in his examples - the `*_if` versions of `map`, `mutate` and `modify` have a `.p` argument where you can pass in a predicate function which if evaluates to true, `.f` will be applied to that element.  
`map_if(.x, .p, .f, ...)`.  
So i think you are just using the wrong function - if you want to do something conditionally then you should be using the `_if` ' versions.

**Comment by pgensler** [comment]
@david-jankoski  thanks for pointing this out. I think the documentation could be improved, as the arguments section below lists all the arguments below implying you could pass a .p in the arguments section to other map* variants, when there's only one predicate function: ```map_if```

Maybe separating map_if and map_at would help for readability?
