### ISSUE TITLE
Basic Vignette of how to use purrr?

### ISSUE THREAD

**Issue by pgensler** [tidyverse/purrr#416]
It would be nice to have a basic vignette which could outline, at a very rudimentary level, the preferred way of using purrr, and highlighting when you should use dplyr vs purrr

-dplyr's mutate is made for applying basic functions:

```
df <-tibble::tibble(
  order_date = as.POSIXct("25072013", format = "%d%m%Y"),
  row_id = c(1)
)
clean <- mutate_if(df, is.POSIXct, as.Date)
str(clean)
```

purrr approach -with dplyr mutate:
```
get_brewer_stats1 <- function(x){
  read_html(x) %>%
  html_nodes(xpath = '//*[@id="container"]/div[2]/div[2]/div[2]') %>%
  html_text()
}

sample_data_rev2 <- sample_data %>%
  mutate(., brewer_stats = map_chr(link, possibly(get_brewer_stats1,otherwise="NULL")))
```

and purrr, is rather made for applying custom functions like this:
https://stackoverflow.com/questions/43218761/by-row-vs-rowwise-iteration/43236272#43236272

**Comment by hadley** [comment]
Yes, this is something we are thinking about. Because it's a bigger project, it's not particularly useful to track in an issue, but we are aware of it and we're thinking about it.
