### ISSUE TITLE
Consider automatically adding names when map_ing on a character vector

### ISSUE THREAD

**Issue by vspinu** [tidyverse/purrr#419]
I think mapping over character strings should add names automatically. Patterns like `names(dts) %>% set_names` are needless pollutants. 

I have been using `set_names` since it has been introduced but never got used to this pattern. In my mind some higher cleanness standards are just not warranted in this case.  Character strings stand for themselves and `c(name="name")` in the name of consistency is an atrocity. Hopefully you can relate my micro-pain :)

**Comment by hadley** [comment]
I really dislike this behaviour in base R — as often it's useful, I find that it needlessly adds names where I don't want them.
