### ISSUE TITLE
rolling map functions (similar to tibbletime's rollify)

### ISSUE THREAD

**Issue by adder** [tidyverse/purrr#420]
Hey

I sometimes need rolling window functions. 
This can be eg. a rolling mean but also a function of some arbitrary complexity.

I often use the `rollify` function from the `tibbletime` package.
You can use this function almost like the `map` function from `purrr` but then with an additional window parameter.
See the examples in the help file for some  use cases.
https://business-science.github.io/tibbletime/reference/rollify.html

I was wondering if something like this would not be a good fit to include in `purrr` to extend the `map` family (eg. `rollify`, `rollify_int`,`rollify_dfr`,`rollify2_int` , `prollify_int`, ...)?

I'm happy to use `tibbletime`'s `rollify`, but I think the idea is universal enough to have a more general implementation in `purrr`.

Greets

**Comment by hadley** [comment]
This feels like out of scope for purrr to me.

**Comment by ben18785** [comment]
Again, sorry if this is flogging a dead horse, but is there currently anything in tidyverse which implements a moving map like Mathematica's MovingMap: http://reference.wolfram.com/language/ref/MovingMap.html 

I find it really useful when I want to iterate over lists with a moving window.
