### ISSUE TITLE
When using ..1, ..2 and so on in anonymous functions in pmap(), conflicts with ... in replicate() and maybe others

### ISSUE THREAD

**Issue by eaurele** [tidyverse/purrr#421]
```r
pmap(list(1, 2), ~ replicate(n = ..1, expr = ..2))
# Error in FUN(X[[i]], ...) : the ... list does not contain 2 elements
```

Though:

```r
pmap(list(1, 2), ~ replicate(n = ..1, expr = .y))
# [[1]]
# [1] 2
```

works.

I suspect the problem arises because of:

```r
print(replicate)
# function (n, expr, simplify = "array") 
#   sapply(integer(n), eval.parent(substitute(function(...) expr)), 
#          simplify = simplify)
```

It seems the `function(...) expr` in `substitute()` does not play well with `..2`, being interpreted as the second element of `...` which is empty.

**Comment by markdly** [comment]
I'm just adding a reprex here for the original problem along with some other possible solutions

``` r
library(purrr)

# doesn't work
pmap(list(1, 2), ~ replicate(n = ..1, expr = ..2))
#> Error in FUN(X[[i]], ...): the ... list does not contain 2 elements

# this works
pmap(list(1, 2), function(x, y) { replicate(n = x, expr = y) })
#> [[1]]
#> [1] 2

# and so does this
pmap(list(1, 2), replicate)
#> [[1]]
#> [1] 2
```

**Comment by hadley** [comment]
This is quite rare, and I don't see an easy fix, so I think we'll just have to leave the current behaviour. Technically the problem is with `replicate()`s suboptimal evaluation strategy.

**Comment by hadley** [comment]
You can also use `rerun()` instead of `replicate()`
