### ISSUE TITLE
only_one

### ISSUE THREAD

**Issue by hadley** [tidyverse/purrr#432]
Not sure if this is exactly the right name, but purrr seems like a reasonable home. This is particularly useful for scraping.

```R
only_one <- function(x) {
  if (length(x) != 1)
    stop("Not length 1")

  x[[1]]
}
```

**Comment by lionel-** [comment]
maybe `rlang::unbox()` should check the length rather than check for `rlang_box` class?

**Comment by hadley** [comment]
I'm not sure if `unbox()` is the right axis to generalise along - it may be what we want is a more general set of extraction operators where you can simultaneously assert what you expect the structure to be. And maybe if you don't supply an assertion, you'd get a message giving you the length + type + class?

```R
strict_extract <- function(x, i = 1, n) {
  if (length(x) < i) stop("`x` doesn't ave position i")

  out <- x[[i]]
  if (missing(n)) {
    message("Length ", out)
  } else {
    stopifnot(length(out) == n)
  }
}
```

cc @jennybc because this is often useful when scraping + rectangling - you want to explicitly know if the input data structure no longer meets your expectations

**Comment by hadley** [comment]
Duplicate of #436
