### ISSUE TITLE
pmap: count not find function "pmap"

### ISSUE THREAD

**Issue by murDataD** [tidyverse/purrr#434]
> library(purrr)
> pmap(list(n = list(5,10,20),mean = list(1,5,10),sd = list(.1,.5,.1)), rnorm)
Error: could not find function "pmap"

Please advise. R Studio couldn't find pmap function but other purrr functions work properly. Could this be a bug in my R Studio?

Mark

**Comment by lionel-** [comment]
Could you post your session info please? Either `sessionInfo()` or `devtools::session_info()` if you have devtools installed.

**Comment by murDataD** [comment]
Thank you for the quick reply. It was my R version; just needed to update again! Bug fixed.

Happy New Year!
