### ISSUE TITLE
Typed pluck

### ISSUE THREAD

**Issue by hadley** [tidyverse/purrr#436]
e.g. `pluck_int()` etc - for when you want to make an assertion about what you're plucking out.

**Comment by hadley** [comment]
Include `n` argument?

**Comment by hadley** [comment]
See also #432 

```
strict_extract <- function(x, i = 1, n) {
  if (length(x) < i) stop("`x` doesn't have position i")

  out <- x[[i]]
  if (missing(n)) {
    message("Length ", out)
  } else {
    stopifnot(length(out) == n)
  }
}
```

**Comment by hadley** [comment]
And the default would be zero-length vectors

**Comment by hadley** [comment]
Or maybe?

```
tpluck <- function(x, ..., .default = NULL, .type = NULL, .n = NULL) {
  out <- pluck(x, ..., .default = .default)
  
  if (!is.null(.type) && !identical(typeof(out), .type)) {
    glubort("Plucked value must be of type {.type}, not {typeof(out)}")
  }
  if (!is.null(.n) && !identical(length(out), .n)) {
    glubort("Plucked value must be length {.n}, not {length(out)}")
  }
  
  out
}
```

**Comment by hadley** [comment]
Now I imagine this would wrap `vec_assert()`, matching whatever arguments it has.

**Comment by lionel-** [comment]
Because `pluck()` also supports functions, the following would work as well for coercing pluck:

```r
pluck(x, 1, "name", int)
pluck(x, 1, "name", dbl)
```

**Comment by jennybc** [comment]
I'm encountering many places where I could use this in googlesheets4. On a first pass, I rectangled some data with a column-wise approach, using `map_chr(x, "name")` and similar. Now I'm refactoring with a row-wise approach and, to retain all the type-safety I had previously, I'd really like to use `pluck_chr(x, "name")`.

**Comment by jennybc** [comment]
I guess I can just keep using `map_*()`, but it feels weird.

**Comment by hadley** [comment]
No longer seems important given the tooling that we have in tidyr.
