### ISSUE TITLE
Consider using dots_list() in invoke()

### ISSUE THREAD

**Issue by hadley** [tidyverse/purrr#437]
i.e.

```
invoke <- function(.f, ...) {
  do.call(.f, dots_list(...))
}
```

This would be an API breaking change, so we'd need to carefully consider the impact, probably by running revdeps before and after the change.

If we do this, we should check that all purrr functions that use `...` in this way are also ported to use `dots_list()`

**Comment by hadley** [comment]
And rename to `execute()`

**Comment by hadley** [comment]
Consider alternative implementation, and check that the problems in http://rpubs.com/hadley/do-call2 don't reoccur.

**Comment by lionel-** [comment]
These are probably all caused by unnecessarily deep copies of call in R. I'll try to fix them all for R 3.6.

The only way to avoid this for existing versions of R is to use a masking strategy as in `rlang::invoke()`. The masking strategy has a bit of overhead but produces cleaner stacktraces / captured calls.

**Comment by hadley** [comment]
`execute()`, now `exec()` will live in rlang. purrrr needs to re-export it, while soft deprecating `invoke()`.

**Comment by flying-sheep** [comment]
So we should use `do.call` again in a purrr pipeline? `stuff %>% exec(fun, !!!.)` doesn’t work.

**Comment by lionel-** [comment]
Good point. There's no way to fix this except with workarounds like

```r
1:3 %>% { exec(list, !!!.) }
```

**Comment by flying-sheep** [comment]
…which is ugly as sin, and far too complicated to recommend to anyone. People need to grok at least 3 concepts for this.

Maybe we should introduce something like `call_with(args, func)` or undeprecate `invoke`

**Comment by lionel-** [comment]
It's also ok to use `do.call()`.

**Comment by lionel-** [comment]
Though it doesn't protect symbolic elements (nor did `invoke()`).

**Comment by flying-sheep** [comment]
[I’d rather not](https://rpubs.com/hadley/do-call2)

**Comment by lionel-** [comment]
I have fixed all these performance issues in R core.

**Comment by flying-sheep** [comment]
ha, nice! well done. so it’s `do.call` for pipelines and `exec` else… hmm, somehow i’m still not too happy with this.

**Comment by lionel-** [comment]
I recognise the magrittr situation is not ideal, but replacing invoke and variants by exec decreases the surface of the API and increases its consistency (using `!!!` for splicing). Also it is easy to define `invoke()` yourself in your scripts / packages, it's a few lines wrapper around `do.call()`. Let's see what @hadley thinks.

**Comment by hadley** [comment]
One approach would be to teach magrittr about unquoting so it could treat it as passing `.` to the second argument, but that's going to require considerable orchestration across packages. I think it would be best to start a fresh issue with a reprex and a moderately realistic example of why this is important.

**Comment by flying-sheep** [comment]
An issue where? here or for magrittr?

**Comment by hadley** [comment]
Here to start.
