### ISSUE TITLE
Unexpected behavior applying `list_modify` to a list of data.frames

### ISSUE THREAD

**Issue by jburos** [tidyverse/purrr#438]
This is probably not a typical use case, but I'm running into problems working with lists of data.frames using `purrr`.  Happy to elaborate on _why_ I'm using a list of dataframes if you're curious, but the TL;DR is that my data are comprised of paired survival, longitudinal, & other outcomes which don't fit well into a single DF. Thus each analysis operates on a list of DFs.

At any rate, here is a minimal example that reproduces the error:

```r
library(purrr)
library(dplyr)
data(mtcars)
data(iris)
datalist <- list(mtcars = mtcars, iris = iris)
# modify some of the data.frames in datalist
modified_data <- list()
modified_data$mtcars <- dplyr::sample_n(datalist$mtcars, size = 5, replace = F)
# (do some sanity checks & reporting on modifications made)
# return an updated datalist
new_datalist <- purrr::list_modify(datalist, !!!modified_data)
```

At this point, I see an error:
```
Error in `[[<-.data.frame`(`*tmp*`, nm, value = c(27.3, 30.4, 13.3, 14.7,  : 
  replacement has 5 rows, data has 32
```

It seems that, because the data.frames are also lists, `list_modify` is attempting to modify _each column_ (element of the list) rather than the data.frame as a whole.

This may be the desired behavior for more common use cases -- the example above works as expected if the number of rows remains the same (say, if you were to use `mutate` rather than `sample_n`) -- but was nonetheless unexpected in this case.

**Comment by hadley** [comment]
I don't think I would use `list_modify()` with data frames for exactly this reason - data frames are lists, so by definition, `list_modify()` will recurse down into each individual column.
