### ISSUE TITLE
Understand performance variations 

### ISSUE THREAD

**Issue by hadley** [tidyverse/purrr#439]
https://gist.github.com/wch/3352f6fa0a843b4aa2f5839bb635a193

Why is @wch’s approach so much faster?

**Comment by wch** [comment]
When I use profvis on @hadley's tidy version of the code, it appears that most of the time is spent in `pluck`.

I published the profiles here:
* My version: http://rpubs.com/wch/346793
* Hadley's version: http://rpubs.com/wch/346794

**Comment by lionel-** [comment]
That is possibly due to `dots_splice()` which should be considerably faster with the dev version of rlang. Does the perf gap persists with dev rlang?

**Comment by wch** [comment]
It is indeed a lot faster with the dev version of rlang, almost as fast as my original version of the code.  Profile here:

* http://rpubs.com/wch/346804
