### ISSUE TITLE
Take dots with dots_list() in pluck()

### ISSUE THREAD

**Issue by lionel-** [tidyverse/purrr#440]
Rather than with `dots_splice()` as we are leaning towards explicit splicing semantics.

**Comment by hadley** [comment]
This is the only current use of `dots_splice()` in purrr.

**Comment by hadley** [comment]
Hmmmm, we have made extensive use of this behaviour in our tests, which makes me worry that this might cause a lot of API breakage for relatively little gain (since `list()` doesn't have any other meaning for `pluck()`) .

**Comment by lionel-** [comment]
There's probably very few people that depend on this behaviour, though the only way to know for sure is revdeps. Do we want to soft-deprecate `rlang::dots_splice()` in the future? It'd be better to switch as soon as possible if it's meant to be retired.

**Comment by hadley** [comment]
Just a note that @jennybc and I got confused by this behaviour in a recent slack thread

**Comment by lionel-** [comment]
There's no failure in the revdeps, so we can go ahead with this one.
