### ISSUE TITLE
functional updating of nested lists

### ISSUE THREAD

**Issue by vspinu** [tidyverse/purrr#444]
I am looking for `update_in` and `assoc_in` which would do something like this 

```R
l <- ll(a = ll(b = 1))
update_in(l, c("a", "b"), `+`, 1)
##=> ll(a = ll(b = 2))

assoc_in(l, c("a", "c"), 3)
##=> ll(a = ll(b = 1, c = 3))
```
Has this already been brewed somewhere? 

Thanks!

**Comment by vspinu** [comment]
Given he current api these two should probably be done with the reverse of `pluck` - `stick` or something.

**Comment by cderv** [comment]
some thoughts: 
Currently, I would do those like that:
``` r
library(rlang)
library(purrr)
#> 
#> Attachement du package : 'purrr'
#> The following objects are masked from 'package:rlang':
#> 
#>     %@%, %||%, as_function, flatten, flatten_chr, flatten_dbl,
#>     flatten_int, flatten_lgl, invoke, list_along, modify, prepend,
#>     rep_along, splice
l <- ll(a = ll(b = 1))

# update_in
modify_depth(l, 2, `+`, 1)
#> $a
#> $a$b
#> [1] 2
modify_depth(l, 1, ~ map_at(.x, "b", `+`, 1))
#> $a
#> $a$b
#> [1] 2
map_at(l, "a", ~ map_at(.x, "b", `+`, 1))
#> $a
#> $a$b
#> [1] 2
modify_at(l, "a", ~ map_at(.x, "b", `+`, 1))
#> $a
#> $a$b
#> [1] 2

# assoc_in
modify_depth(l, 1, append, list(c=3))
#> $a
#> $a$b
#> [1] 1
#> 
#> $a$c
#> [1] 3
map_at(l, "a", append, list(c=3))
#> $a
#> $a$b
#> [1] 1
#> 
#> $a$c
#> [1] 3
```
Created on 2018-01-21 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by lionel-** [comment]
See also https://github.com/tidyverse/purrr/issues/382

**Comment by hadley** [comment]
I'm going to close this in favour of #382

**Comment by vspinu** [comment]
#382 covers part of this issue (corresponding to [`assoc_in`](https://clojuredocs.org/clojure.core/assoc-in)). [`update_in`](https://clojuredocs.org/clojure.core/update-in) is what makes the stuff interesting.
