### ISSUE TITLE
`list_modify` requirement of both named or unnamed lists is too restrictive

### ISSUE THREAD

**Issue by vspinu** [tidyverse/purrr#445]
I think this is an unnecessary restriction when all dots are either named or unnamed. Both of the following are well defined: 

```R
> list_modify(ll(1), a = 2)
Error: `x` and `y` must be either both named or both unnamed

> list_modify(ll(a = 1, b = 2), 2, 3)
Error: `x` and `y` must be either both named or both unnamed
```

When working with calls and argument lists the first use case is pretty common. There might be unnamed arguments but modification arguments are always named.

 utils::modifyList does the first one right:

```R
> modifyList(ll(1), ll(a = 2))
[[1]]
[1] 1

$a
[1] 2
```

**Comment by hadley** [comment]
Hmmmm weakening this restriction feels like it makes the semantics murkier to me. Are you expecting the second case to return `list(2, 3)` or `list(a = 2, b = 3)`?

**Comment by hadley** [comment]
See also #443

**Comment by vspinu** [comment]
> Are you expecting the second case to return list(2, 3) or list(a = 2, b = 3)?

Second.  Positional arguments should never interfere or overwrite the names. Just like `l[[1]] = 2` is equivalent to `l[["a"]] = 2` but doesn't overwrite the name. 

But, frankly I don't care much about my second second case. The first case is the important one and I am currently sticking with `modifyList` instead of `list_modify` just for its sake.
