### ISSUE TITLE
Please add generic `assoc` and `update`

### ISSUE THREAD

**Issue by vspinu** [tidyverse/purrr#448]
No functional language is "complete" without these two functions. Would be great if these were generic and work on all R collections (lists, envs, pairlists etc).

```R
ll <- list()
assoc(ll, a=1)
#> list(a=1)

update(ll, "a", `+`, 1)
#> list(a=2)
```
`assoc` would supersede `list_modify` which is too long  for such a handy function. 

Related discussion on nested updates #444.

**Comment by vspinu** [comment]
`update` is a S3 generic in stats with no methods for list and other atomic types. Hight time to snatch it for rlang style updates.

**Comment by lionel-** [comment]
> update is a S3 generic in stats with no methods for list and other atomic types. Hight time to snatch it for rlang style updates.

We can't do this because it's not good practice to add methods when you don't own either the generic or the class. This leads to clashes.

**Comment by vspinu** [comment]
I am afraid this is an impractical attitude. Global semantics is in the interest of everyone here; you cannot be inventing new names till the end of times.  If purrr is aiming to be _the_ package for list manipulation then it should grab update.list. What other package would need update.list in the first place?

**Comment by lionel-** [comment]
This is the only practical attitude with S3 method registration. It's starting to be enforced by CRAN btw. If you want to create a list method for `update()` you have to do it on your own `update()` generic. But then you're going to be masking a `stats` function and get the wrath of many people.

Personally I think R should move towards lexically scoped method dispatch, but that requires quosures to be practical in functionals (otherwise you dispatch within the functional exec env and everything goes south).

**Comment by vspinu** [comment]
Really? Do they go so far? I thought it's only for cases when you actually overwrite some of the base methods.   

> Personally I think R should move towards lexically scoped method dispatch,

I no longer know the inner workings of S3 dispatch but isn't a form of this already in place? If package A imports an S3 method from package B and package C overwrites the same method then package A still sees the method from B, or not?

**Comment by lionel-** [comment]
> Do they go so far? I thought it's only for cases when you actually overwrite some of the base methods.

Not yet. There is no notion of class ownership but the base types do belong to R core. It would make sense for R CMD check to disallow packages registering base types methods if they don't own the generic.

>  isn't a form of this already in place?

Registration applies to a generic namespace. Lexically scoped methods sort of work but are discouraged by R CMD check and riddled with bugs once you start to pass a generic to `lapply()` and other functionals.

**Comment by vspinu** [comment]
>  R CMD check and riddled with bugs once you start 

It's rather frustrating that instead of fixing the dispatch and registration they keep enforcing extra conventions on the developers :(

**Comment by hadley** [comment]
Can you please link to a good definition for each of these functions?

**Comment by vspinu** [comment]
Clojure [`update`](https://clojuredocs.org/clojure.core/update) and [`assoc`](https://clojuredocs.org/clojure.core/assoc). 

These are single level versions of the nested variants [`assoc-in`](https://clojuredocs.org/clojure.core/assoc-in) and  [`update-in`](https://clojuredocs.org/clojure.core/update-in).

 `assoc` allows for multiple key-value pairs and is thus similar to `list_modify`. Assoc-in is similar to `stick` discussed in #444 and #382. No versions of `update` or `update-in` currently exists.
