### ISSUE TITLE
functional map_when to apply with conditional

### ISSUE THREAD

**Issue by Diego-MX** [tidyverse/purrr#450]
I want to return a list of expressions as with `map`, that are constructed based on different conditions as in `case_when` or `ifelse`.  

The source of this example is a table created outside a technical environment with a structure such as this:  
``` r
toy_table <- data_frame(
  key   = letters[1:3] %>% rep(each = 3), 
  attr1 = replace(runif(9), mod(1:9, 3) != 1, NA), 
  attr2 = replace(runif(9), mod(1:9, 3) != 2, NA), 
  attr3 = replace(runif(9), mod(1:9, 3) != 0, NA), 
  attr4 = replace(runif(9), mod(1:9, 3) != 2, NA))

#> # A tibble: 9 x 5
#>   key    attr1   attr2   attr3  attr4
#>   <chr>  <dbl>   <dbl>   <dbl>  <dbl>
#> 1 a      0.245 NA      NA      NA    
#> 2 a     NA      0.635  NA       0.124
#> 3 a     NA     NA       0.0169 NA    
#> 4 b      0.521 NA      NA      NA    
#> 5 b     NA      0.0913 NA       0.246
#> 6 b     NA     NA       0.150  NA    
#> 7 c      0.497 NA      NA      NA    
#> 8 c     NA      0.488  NA       0.855
#> 9 c     NA     NA       0.592  NA    
``` 
This one is homogeneous, but my example isn't.  

I recover a list of column relations based on the non NA entries.  Keep the second one for the example. 
``` r
relations <- list(
    c("key", "attr1"), 
    c("key", "attr2", "attr4"), 
    c("key", "attr3"))

a_rel <- relations[[2]]
#> [1] "key"   "attr2" "attr4"
```

And I want to filter my original `toy_table` based on such last relation.  That would be,
``` r
a_table <- toy_table %>%
  filter(!is.na(key), is.na(attr1), !is.na(attr2), is.na(attr3), !is.na(attr4) )
#> # A tibble: 3 x 5
#>   key   attr1  attr2 attr3 attr4
#>   <chr> <dbl>  <dbl> <dbl> <dbl>
#> 1 a        NA 0.635     NA 0.124
#> 2 b        NA 0.0913    NA 0.246
#> 3 c        NA 0.488     NA 0.855
```

or equivalently,
``` r
a_cond <- names(toy_table) %>% map( ~ if (.x %in% a_rel) {
  quo( !is.na( !!sym(.x) ) ) } else {
  quo(  is.na( !!sym(.x) ) )
} )

a_table <- filter(toy_table, !!!a_cond)
```
Note that in the previous edit I was using `lazyeval::interp` but now I changed to using `quo` with `!!sym("col")` instead of `as.name("col")`.  I understand this is the new right way to go... 

After several attempts, I was able to functionalize the condition with an `if (...)` to go inside `map`.  But still was looking for something more in the spirit of tidyness.  I'll lleave the question as I had formulated, even though it has a solution already.  

``` r
a_cond <- names(toy_table) %>% map_when(
    . %in% a_rel ~ quo( !is.na( !!sym(.x) )), 
  !(. %in% a_rel) ~ quo( is.na( !!sym(.x) ) ) )
```

Is this usable, or might it be just too abstract?  
Cheers,

**Comment by hadley** [comment]
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by Diego-MX** [comment]
Thanks for checking this issue out.  There's good news and bad news. 

The bad news is that I couldn't get `reprex` running on my computer -which would make another issue- but for the moment leaves output hardcoded by hand.  

The good news is that I got to work more on the issue, and worked it out with better use of quasiquotation and conditioning with standard `if-else`.

**Comment by hadley** [comment]
This feels a little too specific for purrr to me.
