### ISSUE TITLE
Suboptimal error message from map_*() variants

### ISSUE THREAD

**Issue by jennybc** [tidyverse/purrr#452]
``` r
x <- list(
  list(a = 1L),
  list(a = 2:3)
)
purrr::map_int(x, "a")
#> Error: Result 2 is not a length 1 atomic vector
```

Created on 2018-02-01 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

It would be helpful to more about the problematic entry. Is it `NULL`, length 0 or length > 1?

**Comment by hadley** [comment]
Per error style guide, this should be something like: "Result 2 must be a single integer, not an integer vector of length 3"
