### ISSUE TITLE
how to understand the mean function is for columns but not rows

### ISSUE THREAD

**Issue by 2236529177** [tidyverse/purrr#453]
> mtcars[1:5,]
                   mpg cyl disp  hp drat    wt  qsec vs am gear carb
Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2

> library(purrr)
> mtcars[1:5,] %>% keep(function(x) mean(x) > 10)
                   mpg disp  hp  qsec
Mazda RX4         21.0  160 110 16.46
Mazda RX4 Wag     21.0  160 110 17.02
Datsun 710        22.8  108  93 18.61
Hornet 4 Drive    21.4  258 110 19.44
Hornet Sportabout 18.7  360 175 17.02

I can not figure out that the function mean do for the column, thanks a lot

**Comment by hadley** [comment]
Thanks for the nice explanation @cderv !
