### ISSUE TITLE
Would an ireduce() function be welcome?

### ISSUE THREAD

**Issue by ijlyttle** [tidyverse/purrr#456]
With `ireduce_right()` for completeness?

Happy to make a PR if you like.

**Comment by hadley** [comment]
I don't understand what it would do?

**Comment by ijlyttle** [comment]
I found a use for it here: https://github.com/ijlyttle/bsplus/issues/48 

I have a bootstrap accordion to which panels get appended. The empty accordion would be the `.init`, I have a function `bs_append()` that takes an existing accordion and appends a new panel with a title. The panel-contents are in a named-list, with the panel-titles being the names.

The accordion is assembled using `reduce2()`, but I could see the parallels with `imap()`, for example.

I'm sure this is an edge case if it has not come up yet, but I figure I'd at least bring it to your attention.

**Comment by hadley** [comment]
This feels a little too specific for purrr to me.
