### ISSUE TITLE
purrr functionals and factories do not support lexical dispatch

### ISSUE THREAD

**Issue by lurodrigo** [tidyverse/purrr#459]
`map()` doesn't seem to work properly when `.f` is a generic. Example:

```
> x = structure(list(), class = "some_class")
> as.character.some_class = function(x) "some_class object"
> lapply(list(x, x), as.character)
[[1]]
[1] "some_class object"

[[2]]
[1] "some_class object"

> map(list(x, x), as.character)
[[1]]
character(0)

[[2]]
character(0)
```

**Comment by Eluvias** [comment]
```r
purrr::map(list(x, x), ~as.character(.x))
[[1]]
[1] "some_class object"

[[2]]
[1] "some_class object"

```

**Comment by lionel-** [comment]
This is a general issue in purrr. We should probably capture functions in quosures. Need to investigate performance implications.

**Comment by lionel-** [comment]
Also

```
pluck(iris, 5, levels)
#> Error in UseMethod("levels") : 
#>   no applicable method for 'levels' applied to an object of class "factor"
```

**Comment by lionel-** [comment]
Most problematic with base methods since they are not registered.

**Comment by lionel-** [comment]
The simplest solution is to evaluate everything in the purrr namespace. This makes it easier to test for S3 dispatch in unit tests, guarantees unregistered methods from the base namespace are found, and allows users to define methods in the global environment

**Comment by lionel-** [comment]
Or the global env and then unit tests can use `scoped_bindings(global_env(), ...)`.

**Comment by elinw** [comment]
I know this is closed but with the release of 0.3.0 there was a breaking change causing  purrr::map() to say that no method for mean exists for class numeric.  Replacing `mean` with `mean.default` makes the error go away.

**Comment by ColinFay** [comment]
@elinw is this related to the bug in skimr? 
https://twitter.com/_colinfay/status/1098577101404422144?s=21

**Comment by elinw** [comment]
Yes it is the cause of that issue.

**Comment by lionel-** [comment]
Can you open a new issue with a reprex please?

**Comment by ColinFay** [comment]
@lionel- related to #647 :)

**Comment by tzakharko** [comment]
I've just run into this issue with non-exported S3 methods defined in a local environments (these methods are defined for non-exposed internal types, which is why there is not much sense in exporting them)

```r
local({
  x <- structure(list(), class = "some_class")
  as.character.some_class <- function(x) "some_class object"

  print(as.character(x))

  print(map(list(x, x), as.character))
})
```

I suppose this could be fixed by always invoking the mapper in the caller environment, but I assume that this would bring additional problems (otherwise you would have probably already done it).  An easy workaround is wrapping the call in an additional closure (e.g. `~ as.character(.)`) which sets the correct scope. 

This use case is probably too marginal  to justify changes to `purrr` internals, but I wanted to report it in case someone runs into the same issue.

**Comment by lionel-** [comment]
> these methods are defined for non-exposed internal types, which is why there is not much sense in exporting them

The proper practice is to register methods even for non-exported generics. It makes sense to register them because lexical dispatch has serious limitations, for instance with functionals. Global dispatch is the way to go.
