### ISSUE TITLE
map2() - Specify predict type

### ISSUE THREAD

**Issue by tatewr** [tidyverse/purrr#464]
Good day.  I've been scouring the web for the last few days looking at the documentation for map2.  I have taken a training set, nested the data and created **coxph** models for it, saving those models in the nested table.  Now I want to **predict** from that model, but I want to use a **type="expected"**.  I'm not seeing how to get that to work.  I'm still pretty new to R; learned a lot from the RStudio conference and tidyverse workshop, so really looking to continue my learning in tidy-land. Thanks in advance for the help! -Wendy

Using the example from the documentation, how would I add the type="expected" to this function?
# Split into pieces, fit model to each piece, then predict
by_cyl <- mtcars %>% split(.$cyl)
mods <- by_cyl %>% map(~ lm(mpg ~ wt, data = .))
map2(mods, by_cyl, predict)

WHAT I'VE TRIED SO FAR:

I've tried making a formula for the predict function (which works on my single group, non-nested set
`predict.F <- function(model1, data1){
  predict(model1, newdata=data1, type="expected")
}`
but get the following error: "Error in mutate_impl(.data, dots) : Evaluation error: requires numeric/complex matrix/vector arguments"

When I try and put the formula directly in the map2 argument:
`df <- df %>%
 mutate(prediction = map2(model1, data1, predict(model1, newdata=data1, type="expected") `
I get the following error: Evaluation error: no applicable method for 'predict' applied to an object of class "list"

I also tried an anonymous function:
`df <- df %>%
 mutate(prediction = map2(model1, data, ~ predict(.x, newdata=.y, type="expected") `
but get the following error: "Error in mutate_impl(.data, dots) : Evaluation error: requires numeric/complex matrix/vector arguments"

Finally, I tried putting the function directly into map2:
`df <- df %>%
 mutate(prediction = map2(model1, data, function(model, data) predict(model, newdata=data, type="expected") `
but get the following error: "Error in mutate_impl(.data, dots) : Evaluation error: requires numeric/complex matrix/vector arguments"

**Comment by hadley** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)

**Comment by tatewr** [comment]
Thanks, will do! I appreciate the direction to the right community
-W
