### ISSUE TITLE
Transpose drops factors

### ISSUE THREAD

**Issue by dmi3kno** [tidyverse/purrr#471]
It seems like `purrr::transpose()` coerces factors to numeric, seemingly, unprovoked:
``` r
library(tidyverse)

iris_list <- iris %>% select(Sepal.Length, Sepal.Width, Species) %>% slice(c(50:51, 100:101)) %>% 
  as.list()
iris_list
#> $Sepal.Length
#> [1] 5.0 7.0 5.7 6.3
#> 
#> $Sepal.Width
#> [1] 3.3 3.2 2.8 3.3
#> 
#> $Species
#> [1] setosa     versicolor versicolor virginica 
#> Levels: setosa versicolor virginica
```
Then after applying `transpose()` the last element of the list is suddenly numeric:
``` r
iris_list %>% transpose() %>% .[1]
#> [[1]]
#> [[1]]$Sepal.Length
#> [1] 5
#> 
#> [[1]]$Sepal.Width
#> [1] 3.3
#> 
#> [[1]]$Species
#> [1] 1
```
Expected behavior:
``` r
#> [[1]]
#> [[1]]$Sepal.Length
#> [1] 5
#> 
#> [[1]]$Sepal.Width
#> [1] 3.3
#> 
#> [[1]]$Species
#> [1] setosa
#> Levels: setosa versicolor virginica
```

**Comment by hadley** [comment]
Transpose currently only works with atomic vectors.

**Comment by jennybc** [comment]
This just came up in this blog post by @coolbutuseless:

https://coolbutuseless.github.io/2019/03/17/group_map-in-dplyr-0.8.1-still-in-development/

when [I asked](https://twitter.com/JennyBryan/status/1107304077291970560) why, in the post's original form, a factor was reverting to the underlying integer. In that case `pmap(x, list)` was a drop-in substitute for `transpose()` that preserved the factor-ness. Also seems like one of the new tidyr verbs might have helped to get the key vars (just one here) into the right form for the `map2()` simulation of `group_map()`.

**Comment by hadley** [comment]
Closing in order to collect all transpose issues in one place, #875.
