### ISSUE TITLE
keep/drop argument in map_if

### ISSUE THREAD

**Issue by Eluvias** [tidyverse/purrr#473]
Should the `map_if()` gain a `drop` or `keep` argument? 

The idea is to offer the option to keep **only** the elements where `.p` evaluates to `TRUE`  within `map_if()` instead of using `keep()` and `map()`.

A quick wrapper:

```r
map_if2 <- function(.x, .p, .f, drop = FALSE, ...) {

  if (drop) {

    .x2 <- keep(.x, .p)
    out <-  map(.x2, .f, ...)

  } else {

    out <- map_if(.x, .p, .f, ...)
  }

  out
}
```

**Comment by hadley** [comment]
This doesn't seem to be a big win to me - the point of `map_if()` is to only modify certain elements, and supporting `drop = TRUE` would blur its purpose.
