### ISSUE TITLE
unexpected behavior: map_chr converts factors as integer vectors

### ISSUE THREAD

**Issue by czeildi** [tidyverse/purrr#477]
possibly related issue: #471 

``` r
library(purrr)

f <- factor(LETTERS[1:3])
f
#> [1] A B C
#> Levels: A B C

map_chr(f, identity)
#> [1] "1" "2" "3"

as.character(f)
#> [1] "A" "B" "C"
```

I would expect `map_chr` to return the levels as character vector not the integers behind the factor

```r
map_chr(f, ~ .)
#> [1] "A" "B" "C"
```

**Comment by hadley** [comment]
This is as expected because the `map()` functions working with the underlying atomic vectors. I think automatically coercing factors to characters would make purrr less internally consistent.
