### ISSUE TITLE
Strict pluck

### ISSUE THREAD

**Issue by hadley** [tidyverse/purrr#482]
In base R, `[[` sometimes returns an error and sometimes returns `NULL`:

| `row[[col]]` | Zero-length | OOB (int)  | OOB (chr) | Missing  |
|--------------|-------------|------------|-----------|----------|
| `NULL`       | `NULL`      | `NULL`     | `NULL`    | `NULL`   |
| Atomic       | Error       | Error      | Error     | Error    |
| List         | Error       | Error      | `NULL`    | `NULL`   |

`pluck()` eliminates this inconsistently by (effectively) always return `NULL`. We need a strict equivalent that eliminates the inconsistency in the opposite direction: by always throwing an error.

**Comment by hadley** [comment]
We could call it `chuck()` or `suck()`

**Comment by daniel-barnett** [comment]
Were you thinking something like the following (but without the `strict` parameter)? If so, I can clean it up and make a PR. 

```r
test.list <- list(a = 1:5, b = letters[1:5], c = list(abc = 123))
test.atom <- 1:10

> # strict_pluck()
> pluck(NULL, integer(0), strict = TRUE)
Error: `.x` must not be NULL.
> pluck(NULL, 100, strict = TRUE)
Error: `.x` must not be NULL.
> pluck(NULL, "adsaf", strict = TRUE)
Error: `.x` must not be NULL.
> pluck(NULL, NA_integer_, strict = TRUE)
Error: `.x` must not be NULL.

> pluck(test.list, integer(0), strict = TRUE)
Error: Can't find index.
> pluck(test.list, 100, strict = TRUE)
Error: Can't find index.
> pluck(test.list, "adsaf", strict = TRUE)
Error: Can't find index.
> pluck(test.list, NA_integer_, strict = TRUE)
Error: Can't find index.

> pluck(test.atom, integer(0), strict = TRUE)
Error: Can't find index.
> pluck(test.atom, 100, strict = TRUE)
Error: Can't find index.
> pluck(test.atom, "adsaf", strict = TRUE)
Error: Can't find index.
> pluck(test.atom, NA_integer_, strict = TRUE)
Error: Can't find index.
```

**Comment by hadley** [comment]
Exactly!

**Comment by hadley** [comment]
A PR would be great 😄

**Comment by daniel-barnett** [comment]
So, I also have this working for environments and S4 objects. For environments, it errors if the object doesn't exist in the environment, and for S4 if the object doesn't have the desired slot. This would the desired behaviour, right?

The other big one is indexing by function, but (correct me if I'm wrong) I don't think we can really make this strict as it relies on whatever that function's behaviour is.

**Comment by hadley** [comment]
That all sounds correct to me
