### ISSUE TITLE
Expose non-FO versions of hopefully/safely

### ISSUE THREAD

**Issue by hadley** [tidyverse/purrr#484]
To use as alternatives to `try()` at the top-level.

**Comment by lionel-** [comment]
Possible naming scheme:

- `safely()` - `with_safety()`
- `quietly()` - `with_quiet()`
- `possibly()` - `with_possibility()`
- `insistently()` - `with_insistence()`
- `slowly()` - `with_slowness()`

**Comment by hadley** [comment]
No longer convinced this is needed.
