### ISSUE TITLE
Documentation: safely Doesn't Always Have One NULL Value

### ISSUE THREAD

**Issue by billdenney** [tidyverse/purrr#488]
The documentation for `safely` inaccurately states that one value in the list is always `NULL` (https://github.com/tidyverse/purrr/blob/84ce1ad00a736a2e6a75acdc9872af74f6866cf0/R/output.R#L13-L14).  With the `otherwise` argument, both values may be non-NULL.

```r
> a <- safely(function(x) stop("foo"), otherwise="bar")
> a("bloo")
$result
[1] "bar"

$error
<simpleError in .f(...): foo>
```

**Comment by hadley** [comment]
I think that is technically correct - one value is always null. It doesn't imply anything about the other value 😉

**Comment by dchiu911** [comment]
I think @billdenney means sometimes neither are null?
``` r
library(purrr)

# error is NULL
safely(log)(10)
#> $result
#> [1] 2.302585
#> 
#> $error
#> NULL

# result is NULL
safely(log)("a")
#> $result
#> NULL
#> 
#> $error
#> <simpleError in log(x = x, base = base): non-numeric argument to mathematical function>

# neither are NULL
safely(log, otherwise = "b")("a")
#> $result
#> [1] "b"
#> 
#> $error
#> <simpleError in log(x = x, base = base): non-numeric argument to mathematical function>
```

Created on 2018-05-31 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
