### ISSUE TITLE
multiplying the beta coefficient by the number of days in R

### ISSUE THREAD

**Issue by jasperDD** [tidyverse/purrr#496]
I conduct  regression analysis for the client plus the code catogories.
Dependent variable is stuff, and independent is action. for each category the client plus the code, i conduct the regressions.
R script for regression by two categories

    df=read.csv()
    
    library(tidyverse)
    library(broom)
    
    my_lm <- function(df) {
      lm(stuff~action, data = df)
    }
    
    new=df %>% 
      group_by(client,code) %>% 
      nest() %>%
      mutate(fit = map(data, my_lm),
             tidy = map(fit, tidy)) %>%
      select(-fit, - data) %>%
      unnest()

;
Variable action mean is there action or not (1-is action, 0 there is no action ).
The question is : How for each regression of each  above mentioned categories, the value of  received beta coefficient  multiply by the number of days when the action was performed.
For example, for the category a (client) + b (code), the action was 8 days (the number of 1(one) for each category is equal  the number of action days)
it is means that beta coefficient, (suppose 0.56) must be  multiplied by 8 (0.56 * 8)
and this principle with the rest of the regressions for the categories (client) + (code).
To make it clearly, here output which i expect

     client	code	term	estimate	multiply
        a	b	(Intercept)	1,371428571	
        a	b	action	    0,433449477	3,44v #0,43*8
        c	d	(Intercept)	26,1	
        c	d	action	    37,47142857	0
        e	f	(Intercept)	168,2190476	
        e	f	action	   266,383362	3724 #266*14

df

    structure(list(client = structure(c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 2L, 2L, 2L, 2L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 
    3L, 3L, 3L), .Label = c("a", "c", "e"), class = "factor"), code = structure(c(1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 2L, 2L, 2L, 3L, 3L, 3L, 3L, 3L, 
    3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L), .Label = c("b", "d", "f"
    ), class = "factor"), stuff = c(3L, 10L, 100L, 77L, 1L, 9L, 124L, 
    112L, 13L, 40L, 252L, 0L, 10L, 106L, 41L, 4L, 18L, 148L, 165L, 
    0L, 189L, 0L, 0L, 5L, 0L, 0L), action = c(1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 0L, 0L, 0L, 0L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L)), .Names = c("client", "code", "stuff", "action"
    ), class = "data.frame", row.names = c(NA, -26L))

**Comment by cderv** [comment]
Hi, 
This is not really an issue with `purrr` but a general question of how it works. You may have better chance to have a fester answer on community.rstudio.com . I advice to post your question their to (referring to this issue)
