### ISSUE TITLE
`.` doesn't work when mapping over list of data.frames

### ISSUE THREAD

**Issue by kendonB** [tidyverse/purrr#497]
The first one using `.` outputs a functional sequence, rather than the pulled vector

```r
list(data.frame(a = 1)) %>% 
  map(~{
    . %>% pull(a)
  })
#> [[1]]
#> Functional sequence with the following components:
#> 
#>  1. pull(., a)
#> 
#> Use 'functions' to extract the individual functions.

list(data.frame(a = 1)) %>% 
  map(~{
    .x %>% pull(a)
  })
#> [[1]]
#> [1] 1
```

**Comment by lionel-** [comment]
This is a fundamental conflict that cannot be fixed. The inner expression (here the magrittr pipe) decides what `.` means. Fortunately neither magrittr nor the lambda syntax are compulsory so you can easily work around it.
