### ISSUE TITLE
reduce2_right

### ISSUE THREAD

**Issue by smj389** [tidyverse/purrr#498]
There is a bug in reduce2_right. 
The order in which the arguments are passed to reduce2_impl is transposed.
`function (.x, .y, .f, ..., .init) 
{
  reduce2_impl(.x, .f, .y, ..., .init = .init, .left = FALSE)
}`
should be
`function (.x, .y, .f, ..., .init) 
{
  reduce2_impl(.x, .y, .f, ..., .init = .init, .left = FALSE)
}`

**Comment by cderv** [comment]
good catch ! Another information to complete : what is odd is that unit test uses this argument inversion
https://github.com/tidyverse/purrr/blob/b3c29c893fe7b88bba35eb0133010c52e9217d94/tests/testthat/test-reduce.R#L52-L57
It is why tests are passing on this one. That is definitly not consistent with the documentation and `reduce2`. 
``` r
library(purrr)
paste2 <- function(x, y, sep = ".") paste(x, y, sep = sep)
letters[1:4] %>% reduce(paste2)
#> [1] "a.b.c.d"
# reduce2 example
letters[1:4] %>% reduce2(c("-", ".", "-"), paste2)
#> [1] "a-b.c-d"
# what would be consitent
letters[1:4] %>% reduce2_right(c("-", ".", "-"), paste2)
#> Error in reduce2_impl(.x, .f, .y, ..., .init = .init, .left = FALSE): `.y` does not have length 3
# need to invert .f and .y
letters[1:4] %>% reduce2_right(paste2, c("-", ".", "-"))
#> [1] "d-c.b-a"
```

Created on 2018-04-25 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
