### ISSUE TITLE
Generalisation of rerun

### ISSUE THREAD

**Issue by hadley** [tidyverse/purrr#504]
Inspired by bench API — should be able to supply multiple values and generate grid

```R
param_grid(
  rows = c(10000, 100000), 
  cols = c(10, 100),
  rep = 1:3,
  {
    dat <- create_df(rows, cols)
    bench::mark(
      min_time = .5,
      min_iterations = 100,
    
      bracket = dat[dat$x > 500, ],
      which = dat[which(dat$x > 500), ],
      subset = subset(dat, x > 500)
    )
  }
)
```

**Comment by t-kalinowski** [comment]
For what it's worth, I think this is a good idea. Locally I've been using a function `mfor` (multi-for) that effectively does this (except that it evaluates everything in the calling environment as it's trying to behave like an actual `for` function):
``` r
mfor <- function(...) {
  dots <- eval(substitute(alist(...)))
  expr <- dots[[length(dots)]]
  dots[[length(dots)]] <- NULL

  for(i in rev(seq_along(dots))) {
    for_var <- as.name(names(dots)[i])
    for_seq <- dots[[i]]
    expr <- call("for", for_var, for_seq, expr)
  }

  eval.parent(expr)
}

mfor(i = 1:2, j = 1:2, k = 1:2, {
  print(glue::glue("i: {i}   j: {j}   k: {k}"))
})
#> i: 1   j: 1   k: 1
#> i: 1   j: 1   k: 2
#> i: 1   j: 2   k: 1
#> i: 1   j: 2   k: 2
#> i: 2   j: 1   k: 1
#> i: 2   j: 1   k: 2
#> i: 2   j: 2   k: 1
#> i: 2   j: 2   k: 2
```

<sup>Created on 2018-10-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Ideally this could work with an intelligent progress bar of some sort. (printing not just a % complete, but also the current values of each of the variables being iterated over)

**Comment by egnha** [comment]
@t-kalinowski, sweet!

A few remarks:

- You could simplify your function by capturing the expression-to-loop as an explicit (mangled) argument. That is, rather than the signature `function(...)`, try `function(..expr, ...)`. Then the dots will automatically capture just the loop variables (except in the improbable case that one of them is literally named `..expr`, whence the mangling). You won't need to separate them manually.

- Rather than using a for-loop and assignments, you can create the nested for-loops via reduction.

A more functional (i.e., declarative) implementation of `mfor()` might look like this:

```R
mfor <- function(..expr, ...) {
  call_fors <- Reduce(call_for, vars(...), substitute(..expr), right = TRUE)
  eval.parent(call_fors)
}

call_for <- function(., expr) {
  call("for", as.name(.$var), .$range, expr)
}

vars <- function(...) {
  dots <- as.list(substitute(...()))
  purrr::transpose(list(var = names(dots), range = dots))
}

mfor(i = 1:2, j = 3:4, cat(sprintf("i: %d, j: %d\n", i, j)))
#> i: 1, j: 3
#> i: 1, j: 4
#> i: 2, j: 3
#> i: 2, j: 4
```

**Comment by egnha** [comment]
@hadley, would it make sense to derive what you want from a general mechanism for comprehensions? (For lists, for-loops, etc.)

**Comment by t-kalinowski** [comment]
Thanks! Is that a hidden undocumented feature of `substitute`, or is it applicable in other places too?

**Comment by lionel-** [comment]
That's an undocumented quirk of `substitute()` that only applies to dots. Plenty of code relies on this so you can consider it more or less official.

**Comment by lionel-** [comment]
@hadley Where will this function live, given that `rerun()` is in the questioning stage for being an NSE function? Perhaps we should create a little package containing `purrr::when()`, `purrr::rerun()`, and this new function? Perhaps `switch2()` would belong in it as well?

**Comment by lionel-** [comment]
Maybe `redpen::call_match()` and `dplyr::case_when()` would also fit in this package. The theme would be control flow and NSE/formulas.

**Comment by hadley** [comment]
Yeah, I think now this is out of scope for purrr.
