### ISSUE TITLE
map_* expects a vector of length 1

### ISSUE THREAD

**Issue by rmflight** [tidyverse/purrr#518]
This isn't really documented in the `map_*` that these functions expect a length 1 vector.

It is disconcerting, b/c the `map_df*` functions don't care how big the resulting objects are, they just get merged together.

Small pull request to update the documentation.

**Comment by rmflight** [comment]
For example, I really expect this to work:

``` r
l1 <- list(list(a = 1L),
           list(a = c(1L, 2L, 3L)))

purrr::map_int(l1, "a")
#> Error: Result 2 is not a length 1 atomic vector

purrr::map_chr(l1, function(x){class(x$a)})
#> [1] "integer" "integer"
```

**Comment by jennybc** [comment]
In terms of getting what you want, `map()` followed by a type-specific `flatten_*()` does it:

``` r
library(purrr)

l1 <- list(list(a = 1L),
           list(a = c(1L, 2L, 3L)))

map(l1, "a") %>% flatten_int()
#> [1] 1 1 2 3
```

**Comment by rmflight** [comment]
Fair enough, but the reason for the issue (and pull request) is that the
documentation doesn't make this clear.

The documentation seems to imply that the initial example should be
possible.

How can we change the documentation so that it is clearer the ??

**Comment by egnha** [comment]
@rmflight I hope I am not adding noise to the discussion, but what about the first line of the description of the map functions?:

> The map functions transform their input by applying a function to each element and returning a vector the same length as the input.

Does this not stipulate that the function to be mapped by `map_*()` must return a scalar?

**Comment by jennybc** [comment]
I proposed some wording in the PR: https://github.com/tidyverse/purrr/pull/517#issuecomment-398907288

**Comment by cderv** [comment]
Not about the wording but for reference about the use case needing _flatten_ after _map_, there is an open PR #502 adding `map_flat_*` functions.

``` r
# devtools::install_github("tidyverse/purrr#502)
library(purrr)
l1 <- list(list(a = 1L),
           list(a = c(1L, 2L, 3L)))

map_flat_int(l1, "a")
#> [1] 1 1 2 3
```

Created on 2018-06-21 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
