### ISSUE TITLE
array_branch() drops the attributes

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/purrr#519]
This is because `apply()`, which is used inside `array_branch()`, drops the attributes. So, to be fair, this is not purrr's fault, and I understand matrix and array are rather the out of scope of purrr for now (according to https://github.com/tidyverse/purrr/issues/341#issuecomment-362950447).

That said, it would be great if `array_branch()` respect the attributes. This won't be so useful until `map_vec()` is implemented, though. Here's a realistic example:

``` r
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.2.3, proj.4 4.9.3
library(purrr)

nc <- st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE)
x <- nc$geometry[1:3]

distances <-   st_distance(x, st_centroid(x))
#> Warning in st_centroid.sfc(x): st_centroid does not give correct centroids
#> for longitude/latitude data

# distances have units
distances
#> Units: m
#>          [,1]     [,2]     [,3]
#> [1,]     0.00 13985.05 49921.06
#> [2,] 17457.73     0.00 23673.16
#> [3,] 47903.44 14524.29     0.00

# the attributes are lost
map(
  array_branch(distances, 1),
  mean
)
#> [[1]]
#> [1] 21302.04
#> 
#> [[2]]
#> [1] 13710.3
#> 
#> [[3]]
#> [1] 20809.25

# split() keeps the attributes
map(
  split(distances, row(distances)),
  mean
)
#> $`1`
#> 21302.04 m
#> 
#> $`2`
#> 13710.3 m
#> 
#> $`3`
#> 20809.25 m
```

Created on 2018-07-01 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by lionel-** [comment]
Unfortunately even with the new vctrs infrastructure, it's unlikely that we'll fix this any time soon given that matrices are not high priority for purrr.
