### ISSUE TITLE
walk2 unclasses dates but other functions don't

### ISSUE THREAD

**Issue by gergness** [tidyverse/purrr#524]
I find this behavior confusing - `walk2` is the only function out of `map`, `map2`, `walk` and `walk2` that loses the class on dates. I believe it is due to the `transpose` in `pwalk` (and so is related to #471), but because map2 doesn't have this behavior I thought there may be another way to solve this.

``` r
library(purrr)
dates <- seq(as.Date('2018-07-01'), as.Date('2018-07-02'), by = "day")

walk2(dates, dates, ~print(.x))
#> [1] 17713
#> [1] 17714

map(dates, ~.)
#> [[1]]
#> [1] "2018-07-01"
#> 
#> [[2]]
#> [1] "2018-07-02"
map2(dates, dates, ~.x)
#> [[1]]
#> [1] "2018-07-01"
#> 
#> [[2]]
#> [1] "2018-07-02"
walk(dates, ~print(.))
#> [1] "2018-07-01"
#> [1] "2018-07-02"
```

Created on 2018-07-10 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by lionel-** [comment]
This was fixed in #554 thanks to @mikmart :)
