### ISSUE TITLE
.at documentation says numeric positions are accepted

### ISSUE THREAD

**Issue by maxheld83** [tidyverse/purrr#529]
from the `.at` documentation:

> A character vector of names, positive numeric vector of positions to include, or a negative numeric vector of positions to exlude. Only those elements corresponding to .at will be modified.

Shouldn't it be positive *integer* vector of positions, etc?

**Comment by lionel-** [comment]
It can also be a double vector of positions (integers coded as double) so numeric seems to be the right term here.
