### ISSUE TITLE
map_df Loses Attributes

### ISSUE THREAD

**Issue by billdenney** [tidyverse/purrr#532]
When running `map_df()` on a data.frame, all attributes of the columns are lost.

``` r
library(purrr)
#> Warning: package 'purrr' was built under R version 3.4.4
foo <- data.frame(A = 1, B = 2)
attr(foo$A, "hi") <- "hello"
bar <- map_df(.x = foo, .f = function(x) x)
attributes(foo$A)
#> $hi
#> [1] "hello"
attributes(bar$A)
#> NULL
```

**Comment by davidski** [comment]
Possible duplicate of #358?

**Comment by hadley** [comment]
Really a duplicate of https://github.com/tidyverse/dplyr/issues/3259 — but in general you shouldn't expect attributes not associated with an S3 class to be preserved by any operation.
