### ISSUE TITLE
map2-pmap: need better explanation of _dfc and _dfr functionality

### ISSUE THREAD

**Issue by bbrewington** [tidyverse/purrr#533]
I'm guessing it's an indicator of operating on rows or columns.

It's in the map2-pmap.R code...maybe put an explanation in the "Values" section?  Also, might be helpful to include an example showing what it does.
https://github.com/tidyverse/purrr/blob/master/R/map2-pmap.R

**Comment by Ryo-N7** [comment]
I'll work on this for tidy-dev-day
@batpigandme please add a tidy-dev-day label.
