### ISSUE TITLE
New comparison vignette

### ISSUE THREAD

**Issue by hadley** [tidyverse/purrr#537]
Something like this:

---

One problem with the apply family is their lack of consistency:

-   The first argument to `lapply()`, `sapply()`, `vapply()` and `tapply()`, 
    is the vector; the first argument to `mapply()` is the function.

-   With `vapply()`, `sapply()`, and `mapply()` you can choose to
    suppress names on the output with `USE.NAMES = FALSE`; but you can't
    with `lapply()` or `tapply()`.

-   There's no consistent way to pass non-vectorised arguments on to the mapper
    function. Most functions use `...` but `mapply()` uses `MoreArgs` (which
    you'd expect to be called `MORE.ARGS` to be consistent with `USE.NAMES`). 
    The closely related  `Map()`, `Filter()` and `Reduce()` expect you to 
    create a new anonymous function.

-   `sapply()` and `mapply()` automatically simplify their output which
    means that different input lengths will return different _types_ of 
    output. `sapply()` has a variant that allows you to specify the desired 
    type called `vapply()`, but `mapply()` does not. Additionally, the 
    simplify argument to `sapply()` is called `simplify`; where for `mapply()`
    it's called `SIMPLIFY`.

Note that I don't mention `apply()` here; it has limited use because it works with matrices, which are rare in data analysis. You should never use `apply()` with a data frame because it turns it into a matrix, which is a slow operation.

**Comment by hadley** [comment]
Show examples of type instability causing problems.

**Comment by hadley** [comment]
Show difference in approach between purrr and base R:

```r
mtcars %>% 
  split(mtcars$cyl) %>% 
  map(~ lm(mpg ~ wt, data = .x)) %>% 
  map(coef) %>% 
  map_dbl(1)

by_cyl <- split(mtcars, mtcars$cyl)
models <- lapply(by_cyl, function(data) lm(mpg ~ wt, data = data))
vapply(models, function(x) coef(x)[[1]], double(1))

sapply(split(mtcars, mtcars$cyl), function(x) coef(lm(mpg ~ wt, x))[[1]])
```

**Comment by ColinFay** [comment]
Hey, 

I've already got something written there I can extend: https://colinfay.me/happy-dev-purrr/ so I'll be glad to take this one

**Comment by hadley** [comment]
That would be great, thanks!
