### ISSUE TITLE
Couldn't we have a `.i` pronoun that would make `i*` functions obsolete ?

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/purrr#546]
I often find myself needing `imap_if`, `imap_at`, `imutate_all`, `isummarize_at ` etc...

Many SO revolve around this issue as well.

I understand the wish not to extend families of functions to infinity, but if we could access a `.i` pronoun that would contain the indice or name, there would be no need for those, and `.i` or `.n` (both could be available) would be more readable than `.y` which sometimes confuses inexperienced users.

**Comment by hadley** [comment]
That feels very unpurrr like to me as no functions currently use NSE. If we did inject a pronoun we'd need to modify the environment of the function being passed in, which is a bit of an odd thing to do.

**Comment by moodymudskipper** [comment]
If `as_mapper`  is modified to add `.i` and `.n` parameters, the relevant dplyr functions could pass indices and names to the transforming functions or predicates if their formals are compatible.

Then no funny business with pronouns and environments.

```
as_mapper(~ .+3)
#> function (..., .x = ..1, .y = ..2, . = ..1, .i, .n)
#> . + 3

as_mapper(~ paste(., .i, .n))
#> function (..., .x = ..1, .y = ..2, . = ..1, .i, .n)
#> paste(., .i, .n)

l1 <- list(a = "foo", b = "bar")

## New feature :
l1 %>% map(~ paste(., .i, .n))
# $a
# [1] "foo 1 a"
#
# $b
# [1] "bar 2 b"

## Just as before :
l1 %>% map(paste,"X")
# $a
# [1] "foo X"
#
# $b
# [1] "bar X"

```

**Comment by hadley** [comment]
That would require different magic to tell if the function had `.i` and `.n` arguments (and then it might match coincidentally). I don't think level of magic is better than explicitly calling `imap()`.
