### ISSUE TITLE
`.at` and `.if` as parameters ?

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/purrr#547]
Somewhat related to https://github.com/tidyverse/purrr/issues/546

Some functions don't have a `*_if` / `*_at` version, like `map_dbl`. We also would sometimes benefit from `mutate_at_if` (and so on), but having every combination would not be realistic.

Why not use `.at` and `.if` parameters ? It seems to me that would make everything much easier. 
`.at` would be `vars(everything())` by default, `.if` would be `~TRUE` by default.

The `...` are never fed to he `.p` as far as I know so there'd be no conflict, arguments would sit after the `...` so would need to be called explicitly, which would take about as much typing as calling the `*_at` / `*_if` functions.

**Comment by hadley** [comment]
This is likely to be resolved in a different direction in the future, once purrr uses vctrs. Then `map_if()` and `map_at()` will gain `.ptype` arguments which will allow you to specify the desired output prototype.
