### ISSUE TITLE
[Pitch] add a combine vector operator 

### ISSUE THREAD

**Issue by tzakharko** [tidyverse/purrr#549]
There are cases in which one would prefer to have a combine operation instead of the combine function, to improve readability and decrease the amount of brackets, e.g. `x %c% y` or `x %,% y` instead of `c(x, y)`. Such an operator also adheres to the "chain, don't nest" idea that is central to tidyverse. Alternative of course is to simply use `x %>% c(y)`, but personally I do prefer a dedicated operator. Implementing such an operator could be as simple as 

    `%,%` <- c

If the maintainers are interested in such a feature, I could prepare a PR that implements this.

**Comment by jennybc** [comment]
Just noting that `base::append()` is, at least, a more nicely named way of doing this in a piped fashion.

``` r
`%>%` <- magrittr::`%>%`
x <- 1:3
y <- 4:5
x %>%
  append(y)
#> [1] 1 2 3 4 5
```

That's neither here nor there in terms of whether an operator is needed. I suspect magrittr is a better target for this feature request, in that it already hosts some alternative operators.

**Comment by tzakharko** [comment]
The reason why I suggested it for purr instead of magrittr is because purr already defines some convenience operators R is lacking (`%||%` and `%@%`) and magrittr's aliases are exactly the opposite (they provide function mnemonics for operators and not operators for existing functions). In addition, magrittr's aliases are not loaded by default by `library(tidyverse)`...

**Comment by hadley** [comment]
I don't like to add infix operators unless they are compellingly useful, which I don't think `%,%`, sorry. It would be better in another package.
