### ISSUE TITLE
Pluck is missing in the pkgdown reference page

### ISSUE THREAD

**Issue by cderv** [tidyverse/purrr#550]
`pluck` help page [exists](https://purrr.tidyverse.org/reference/pluck.html) but is missing from the [reference page](https://purrr.tidyverse.org/reference/index.html) and I don't see the function help page in the [_pkgdown.yml file](https://github.com/tidyverse/purrr/blob/master/_pkgdown.yml)

Is it intentionally left out or just missing?

**Comment by lionel-** [comment]
It was marked as internal when it was introduced but I guess it should be fully part of the API.
