### ISSUE TITLE
reduce() does not work with a list of functions

### ISSUE THREAD

**Issue by drtjc** [tidyverse/purrr#553]
The following code results in an error:
```
Funcall <- function(f, ...) f(...)
reduce_right(list(cos), Funcall, .init = 0)
# Error in f(...) : could not find function "f"
```
I think(?) the above code should lead to:
```
Funcall(cos, 0)
# [1] 1
```
The base R `Reduce()` function works:
```
Reduce(Funcall, list(cos), 0, right = TRUE)
# [1] 1
```

Note: The `Reduce()` example is part of a larger example in the function help
```
Reduce(Funcall, list(log, exp, acos, cos), 0, right = TRUE)
```

**Comment by drtjc** [comment]
I think this has to do with how initial values are treated. For example:
```
Reduce(`%%`, 4, init = 7, right = TRUE)
# [1] 4 
# i.e. 4 %% 7

reduce_right(4, `%%`, .init = 7)
# [1] 3
# i.e. 7 %% 4 

reduce(4, `%%`, .init = 7) # gives 3
Reduce(`%%`, 4, init = 7, right = FALSE) # gives 3
```

Help for `Reduce()` says "*if init is given, `Reduce` logically adds it to the start (when proceeding left to right) or the end of `x`, respectively*". It seems `reduce()` is essentially always adding it to the start of `x`.


Hence the code in the initial comment above, `reduce_right(list(cos), Funcall, .init = 0)`, is producing a call of:
```
Funcall(0, cos)
```

**Comment by drtjc** [comment]
Actually, it's not really to do with initial values. E.g.
```
reduce_right(c(4, 7), `%%`) # = 3
7 %% 4 # =3

Reduce(`%%`, c(4, 7), right = TRUE) # = 4
4 %% 7 # = 4
```
It looks like the difference is because:
```
reduce_right(list(x1, x2, x3), f) = f(f(x3, x2), x1)
Reduce_right(list(x1, x2, x3), f) = f(f(x2, x3), x1)
```

That is, `reduce_right()` reverses the list, whereas `Reduce_right()` works backwards.

**Comment by yutannihilation** [comment]
> `Reduce_right(list(x1, x2, x3), f) = f(f(x2, x3), x1)`

I think this is `f(x1, f(x2, x3))`, which is the same as [Haskell's `foldr`](https://wiki.haskell.org/Fold#Examples). Maybe this example is more obvious?:

``` r
f <- function(x, y) glue::glue("({x} {y})")

Reduce(f, letters[1:5], init = "!")
#> (((((! a) b) c) d) e)
Reduce(f, letters[1:5], init = "!", right = TRUE)
#> (a (b (c (d (e !)))))

purrr::reduce(letters[1:5], f, .init = "!")
#> (((((! a) b) c) d) e)
purrr::reduce_right(letters[1:5], f, .init = "!")
#> (((((! e) d) c) b) a)
```

<sup>Created on 2018-09-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

But, I don't know there's a de facto standard for `reduce`/`fold`, so I have no idea if this is right or wrong...

**Comment by drtjc** [comment]
```
f(x1, f(x2, x3))
```
yes, i got that the wrong way round. Thanks.
Your example makes it clear what is happening. I've no idea either is there is a "correct" one.
