### ISSUE TITLE
Programming using the tidyverse: speed issues

### ISSUE THREAD

**Issue by danilinares** [tidyverse/purrr#555]
I posted this question in StackOverflow that I think it might be of your interest:

https://stackoverflow.com/questions/52591801/programming-using-the-tidyverse-speed-issues?noredirect=1#comment92118537_52591801

We released the package quickpsy a few years ago (paper in the R journal paper). The package used R base functions, but also made an extensive use of functions of what was called at that time the Hadleyverse. We are now developing a new version of the package that mostly uses functions from the tidyverse and that incorporates the new non-standard evaluation approach and found that the package is much much slower (more than four times slower). We found for example that purrr::map is much slower than dplyr::do (which is deprecated):

library(tidyverse)

system.time(
  mtcars %>% 
    group_by(cyl) %>% 
    do(head(., 2))
  )

system.time(
  mtcars %>% 
    group_by(cyl) %>% 
    nest() %>% 
    mutate(temp = map(data, ~head(., 2))) %>% 
    unnest(temp)
)
We also found that functions like pull are very slow.

We are not sure whether the tidyverse is not meant to be used for this type of programming or we are not using it properly.

**Comment by batpigandme** [comment]
Hi,

If you could include the body of your issue here as well, it'll be easier for the maintainers to keep track of.

Thanks

**Comment by lionel-** [comment]
The nest/unnest version allocates twice as much data, which explains why it's consistently twice as slow:

```r
res <- bench::press(n = 1:6, {
  df <- bind_rows(rep(list(mtcars), 10^n))
  bench::mark(
    do = df %>%
      group_by(cyl) %>%
      do(head(., 2)),
    nest = df %>%
      group_by(cyl) %>%
      nest() %>%
      mutate(temp = map(data, ~head(., 2))) %>%
      unnest(temp)
  )
})
#> # A tibble: 12 x 15
#>    expression     n      min     mean   median      max `itr/sec` mem_alloc
#>  * <chr>      <int> <bch:tm> <bch:tm> <bch:tm> <bch:tm>     <dbl> <bch:byt>
#>  1 do             1   3.17ms   3.69ms   3.61ms   4.94ms   271.      67.36KB
#>  2 nest           1   6.57ms   7.16ms   7.12ms   8.48ms   140.     120.72KB
#>  3 do             2   3.36ms   3.67ms   3.62ms    4.5ms   273.     326.11KB
#>  4 nest           2   7.18ms    7.8ms   7.72ms   9.47ms   128.     587.22KB
#>  5 do             3   6.36ms   7.03ms   6.91ms   8.06ms   142.       2.85MB
#>  6 nest           3  13.47ms  14.85ms  14.72ms  17.14ms    67.3      4.96MB
#>  7 do             4   43.2ms  47.91ms  47.63ms   53.6ms    20.9     28.11MB
#>  8 nest           4  89.88ms 103.72ms  90.22ms  157.8ms     9.64    53.57MB
#>  9 do             5 525.66ms 525.66ms 525.66ms 525.66ms     1.90    280.8MB
#> 10 nest           5 828.12ms 828.12ms 828.12ms 828.12ms     1.21    511.1MB
#> 11 do             6     4.4s     4.4s     4.4s     4.4s     0.227    2.74GB
#> 12 nest           6    9.49s    9.49s    9.49s    9.49s     0.105     4.8GB
#> # ... with 7 more variables: n_gc <dbl>, n_itr <int>, total_time <bch:tm>,
#> #   result <list>, memory <list>, time <list>, gc <list>
```

I *think* this is not normal, and probably a tidyr issue. The `do()` version should consume less memory at any point because the intermediate results are discarded, but the nest/unnest version shouldn't allocate more than `do()` overall.

**Comment by danilinares** [comment]
This is what I get:

    # A tibble: 12 x 15
       expression     n      min     mean   median      max `itr/sec` mem_alloc
     * <chr>      <int> <bch:tm> <bch:tm> <bch:tm> <bch:tm>     <dbl> <bch:byt>
     1 do             1   2.01ms   2.21ms   2.12ms   3.86ms   452.      50.09KB
     2 nest           1   9.57ms  11.07ms  10.85ms  12.78ms    90.3     107.9KB
     3 do             2   2.21ms   2.69ms   2.59ms   4.43ms   372.     320.09KB
     4 nest           2   8.89ms   10.1ms  10.13ms  11.62ms    99.0     574.4KB
     5 do             3   4.49ms   5.32ms   5.18ms   7.28ms   188.       2.95MB
     6 nest           3  12.96ms  14.31ms  13.72ms  16.54ms    69.9      4.95MB
     7 do             4  38.81ms  53.99ms  43.94ms 136.42ms    18.5     29.32MB
     8 nest           4  82.49ms 134.36ms 132.87ms 189.21ms     7.44    53.56MB
     9 do             5  399.8ms 441.29ms 441.29ms 482.79ms     2.27   292.99MB
    10 nest           5 706.86ms 706.86ms 706.86ms 706.86ms     1.41   511.09MB
    11 do             6    5.16s    5.16s    5.16s    5.16s     0.194    2.86GB
    12 nest           6    7.42s    7.42s    7.42s    7.42s     0.135     4.8GB
    # ... with 7 more variables: n_gc <dbl>, n_itr <int>, total_time <bch:tm>,
    #   result <list>, memory <list>, time <list>, gc <list>

I think I was imprecise in my comment in sctakoverflow. Rather than having large data frames I have long lists (in the form of a column of a dataframe) with no so large data frames. Given than according to this benchmark for small data frames nest is much slower than do, that might explain in part why our quickpsy package is much slower now.

**Comment by danilinares** [comment]
Hi,

**Comment by danilinares** [comment]
Do you want me to move it or you move it?

**Comment by lionel-** [comment]
I wanted the move bot to move it ;)
