### ISSUE TITLE
Add mapper support for compose

### ISSUE THREAD

**Issue by ColinFay** [tidyverse/purrr#556]
## Issue

Today, if I want to insert mappers in a `compose` call, I'll have to wrap it into : 

``` r
sample_round <- compose(
  as_mapper(~ round(.x, 2)),
  mean,
  as_mapper(~ sample(.x, 10))
)
map_dbl(mtcars, sample_round)
   mpg    cyl   disp     hp   drat     wt   qsec     vs     am   gear   carb 
 20.10   6.20 240.62 139.00   3.46   2.92  17.35   0.50   0.40   3.80   2.50 
```

As this is not supported: 

``` r
sample_round <- compose(
  ~ round(.x, 2),
  mean,
  ~ sample(.x, 10)
)
Error in FUN(X[[i]], ...) : 
  'list(...)[[1L]]' is not a function, character or symbol
```

This is because `compose` uses `lapply(list(...), match.fun)`, and `match.fun` doesn't know how to deal with formulas. 

## Proposed solution 

I suggest a modification for : 

``` r 
compose <- function(...) {
  fs <- lapply(list(...), as_mapper)
  n <- length(fs)
  
  last <- fs[[n]]
  rest <- fs[-n]
  
  function(...) {
    out <- last(...)
    for (f in rev(rest)) {
      out <- f(out)
    }
    out
  }
}

sample_round <- compose(
  ~ round(.x, 2),
  mean,
  ~ sample(.x, 10)
)
map_dbl(mtcars, sample_round)
   mpg    cyl   disp     hp   drat     wt   qsec     vs     am   gear   carb 
 21.77   5.80 293.78 125.90   3.53   3.27  17.87   0.30   0.70   3.60   2.30 
```

This would also allow constructing complex "pluckers" : 

``` r 
plop <- list(
  a = list(
    b = list(
      c = list(
        10, 20, 30
        )
    )
  ), 
  aa = list(
    b = list(
      c = list(
        10, 20, 30
      )
    )
  ), 
  aaa = list(
    b = list(
      c = list(
        10, 20, 30
      )
    )
  )
)

plucker <- compose(~ .x * 10, 1, "c", "b")
map(plop, plucker)
$a
[1] 100

$aa
[1] 100

$aaa
[1] 100
```
## Downside 

Current version of `compose` allows to compose with characters elements. I'm not sure if this is widely used though (the documentation do not reference this use case, so I guess we can safely assume this is seldom used): 

``` r 
new_compose <- purrr::compose("round", "mean")
map_dbl(mtcars, new_compose)
 mpg  cyl disp   hp drat   wt qsec   vs   am gear carb 
  20    6  231  147    4    3   18    0    0    4    3 
```

**Comment by egnha** [comment]
@ColinFay I'm not sure whether this well documented, but `map()` already applies `as_mapper()`, so your plucker can be expressed more succinctly like this:
```R
map(plop, list("b", "c", 1)) %>% str
#> List of 3
#> $ a  : num 10
#> $ aa : num 10
#> $ aaa: num 10
```
As for your other `compose()` example, may I suggest using `gestalt::compose()` instead, or better yet, the composition operator `` gestalt::`%>>>%` ``? The operator `%>>>%` comprehends the magrittr `%>%` syntax, so instead of
```R
sample_round <- purrr::compose(
  as_mapper(~ round(.x, 2)),
  mean,
  as_mapper(~ sample(.x, 10))
)
```
you can write
```R
library(gestalt)

sample_round <- sample(2) %>>>% mean %>>>% round(2)

set.seed(1)
purrr::map_dbl(mtcars, sample_round)
#> mpg      cyl   disp     hp   drat     wt   qsec     vs     am   gear   carb 
#> 19.60   6.00 227.55 216.00   3.80   3.51  17.13   0.00   0.50   3.00   5.00 
```
Like `%>%`, you read the composition from _left to right_.

**Comment by egnha** [comment]
The "mapper composition" you want is a composition of higher-order functions. So instead of modifying `compose()`, you can do:
```R
library(purrr)
library(gestalt)

mapper_compose <- list %>>>% map(as_mapper) %>>>% gestalt::compose
```
Such a composition works with `gestalt::compose()`, but not with `purrr::compose()`, because the former accepts both `...` and lists of functions, while the later does not.

I believe this does what you want:
```R
map(plop, mapper_compose("b", "c", 1, ~.x * 10)) %>% str
#> List of 3
#>  $ a  : num 100
#>  $ aa : num 100
#>  $ aaa: num 100
```
(Actually, in this particular example, it would be better to do
```R
map_dbl(plop, list("b", "c", 1)) * 10
```
optionally followed by `as.list()`, because `*` is vectorized.)

**Comment by ColinFay** [comment]
@egnha yep, this totally works for these fringe use cases, thanks for the advice :) 

Still, I think adding mapper support to `compose` would be consistent with the rest of the package

**Comment by lionel-** [comment]
We'd have to deprecate string-matching first so it'd make more sense to use `as_function()` I think, at least at first.

However if you're using the lambda formula already, isn't it simpler and more readable to just construct the function you need directly?

**Comment by lionel-** [comment]
I was talking about plucking support, i.e. using `as_mapper()` instead of `as_function()`. I think it's just simpler and more readable to do extraction within a custom lambda rather than composing plucker and functions with `compose()`.

**Comment by lionel-** [comment]
And `~` support can be implemented with `as_function()` without breaking the interface. Plucking support is a breaking change so should only be done if useful.

**Comment by ColinFay** [comment]
Ah, ok. 

It indeed seems like a very rare use case (this kind of plucking where you need to combine lambda and numeric/characters — I had to do this twice and I indeed implemented my own function to do that). 

Not worth the breaking change if `as_function()` could do the trick without breaking anything, my original suggestion was more about being able to use lamba inside compose for composing function :) 

 Should I make a PR with the modified version of `compose` with `as_function`?

**Comment by lionel-** [comment]
That'd be great! It should still use `match.fun()` for strings.

**Comment by edavidaja** [comment]
I posted [this issue](https://github.com/DavisVaughan/furrr/issues/51) at `furrr` initially, but I'm wondering if it's related to this discussion--essentially, I'm trying to compose with pluck, and it works with `map()` but not `future_map()` or `future_lapply()`. Happy to start a separate issue if it's unrelated.
