### ISSUE TITLE
flatten() fails on lists with unevaluated expressions

### ISSUE THREAD

**Issue by ArtemSokolov** [tidyverse/purrr#557]
It seems that `flatten()` doesn't handle lists with unevaluated expressions:

``` r
x <- list( "a", 5, quote(b) )
unlist(x)
# [[1]]
# [1] "a"
#
# [[2]]
# [1] 5
#
# [[3]]
# b

flatten(x)
# Error: Element 3 is not a vector (symbol)
```

This prevents its usage with nested lists of expressions, such as abstract syntax trees.

**Comment by batpigandme** [comment]
Interestingly, [`rlang::flatten()`](https://rlang.r-lib.org/reference/flatten.html) _does_ handle this without throwing an error:
``` r
library(purrr)
x <- list( "a", 5, quote(b))
unlist(x)
#> [[1]]
#> [1] "a"
#> 
#> [[2]]
#> [1] 5
#> 
#> [[3]]
#> b
purrr::flatten(x)
#> Error: Element 3 is not a vector (symbol)
rlang::flatten(x)
#> [[1]]
#> [1] "a"
#> 
#> [[2]]
#> [1] 5
#> 
#> [[3]]
#> b
```
<sup>Created on 2018-10-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by lionel-** [comment]
What will `vctrs::flatten()` do? ;)

**Comment by lionel-** [comment]
That's because `purrr::flatten()` tries to simplify lists that are already flat. There are plans to fix this behaviour, but not for this release round.

**Comment by lionel-** [comment]
See #575 for a discussion.
