### ISSUE TITLE
detect_all/detect_index_all

### ISSUE THREAD

**Issue by hammer** [tidyverse/purrr#563]
Hey I find the `detect`/`detect_index` functions handy together with `possibly` for finding bad list elements. Usually I would like to get all elements or indices that match, not just the first. Any interest in adding these functions to `purrr`?

**Comment by lionel-** [comment]
I think that would be `which(map_lgl(x, fn))` and `keep(x, fn)`? Perhaps we should add these examples in `?detect`?

**Comment by hammer** [comment]
Sure, I've found other ways to do it. I'm suggesting that the presence of `detect` and `detect_index` in the API makes it feel like there's a hole in the API where `detect_all`/`detect_index_all` should be. Up to y'all on what if feels like from your far-more informed perspective!

**Comment by lionel-** [comment]
I think it would be strange to have `keep()` and `detect_all()` be synonyms.
