### ISSUE TITLE
Add tidy dots support to compose()

### ISSUE THREAD

**Issue by ArtemSokolov** [tidyverse/purrr#564]
This is super minor, but the current behavior for passing a list of functions to `compose()` requires the usage of `invoke()` or `lift()`. It would be nice to add tidy dots support, allowing the list to be passed with the `!!!` operator:

```r
funs <- c( exp, log10, sqrt )
invoke( compose, funs )    # Works
lift( compose )(funs)      # Also works
compose( !!!funs )         # Error in !funs : invalid argument type
```

I believe the only modification required is to change [line 14 of compose.R](https://github.com/tidyverse/purrr/blob/43c3eb329001152762f618a62beec111702734b9/R/compose.R#L14) from

    fs <- lapply(list(...), match.fun)

to

    fs <- lapply(rlang::list2(...), match.fun)

Happy to submit a pull request.

**Comment by egnha** [comment]
#366 discusses this (among other things).

**Comment by ArtemSokolov** [comment]
Thanks for the pointer, @egnha. I see that the issue was originally discussed a year ago. Has there been any updates?

Is it still worth for me to submit a pull request focused specifically on tidy dots, or is it better to wait for the overhaul of the whole function, as you proposed?

**Comment by batpigandme** [comment]
Hi,

I'd say leave both of these open for now. purrr's had a couple of maintenance releases for compatibility, but nothing major in a while, so I imagine this will be reviewed/discussed in the next round of purrr updates.

Thanks for your patience.

**Comment by egnha** [comment]
@ArtemSokolov, in fact the issues in #366 have been resolved in the meantime, according to a different design, and expanded scope, outside of purrr: see the [gestalt](https://www.github.com/egnha/gestalt) package. While the focus there is on an infix form of composition, `%>>>%`, a `compose()` is included as well.

(In my view, `gestalt::compose()` could be a practical replacement for `purrr::compose()`. On the other hand, `purrr::compose()` works well for simple usage, as is, and I can understand that the purrr maintainers would prefer to minimize the number of import dependencies.)
