### ISSUE TITLE
pmap_chr() on a 0-column tibble crashes 32-bit R 3.5.1

### ISSUE THREAD

**Issue by wlandau** [tidyverse/purrr#565]
Using 43c3eb329001152762f618a62beec111702734b9:

```r
purrr::pmap_chr(tibble::tibble(x = 1)[, 0], paste)
```

![crash](https://user-images.githubusercontent.com/1580860/47458166-e74e2000-d7a6-11e8-9514-d34cb5fe3d05.png)

``` r
sessionInfo()
#> R version 3.5.1 (2018-07-02)
#> Platform: i386-w64-mingw32/i386 (32-bit)
#> Running under: Windows 7 x64 (build 7601) Service Pack 1
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United States.1252 
#> [2] LC_CTYPE=English_United States.1252   
#> [3] LC_MONETARY=English_United States.1252
#> [4] LC_NUMERIC=C                          
#> [5] LC_TIME=English_United States.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] compiler_3.5.1  backports_1.1.2 magrittr_1.5    rprojroot_1.3-2
#>  [5] tools_3.5.1     htmltools_0.3.6 yaml_2.2.0      Rcpp_0.12.19   
#>  [9] stringi_1.2.4   rmarkdown_1.10  knitr_1.20      stringr_1.3.1  
#> [13] digest_0.6.18   evaluate_0.12
```

**Comment by wlandau** [comment]
I forgot to mention: for Windows, this error appears to happen on 32-bit R 3.5.1 and devel, but not on 64-bit R and not for R 3.4.4.

**Comment by lionel-** [comment]
Simpler reprex:

```r
pmap(list(), identity)
```

**Comment by lionel-** [comment]
It seems that `VECTOR_ELT(empty_list, 0)` usually returns `NULL` but crashes on that platform. That's weird, I'd have thought it'd crash on all platforms.

**Comment by wlandau** [comment]
Just a guess, but I wonder if this could somehow be related to ALTREP. From [`Rinternals.h`](https://github.com/wch/r-source/blob/ae6c6d75d0421ea4a4b06a2059b0d7f7e387985e/src/include/Rinternals.h#L448), `VECTOR_ELT` is just `((SEXP *) DATAPTR(x))[i]`, and [`DATAPTR`](https://github.com/wch/r-source/blob/b60247bca7ed0e5d7565432c19e17db258957caf/src/include/Rinlinedfuns.h#L103-L106) now seems to rely on ALTREP functionality. This might explain why it crashes on R 3.5.1 but not 3.4.4. cc @gmbecker.
