### ISSUE TITLE
accumulate: the output vector is longer than the input

### ISSUE THREAD

**Issue by loladze** [tidyverse/purrr#569]
The documentation for accumulate says that the output has the same length as the input list:

accumulate(.x, .f, ..., .init)
Value: "A vector the same length of .x with the same names as .x" 

This does not seem to be always the case. For example the lengths are equal here:
 
    > 1:5 %>% accumulate(max)
    [1] 1 2 3 4 5

But here the output is a unit longer as it takes the initial condition:

    > 1:5 %>% accumulate(max, .init = 1)
    [1] 1 1 2 3 4 5
Should the documentation be updated?

**Comment by batpigandme** [comment]
Hmm, so I think, if this is expected behaviour, we should probably clarify the `.init` description, as well. The argument info for `.init` says:

> `.init` If supplied, will be used as the first value to start the accumulation, rather than using `x[[1]]`.

I read this as ~instead of, but in the example you give, and the one in the docs, it seems to be prepending `.init`, which is why it's `length(.x) + 1`.

``` r
library(purrr)
1:10 %>% accumulate(max, .init = 5)
#>  [1]  5  5  5  5  5  5  6  7  8  9 10
```

<sup>Created on 2018-11-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by loladze** [comment]
Yes, exactly. If the initial value is supplied, then it lengthens the output by one. Either the documentation should be updated, or for consistency of the accumulate behavior, the initial value should be dropped from the output by default.

**Comment by batpigandme** [comment]
Yep. I just talked to @hadley about this, and the prepending behaviour _is_ correct. So, a documentation update is in store clarifying that: the `.init` value is prepended, and that the resulting output with `.init` is `length(.x)` + 1. 

I'm at a conference for the next couple days, but will take care of it when I'm back (unless you'd like to give it a whirl — no pressure, either way is 100% fine)!

**Comment by loladze** [comment]
To keep the official documentation safe from my whirls :), I post suggested additions here in _italics_ 

**.init**  If supplied, will be used as the first value to start the accumulation, rather than using x[[1]]. This is useful if you want to ensure that reduce returns a correct value when .x is empty. If missing, and x is empty, will throw an error. _The .init value prepends to the output making its length = length(.x) + 1_

Value: A vector the same length of .x _, unless .init  is supplied extending the length by 1,_ with the same names as .x
