### ISSUE TITLE
Consistent dots-splicing

### ISSUE THREAD

**Issue by egnha** [tidyverse/purrr#576]
Some functions support dots-splicing, e.g.,
```R
compose(log, abs)
compose(!!!list(log, abs))
```
while others do not, e.g.,
```R
map(letters, paste, 1:3, sep = "_")
map(letters, paste, !!!list(1:3, sep = "_"))  # error
```
Should dots-splicing behavior be more consistent across purrr?

(I presume this might already be under consideration for tidyverse packages, generally. Just flagging it for the record ... )

**Comment by lionel-** [comment]
I've just started looking into this 2 minutes ago ;)

**Comment by lionel-** [comment]
This is not as trivial as I thought because `as_mapper()` also takes the dots, and we need to be careful to evaluate spliced arguments only once. So for now we'll just have to rely on the mapped function to support tidy dots.

**Comment by egnha** [comment]
That was my feeling as well. One workaround for effectively making `map_*()` comprehend dots-splicing would be for `partial()` to comprehend dots-splicing (cf. #457). But I'm not sure whether that'd be a practical alternative. (Would most users think to do that? I'd wager not.)
