### ISSUE TITLE
Recursively simplifying lists using `modify_depth`

### ISSUE THREAD

**Issue by r-cheologist** [tidyverse/purrr#601]
As first laid out [here on `stackoverflow`](https://stackoverflow.com/q/53666007/2103880), I am trying to simplify deep lists (originating from `XML` processing) such that

    xml_list <- list(
      a = "7",
      b = list("8"),
      c = list(
        c.a = "7",
        c.b = list("8"),
        c.c = list("9", "10"),
        c.d = c("11", "12", "13")),
      d = c("a", "b", "c"))

becomes

    list(
      a = "7",
      b = "8",
      c = list(
        c.a = "7",
        c.b = "8", 
        c.c = list("9", "10"),
        c.d = c("11", "12", "13")),
      d = c("a", "b", "c"))

After wrestling with a recursive function based on `rapply` that would quickly run into `C` stack errors with lists of even modest size, I found `purrr` functionality and came up with a function that **NEARLY** does what I want:

    library(magrittr)
    clean_up_list <- function(xml_list)
    {
      list_depth <- xml_list %>%
        purrr::vec_depth()
      for(dl in rev(sequence(list_depth)))
      {
        xml_list %<>%
          purrr::modify_depth(
            .depth = dl,
            .ragged = TRUE,
            .f = function(x)
            {
              if(is.list(x) && length(x) == 1 && length(x[[1]]) == 1)
              {
                unlist(x, use.names = FALSE)
              } else {
                x
              }
            })
      }
      return(xml_list)
    }

What keeps puzzling me is why elements that used to be vectors (like `c.d` and `d` in the example) now are converted to lists --- where am I erring and how to prevent that?

**Comment by lionel-** [comment]
Can you please try with the dev version? `modify_depth()` now uses `[[<-` to update elements and I'm getting this result:

```r
list(
  a = "7",
  b = "8",
  c = list(
    c.a = "7",
    c.b = "8",
    c.c = list("9", "10"),
    c.d = c("11", "12", "13")
  ),
  d = c("a", "b", "c")
)
```

**Comment by r-cheologist** [comment]
On Tue, 2018-12-11 at 06:48 -0800, Lionel Henry wrote:
> Can you please try with the dev version? modify_depth() now uses [[<-
> to update elements and I'm getting this result:
> list(
>   a = "7",
>   b = "8",
>   c = list(
>     c.a = "7",
>     c.b = "8",
>     c.c = list("9", "10"),
>     c.d = c("11", "12", "13")
>   ),
>   d = c("a", "b", "c")
> )

Thanks! Works as expected with the development version. When will the
change show up in the main line.

Joh

**Comment by lionel-** [comment]
Before the new year.
