### ISSUE TITLE
Extending map to handle higher-dimensional arrays

### ISSUE THREAD

**Issue by egnha** [tidyverse/purrr#606]
It'd be handy if `map_*()` and `imap_*()` could handle functions returning higher-dimensional arrays, by gaining an output-shape parameter (defaulting to `1`). That is, if they were to behave like this generalization of `map_dbl()`:
```R
map_dbl <- function(.x, .f, ..., .shape = 1) {
  f <- as_mapper(.f)
  vapply(.x, f, FUN.VALUE = array(NA_real_, .shape), ...)
}
```
A typical use beyond the current capability of `map_*()` would be getting a matrix by mapping a function returning a vector (of a fixed length and type).

**Comment by hadley** [comment]
I think for now we're going to say that this is out of scope for purrr. It's a relatively rare ask and I think it will require substantial work to think through the consequence for all families of purrr functions.
