### ISSUE TITLE
Unexpected behavior when using pmap with factors

### ISSUE THREAD

**Issue by gvwilson** [tidyverse/purrr#611]
I can compare factors to strings using `filter` and other `dplyr` functions, but I cannot do this inside `pmap` (presumably because what's actually passed in is the integer value of the factor, and its relationship to the factor name has been lost). It took me a while to figure out what was going on: is there a way to retain factor name information inside `pmap` and its ilk, or should I PR a warning or counter-example of some kind for the docs?

```
library(tidyverse)

data <- tibble(
  left = factor(c("a", "a", "b", "b")),
  right = c(1, 2, 1, 2)
)

cat("Initial table\n")
data

cat("\nComparing strings to factors works\n")
data %>%
  filter(left == "a")

cat("\nTrying to compare factor to string in pmap doesn't\n")
data %>%
  pmap(function(...) {
    args <- list(...)
    if (args[[1]] == "a") {
      "alpha"
    } else if (is.numeric(args[[1]])) {
      "numeric"
    } else {
      args[[1]]
    }
  })
```

**Comment by lionel-** [comment]
Fixed with the devel version! :)

**Comment by gvwilson** [comment]
Thanks @lionel - can you please point me at the docs that explain the new behavior? Also, happy new year!

**Comment by lionel-** [comment]
There is no doc because we just implement the regular subsetting semantics of vectors in R. This was contributed here: https://github.com/tidyverse/purrr/pull/554

Once we integrate vctrs into purrr, we'll fix the remaining of such issues.
