### ISSUE TITLE
compose: Formula notation gives error

### ISSUE THREAD

**Issue by mrstlee** [tidyverse/purrr#614]
```r
purrr::compose(~.x, ~.x + 1)
#> Error in FUN(X[[i]], ...): 'list(...)[[1L]]' is not a function, character or symbol
```

I'm using purrr 0.2.5 on windows 10.

Note that I get the same result with the example from the help page:

```r
purrr::compose(~paste(.x, "foo"), ~paste(.x, "bar"))
#> Error in FUN(X[[i]], ...): 'list(...)[[1L]]' is not a function, character or symbol
```
Thanks!

**Comment by lionel-** [comment]
Thanks to @ColinFay's contribution, this is implemented in the next purrr version that will be released later this month.
