### ISSUE TITLE
compose: '.dir' argument not recognised.

### ISSUE THREAD

**Issue by mrstlee** [tidyverse/purrr#615]
``` r
purrr::compose(function(.x) paste(.x, "foo"), function(.x) paste(.x, 
    "bar"), .dir = "forward")
#> Error in get(as.character(FUN), mode = "function", envir = envir): object 'forward' of mode 'function' was not found
```
I'm using purrr 0.2.5 on windows 10.

I guess evaluation of '...' slurps in the '.dir' argument?

Thanks!

**Comment by lionel-** [comment]
It seems you're consulting the documentation for the development version but you have the CRAN version installed. You can install it with:

```r
remotes::install_github("tidyverse/purrr")
```

**Comment by lionel-** [comment]
I think this is normally the case, but we had to rebuild the site when we switched to automatic deployment of the website. Hopefully once the next version of purrr is out, the website will be pinned at the CRAN release. Sorry about that.

**Comment by mrstlee** [comment]
No worries, Lionel. Not bad practice for me to check the doc revision vs
the module rev I'm using!
