### ISSUE TITLE
Should accumulate get its own documentation?

### ISSUE THREAD

**Issue by MilesMcBain** [tidyverse/purrr#616]
`accumulate` is hell useful but every time I try to use it I spend a while trying to parse the doco, which is mostly about `reduce`. Going to see if I can improve for tidyverse-dev-day.

**Comment by MilesMcBain** [comment]
@batpigandme Can I has tidyverse-dev-day tag plz?

**Comment by batpigandme** [comment]
@MilesMcBain Lionel beat me to it! 💥

**Comment by lionel-** [comment]
I'm not sure the documentation should be separate because accumulate is just like a reduce that keeps the intermediate steps. Maybe it needs its own section?

**Comment by lionel-** [comment]
Documentation for accumulate2 would be great!
