### ISSUE TITLE
compose() does not work with generic functions

### ISSUE THREAD

**Issue by MarselScheer** [tidyverse/purrr#629]
In purrr 0.3.0
`purrr::compose(t,t,identity)(1:3)`
does not match 
`purrr::compose(t,t)(1:3)`
In purrr 0.2.5 they match and I assume that this is the correct behavior

**Comment by yutannihilation** [comment]
The problem is `compose()` now extracts the first function's body. If the body `UseMethod()`, the value is returned immediately (right?). So, when we add a non-generic function (e.g. `identity()`) at the end, it works.

Can this line simply be reverted to `out <- first_fn(...)`?:

https://github.com/tidyverse/purrr/blob/240f7b2fdd4ef41ef9e2b5ce29e2d55708405639/R/compose.R#L52

``` r
library(purrr)

foo <- function(...) UseMethod("foo")
foo.default <- function(...) message("foo")

purrr::compose(foo)()
#> foo
purrr::compose(foo,foo)()
#> foo
purrr::compose(foo,foo,foo)()
#> foo

body(purrr::compose(foo,foo,foo))
#> {
#>     out <- {
#>         UseMethod("foo")
#>     }
#>     fns <- list(function (...) 
#>     UseMethod("foo"), function (...) 
#>     UseMethod("foo"))
#>     for (fn in fns) {
#>         out <- fn(out)
#>     }
#>     out
#> }

# adding non-generic function works
purrr::compose(foo,foo,foo,function(...) NULL)()
#> foo
#> foo
#> foo
#> NULL
```

<sup>Created on 2019-01-31 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by lionel-** [comment]
@yutannihilation Good diagnostic. The goal was to have the same formals list as the original function, so we can have auto-completion of arguments etc. If I can't make it working with generic functions, I'll revert that feature.

**Comment by yutannihilation** [comment]
Thanks for the background, so we need to construct a function call by matching formals like this?

``` r
wrap <- function(f) {
  f_expr <- rlang::enexpr(f)
  
  formal_args <- names(formals(f))
  dots_pos <- which(formal_args == "...")
  
  formal_args <- setNames(rlang::syms(formal_args), formal_args)
  
  args_before_dots <- formal_args[seq_along(formal_args) < dots_pos]
  args_after_dots <- formal_args[seq_along(formal_args) > dots_pos]
  
  body <- rlang::expr((!!f_expr)(!!!args_before_dots, ..., !!!args_after_dots))
  rlang::new_function(formals(f), body, rlang::caller_env())
}

wrap(mean)
#> function (x, ...) 
#> mean(x = x, ...)

wrap(dplyr::group_by)
#> function (.data, ..., add = FALSE, .drop = FALSE) 
#> dplyr::group_by(.data = .data, ..., add = add, .drop = .drop)

f <- mean
wrap(f)(1:10)
#> [1] 5.5
```

<sup>Created on 2019-02-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by lionel-** [comment]
@yutannihilation This approach is not compatible with `substitute()` / `enquo()`.

**Comment by yutannihilation** [comment]
Ah, I see.
