### ISSUE TITLE
updating purrr to 0.3.0 stopped by Trend Micro

### ISSUE THREAD

**Issue by Vidaringa** [tidyverse/purrr#630]
I don't know if this should be posted here or not. I tried to update purrr from 0.2.5 to 0.3.0. I got "R Session Aborted". After that I couldn't launch RStudio, I just got the message: "This site can't be reached".

I found out it was my trend micro virus protection that caused this. I had to install RStudio again to be able to use it.

I can't update to 0.3.0 unless I allow it in trend micro.

**Comment by Vidaringa** [comment]
I tried to install in in a fresh session and it worked.

Thank you for your help.

**Comment by lionel-** [comment]
Great! I recommend installing packages with https://github.com/r-lib/pak, it is much safer on Windows and will not break your library when the DLL can't be updated.
