### ISSUE TITLE
modify2() doesn't preserve 1-column data.frame

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/purrr#632]
``` r
library(purrr)

# OK
modify(data.frame(x = 1), ~ identity(.x))
#>   x
#> 1 1

# wrong
imodify(data.frame(x = 1), ~ identity(.x))
#> [[1]]
#> [1] 1

# wrong
modify2(data.frame(x = 1), "x", ~ identity(.x))
#> [[1]]
#> [1] 1

# OK
imodify(data.frame(x = 1, y = 1), ~ identity(.x))
#>   x y
#> 1 1 1
```

<sup>Created on 2019-02-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by yutannihilation** [comment]
``` r
purrr:::recycle_args(list(data.frame(x = 1), "x"))
#> [[1]]
#> [[1]][[1]]
#> [1] 1
#> 
#> 
#> [[2]]
#> [1] "x"

purrr:::recycle_args(list(data.frame(x = 1, y = 2), c("x", "y")))
#> [[1]]
#>   x y
#> 1 1 2
#> 
#> [[2]]
#> [1] "x" "y"
```

<sup>Created on 2019-02-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

The problem is `rep.int()` doesn't preserve data.frame.

https://github.com/tidyverse/purrr/blob/28a6811a9abcbdc6263a3ec04a87531574c9fa2d/R/utils.R#L46

Though vctrs might provide a proper recycling, I guess we should not allow recycling for the first argument in `modify()`. I feel this should raise an error, since there's no element at the position of `2` of the `.x`:

``` r
purrr::modify2(data.frame(x = 1), 1:2, ~ .)
#> [[1]]
#> [1] 1
#> 
#> [[2]]
#> [1] 1
```

<sup>Created on 2019-02-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by hadley** [comment]
Part of #878 — I think we can just make recycling work even though it's not really needed here. It makes for one less different to explain.
