### ISSUE TITLE
map_chr implicit coercion

### ISSUE THREAD

**Issue by grayskripko** [tidyverse/purrr#633]
Why it isn't so strict to throw an error?
```{r}
1:2 %>% map_chr(length)
# > [1] "1" "1"
```

**Comment by lionel-** [comment]
This will change when we switch to vctrs for our coercion backend.

**Comment by grayskripko** [comment]
ok. Do you need this issue open?

**Comment by lionel-** [comment]
Yes we'll tackle it at the vctrs milestone.

**Comment by hadley** [comment]
Now tracking in #904
