### ISSUE TITLE
`assign_in()` `NULL` should assign rather than remove

### ISSUE THREAD

**Issue by lionel-** [tidyverse/purrr#636]
The modfied object returned by `pluck<-` should always have the same length structure.

**Comment by lionel-** [comment]
Document difference with `[[<-`: no removal, no expansion.

**Comment by lionel-** [comment]
After feedback from #634, maybe we should let puck create new elements — at least by name, it feels like assigning by index should be stricter (semantic difference between vector and associative containers).

This means we'd allow removing elements with `zap()`, but only by name?

What do you think @hadley?

**Comment by hadley** [comment]
I think it seems like a nice principle that `pluck<-(x, i, value)` have the same sizes and types as `x`. Assigning deeply into structures where bits might not exist seems risky to me and I think you'd be better off first normalising your data structure with some other tool.

**Comment by lionel-** [comment]
In the shallow case it seems reasonable to do `assign_in(x, "elt", value)` and expect new elements to be added. In that case it's more of a `$<-` action than a `[[<-` one.

**Comment by hadley** [comment]
I think this needs more thought about what our desired `$<-` vs `[[<-` vs `[<-` semantics are

**Comment by hadley** [comment]
Reprex:

``` r
library(purrr)

x <- list(a = 1, b = list(c = 1))
pluck(x, "a") <- NULL
str(x)
#> List of 1
#>  $ b:List of 1
#>   ..$ c: num 1

pluck(x, "b", "c") <- NULL
str(x)
#> List of 1
#>  $ b: Named list()
```

<sup>Created on 2022-08-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Definitely feels like purrr is standardising on using `zap()` to delete.
