### ISSUE TITLE
prepend: fails for empty list

### ISSUE THREAD

**Issue by czeildi** [tidyverse/purrr#637]
`purrr::prepend` fails for empty list due to the checking of the `before` param though (partly based on the documentation) I would expect it to work as `base::append` by default. Is there a reason for this?

If you agree that it should work for empty lists as well I am happy to submit a PR.

``` r
purrr::prepend(list(), "a")
#> Error in purrr::prepend(list(), "a"): before > 0 && before <= n is not TRUE

append("a", list())
#> [[1]]
#> [1] "a"

purrr::prepend(list("b"), "a")
#> [[1]]
#> [1] "a"
#> 
#> [[2]]
#> [1] "b"
append("a", list("b"))
#> [[1]]
#> [1] "a"
#> 
#> [[2]]
#> [1] "b"
```

Created on 2019-02-10 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

My first idea for implementation:
```
function (x, values, before = 1) 
{
    n <- length(x)
    stopifnot(n == 0 || (before > 0 && before <= n))
    if (before == 1) {
        c(values, x)
    }
    else {
        c(x[1:(before - 1)], values, x[before:n])
    }
}
```

**Comment by lionel-** [comment]
Maybe `before` should have `NULL` as default argument? Then it'd mean to prepend at the beginning, even in the 0 case? If `1` is passed instead, we'd still get an error as currently happens because this means the user assumptions regarding the input vector are not fulfilled.

 A PR would be great!
