### ISSUE TITLE
Type-stable roll map

### ISSUE THREAD

**Issue by luka-s** [tidyverse/purrr#642]
Working with time series data, I frequently apply calculations to a rolling window. I propose to extend purrr with type-stable rolling calculations. The proposal addresses the same use case as #420 with an interface similar to `purrr::map` [edit:] and inspired by [tsibble::slide](https://tsibble.tidyverts.org/reference/slide.html) (@DavisVaughan: thanks for pointing out tsibble).

**Description:**

`slide` applies a function .f over a rolling window of size .n of a vector and (optionally) pads the result with `.fill` such that the length of the resulting vector matches the input length and the result is  'left', 'center' or 'right' aligned with the rolling window. `.fill = NULL` means no filling.

`slide(.x, .f, 3, .fill = NULL, ...)` corresponds to `c(.f(.x[1:3], ...), .f(.x[2:4], ...), etc. )`.

slide always returns a list, slide_lgl, slide_int, slide_dbl and slide_chr return an atomic vector of the indicated type (or die trying).

`slide2` and `pslide` apply .f over a rolling window in two or more vectors of equal length.

The `_at` variants apply the rolling function only over windows that are 'left', 'center' or 'right' aligned with positions specified by `.at`. The remaining elements are filled with `.fill` or dropped if `.fill = NULL`.

**Usage:**
```
slide(.x, .f, .n, .align = c("right", "center", "left"), .fill = list(NULL), ...)
slide_lgl(.x, .f, .n, .align = c("right", "center", "left"), .fill = NA, ...)
slide_int
slide_dbl
slide_chr

slide_at(.x,. at, .f, .n, .align = c("right", "center", "left"), .fill = list(NULL), ...)
slide_at_lgl(.x, .at, .f, .n, .align = c("right", "center", "left"), .fill = NA, ...)
slide_at_int
slide_at_dbl
slide_at_chr

slide2(.x, .y, .f, .n, .align = c("right", "center", "left"), .fill = list(NULL), ...)
slide2_lgl(.x, .y, .f, .n, .align = c("right", "center", "left"), .fill = NA, ...)
slide2_int
slide2_dbl
slide2_chr

slide2_at(.x, .y, .at, .f, .n, .align = c("right", "center", "left"), .fill = list(NULL), ...)
slide2_at_lgl(.x, .y, .at, .f, .n, .align = c("right", "center", "left"), .fill = NA, ...)
slide2_at_int
slide2_at_dbl
slide2_at_chr

pslide(.l, .f,.n, .align = c("right", "center", "left"), .fill = list(NULL), ...)
pslide_lgl(.l, .f,.n, .align = c("right", "center", "left"), .fill = NA, ...)
pslide_int
pslide_dbl
pslide_chr

pslide_at(.l, .at, .f,.n, .align = c("right", "center", "left"), .fill = list(NULL), ...)
pslide_at_lgl(.l, .at, .f,.n, .align = c("right", "center", "left"), .fill = NA, ...)
pslide_at_int
pslide_at_dbl
pslide_at_chr
```

**Examples:**
```
slide_chr( c("a", "b", "c", "d", "e"), str_c, 3, collapse = "-")

slide2_dbl(runif(500), runif(500), cor, 365)
```

I look forward to questions and comments.

If the idea resonates with others, I can contribute a C implementation along the lines of map_impl.

**Comment by lelm** [comment]
Why extend purrr?

- roll_map fits to purrr’s purpose to 'provide a functional toolkit for R'. It is a type-stable version of zoo::rollapply, like map is a type-stable version of sapply.
- The proposed function signature is intuitive for users of purrr::map as map is a special case of roll_map with argument .k = 1: `map(x, f, ...)` is identical to `roll_map(x, f, .k = 1, ...)`
- The application of a function over a rolling window is a frequent use case in contributed R packages, including [zoo::rollapply](https://github.com/cran/zoo/blob/master/R/rollapply.R) and [tibbletime::rollify](https://github.com/cran/tibbletime/blob/master/R/rollify.R) (apply arbitrary R function) and [roll](https://cran.r-project.org/web/packages/roll/index.html), [RcppRoll](https://cran.r-project.org/web/packages/RcppRoll/index.html), [rollRegress](https://cran.r-project.org/web/packages/rollRegres/index.html) and [RollingWindow](https://github.com/andrewuhl/RollingWindow) packages (apply specific functions) to name just a few.
- An implementation in C along similar lines as map_impl allows for a speed-gain over a loop in R: a vector of length of the rolling window needs to be allocated only once and its content can be overwritten in each iteration.

**Comment by DavisVaughan** [comment]
You should have a look at the window functions of tsibble as they implement a full set of the functionality you are looking for https://tsibble.tidyverts.org/articles/window.html

**Comment by lelm** [comment]
Thanks for pointing out  type-stable rolling calculations in `tsibble::slide`.

I continue to advocate the addition of simple rolling calculations to purrr. Rolling calculations do not require the introduction of time-series objects, which is the main purpose of zoo, tsibble or tibbletime packages (the packages that currently implement rolling calculations with arbitrary functions).

**Comment by lelm** [comment]
Thanks for pointing out  type-stable rolling calculations in [tsibble::slide](https://tsibble.tidyverts.org/reference/slide.html).

I quite like the name `slide`, precise and to the point. I have edited the proposal above, replacing the initial name `roll_map` with `slide` and adding `slide_at`.
- The proposal differs from tsibble::slide mainly in the use of '.at' instead of '.step' to define a subset of rolling windows over which to apply the function. '.at' specifies positions more precisely and one can imagine e.g. to apply .f over windows ending at the first observation in each calendar month.
- An argument '.partial' (or alternatively minimum number of observations as in [pandas.rolling](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rolling.html)) can be added if needed.

I continue to advocate the addition of rolling calculations to purrr. Rolling calculations do not require the introduction of time-series objects, which is the main purpose of zoo, tsibble or tibbletime packages that currently implement rolling calculations with arbitrary functions.

**Comment by luka-s** [comment]
I've pushed a first draft of `slide` and `slide_[lgl|int|dbl|chr]` to [speedtest](https://github.com/luka-s/purrr/tree/speedtest) branch in luka-s/purrr to demonstrates the speed of a C implementation that allocates a vector for the rolling window only once and overwrites its values in each iteration.

In an example computing the rolling sum of the preceding 100 elements in a vector of length 10'000, median execution time of the proposed C implementation is roughly four times faster than an [R implementation](https://github.com/luka-s/purrr/blob/speedtest/R/slide_R.R) based on map.

Comparing to rolling window calculations in other packages, the proposed C implementation is roughly 12 times faster than `zoo::rollapply`, 9 times faster than `tibbletime::rollify` and 4 times faster `tsibble::slide`. The latter takes roughly as much time as above R implemenation.

```r
install.packages(c("zoo", "tibbletime", "tsibble", "RcppRoll", "devtools"))
devtools::install_github("luka-s/purrr", ref = "speedtest")
```
```r
x <- runif(10000)
n <- 100
microbenchmark::microbenchmark(
    "zoo::rollapply" = zoo::rollapply(x, n, sum, fill = NA, align = "right"),
    "tibbletime::rollify" = tibbletime::rollify(sum, n, na_value = NA)(x),
    "tsibble::slide" = tsibble::slide_dbl(x, sum, .size = n, .align = "right"),
    "R implementation" = purrr::slide_dbl_R(x, sum, n, .align = "right"),
    "proposed purrr::slide" = purrr::slide_dbl(x, sum, n, .align = "right"),
    check = function(x) all(purrr::map_lgl(x, identical, x[[1]])))
## Unit: milliseconds
##                   expr      min         lq      mean     median        uq       max neval
##         zoo::rollapply 90.04881 108.572619 118.31155 117.652107 124.24313 175.40573   100
##    tibbletime::rollify 67.76580  75.086954  85.31775  80.009190  83.59292 187.84146   100
##         tsibble::slide 25.87709  34.840706  41.42198  39.962938  44.54917 106.35733   100
##       R implementation 23.44598  31.331699  36.41349  37.422567  41.01313  73.53319   100
##  proposed purrr::slide  7.31262   8.651799  11.63356   9.111142  14.90900  23.13753   100
```

Of course, a specific implementation of the rolling sum in C or C++ is much faster than
applying an arbitrary R function over a rolling window: `RcppRoll::roll_sum` is
roughly 10 times faster than a rolling sum with the proposed slide function.
```r
microbenchmark::microbenchmark(
    "proposed purrr::slide" = purrr::slide_dbl(x, sum, n, .align = "right"),
    "RcppRoll" = RcppRoll::roll_sum(x, n, fill = NA, align = "right"),
    check = function(x) all(purrr::map_lgl(x, identical, x[[1]])))
## Unit: microseconds
##                   expr      min        lq      mean   median        uq       max neval
##  proposed purrr::slide 6038.807 6743.3125 7730.0684 7177.788 8660.9295 14728.798   100
##               RcppRoll  645.467  668.0855  722.4592  694.490  733.2655  1143.284   100
```

Execution times are measured on my MacBook Pro late 2016 model with 2.9 GHz Intel Core i7 processor running R 3.5.2.

**Comment by DavisVaughan** [comment]
I've wanted to ask the tsibble team if they would move their rolling functions into a separate package for awhile now. 90% of it is not tsibble specific (they have a new `slide_tsibble()` function but that could stay there).

I personally think it would make a lot of sense for all of this to be in a separate package. The tsibble versions could serve as a pure R +map() implementation and then, incrementally, faster C versions could be rolled out.

**Comment by lionel-** [comment]
This is all now covered by Davis' package https://github.com/DavisVaughan/slide
