### ISSUE TITLE
reduce applied to a list of functions

### ISSUE THREAD

**Issue by neuwirthe** [tidyverse/purrr#643]
reduce does not work in the following example.
Should reduce applied to a lust of functions work this way?

```
compose <- function(f,g){
  function(x)f(g(x))
}
compose(sin,sqrt)(2)
reduce(list(sin,sqrt),compose,.dir="backward")(2)
reduce(list(sin,sqrt),compose,.dir="forward")(2)
reduce(list(sin,sqrt),compose,.dir="forward") %>% class()
reduce(list(sin,sqrt),compose,.dir="backward") %>% class()
```

**Comment by batpigandme** [comment]
When I try to run this, I'm getting the following error after trying to run the first `reduce()`.
```r
#> Error: C stack usage  7969232 is too close to the limit
```
Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

You can install reprex by running (you may already have it, though, if you have the tidyverse package installed):
```r
install.packages("reprex")
```

Thanks

**Comment by neuwirthe** [comment]
The error message you get is exactly why I wrote the post.
So, you have reproduced the error yourself ;-)

**Comment by batpigandme** [comment]
OK. For future reference, it's helpful to know what error you're encountering for triaging/figuring out issues. reprex doesn't work in this case anyhow, because of the C stack error, but including the error that you _are_ getting in the issue makes things just a little bit easier to get sorted!

**Comment by egnha** [comment]
@neuwirthe, `reduce()` isn't required to compose a list of functions. (In fact, doing so adds some overhead to the resulting composition.) It is more idiomatic to use unquote-splicing to compose a list of functions, e.g.
```R
fns <- list(sin, cos)
compose(!!! fns)
```
