### ISSUE TITLE
partial() creates a fragile data mask

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/purrr#649]
I originally reported this in #647, but now I feel this is a different issue. Though this is how a data mask is used by `eval_tidy()`, I'm afraid `partial()` doesn't do the right thing. Probably, the enclosing environment should be passed as the quosure's environment (currently it's the empty env)?

``` r
library(purrr)

p_mean <- partial(mean, na.rm = TRUE)
rlang::env_parents(get("mask", environment(p_mean)))
#> [[1]]   <env: 0x7fb1b2e94300>
#> [[2]]   <env: 0x7fb1b2d27a28>
#> [[3]] $ <env: namespace:purrr>
#> [[4]] $ <env: imports:purrr>
#> [[5]] $ <env: namespace:base>
#> [[6]] $ <env: global>

p_mean(1:10)
#> [1] 5.5

rlang::env_parents(get("mask", environment(p_mean)))
#> [[1]]   <env: 0x7fb1b2e94300>
#> [[2]] $ <env: empty>
```

<sup>Created on 2019-02-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by lionel-** [comment]
The parent of data masks are unstable by design. Not sure what is the environment it got rechained to here. But it will be rechained to the quosure environment (stored in `call`) at the next`eval_tidy()`.

**Comment by lionel-** [comment]
We really need two-parent environments for implementing data masks. Since we can't do that yet, we rechain the parent of the mask from quosures to quosures to simulate it.

There's a quosure inversion mechanism in `partial()` that might explain the environment there. Oh which reminds me that `call` won't be a quosure but a normal call to be evaluated in `partial()`'s environment. This will be the case because of the default value of `env` in `eval_tidy()`.

**Comment by yutannihilation** [comment]
Thanks for the explanation! I know rechaining, but I don't see how the reference to the calling environment of `partial()` is kept... Probably this is just my problem of understanding about tidy eval, sorry.

**Comment by lionel-** [comment]
In the current implementation the calling environment of partial is ignored.

**Comment by yutannihilation** [comment]
Thanks, I just didn't understand this can be evaluated in the empty env, thanks to the fact that the unquoted function contains the environment and `mean.default` is registered in `.__S3MethodsTable__.`.

``` r
library(rlang)

version$version.string
#> [1] "R version 3.5.2 (2018-12-20)"

q <- new_quosure(expr((!!mean)(1)), empty_env())
eval_tidy(q, list())
#> [1] 1

ls(.__S3MethodsTable__., pattern = "mean")
#> [1] "mean.Date"     "mean.default"  "mean.difftime" "mean.POSIXct" 
#> [5] "mean.POSIXlt"  "mean.quosure"  "print.kmeans"
```

<sup>Created on 2019-02-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>


And it's not the case with the older version of R...

``` r
library(rlang)

version$version.string
#> [1] "R version 3.4.4 (2018-03-15)"

q <- new_quosure(expr((!!mean)(1)), empty_env())
eval_tidy(q, list())
#> Error in UseMethod("mean"): no applicable method for 'mean' applied to an object of class "c('double', 'numeric')"

ls(.__S3MethodsTable__., pattern = "mean")
#> [1] "mean.quosure" "print.kmeans"
```

<sup>Created on 2019-02-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by lionel-** [comment]
Yes in older versions of R the base methods are scoped lexically, they are now registered from R 3.5.
