### ISSUE TITLE
invisibility of return value not preserved by partial

### ISSUE THREAD

**Issue by ggrothendieck** [tidyverse/purrr#656]
`f` returns invisibly but `partial` of it returns visibly.  I would have expected that the visiblity/invisibility not be affected by `partial`.

```r
f <- function(x) print(x + x)
f(3)
## [1] 6

library(purrr)
partial(f, x = 3)()
## [1] 6
## [1] 6
```

**Comment by edvaldig** [comment]
I had the same request, i.e. make partial and compose support _void_ functions. E.g.:

`log_error <- purrr::partial(cli::cat_line, col = "red")`

Currently this will print out the line in red but also return NULL, the same applies to compose:

`log_error <- purrr::compose(invisible, purrr::partial(cli::cat_line, col = "red"))`

The fix could be as simple as to have a boolean parameter for whether there should be a return value or not.

**Comment by pnacht** [comment]
As far as I can tell, the bug isn't in `purrr::partial`, but in `rlang::eval_tidy`, which `partial` uses to evaluate the final function call.

``` r
print(1)
#> [1] 1

eval(quote(print(1)))
#> [1] 1

rlang::eval_tidy(quote(print(1)))
#> [1] 1
#> [1] 1
```

<sup>Created on 2020-04-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I've posted this on the `rlang` github: https://github.com/r-lib/rlang/issues/961

**Comment by lionel-** [comment]
We now use a simpler approach when all arguments are from the same environment, which is the common case. This preserves visibility.
