### ISSUE TITLE
Idea: having a `selectively()` adverb as an alternative to `*_if` functions.

### ISSUE THREAD

**Issue by jameslairdsmith** [tidyverse/purrr#657]
Many of the existing purrr functions already have `*_if` variants that allow users to apply a function to only those elements that satisfy a given predicate. But sometimes a user will want to use one of the functions that doesn't have an `*_if` variant with a predicate. An example might be if you wanted to make use of `modify_depth()`, but only modify the elements at a given depth that also satisfy a given predicate.

It would be possible to make variants that did this (eg. `modify_depth_if()`), but that seems unwieldy and confusing. One could also add `.p = ` arguments to all the functions, but that may also be confusing and couldn't be used beyond the purrr functions.

A more simple and elegant way to deal with this would be to have an adverb like `selectively()` which would take a function (`.f`) and predicate (probably `.p`) as inputs and return a new function that did the same thing as `.f` but only performed it on elements that satisfied `.p`. Elements that didn't satisfy `.p` would be left as is or optionally have an `.else` function applied to them as it is at the moment with the `*_if` functions.

In this form it would only work for applying a predicate test to the first argument of `.f`, but that already covers many use cases. I could imagine there being advanced variants that took more, perhaps like `selectively2()` for the first two arguments. There may also be a way to do it with named arguments or functions that take dots as their first argument.

A simple example would be something like this:

``` r
library(tidyverse)

times_ten <- function(x){x * 10}
is_more_than_two <- function(x){if(x > 2){TRUE}else{FALSE}}

number <- 1:5

tibble(number) %>% 
  mutate(ten_times_number = map_if(number, 
                                   is_more_than_two, 
                                   times_ten)) %>% 
  unnest(ten_times_number)
#> # A tibble: 5 x 2
#>   number ten_times_number
#>    <int>            <dbl>
#> 1      1                1
#> 2      2                2
#> 3      3               30
#> 4      4               40
#> 5      5               50
```

<sup>Created on 2019-03-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Instead you could write this to get the same output:

``` r
## doesn't work
tibble(number) %>% 
  mutate(ten_times_number = map_dbl(number, selectively(times_ten, 
                                                        .p = is_more_than_two))
```

<sup>Created on 2019-03-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

I like the idea of using `.if = ` rather than `.p = ` because it would read better, but for consistency with the other functions and to avoid confusion with the `if()` function it should probably be `.p =`.

Apologies if this has been mentioned elsewhere; I know there is the `when()` function, but the implementation of that looks different.

**Comment by moodymudskipper** [comment]
Here's a quick way to do it in case you need it now (only tested on your example) : 

```
selectively <- function(fun, .p) {
  .p <- purrr::as_mapper(.p)
  function(...) {
    data <- ..1
    ind <- .p(data)
    if(length(ind)) data[ind] <-  eval(rlang::expr(fun(data[ind], !!!list(...)[-1])))
    data
  }
}      

tibble(number) %>% 
  mutate(ten_times_number = map_dbl(number, selectively(times_ten, 
                                                        .p = is_more_than_two)))

# # A tibble: 5 x 2
# number ten_times_number
#    <int>            <dbl>
# 1      1                1
# 2      2                2
# 3      3               30
# 4      4               40
# 5      5               50
```

**Comment by hadley** [comment]
This is fairly simple to implement:

``` r
library(purrr)
selectively <- function(condition, true, false = identity) {
  condition <- rlang::as_function(condition)
  true <- rlang::as_function(true)
  false <- rlang::as_function(false)
  
  function(x) {
    if (condition(x)) {
      true(x)
    } else {
      false(x)
    }
  }
}

number <- 1:5
map_dbl(number, selectively(~ .x > 2, ~ .x * 10))
#> [1]  1  2 30 40 50
```

<sup>Created on 2022-08-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

But it feels a bit too special case for purrr. I think we want to be fairly careful adding new adverbs, because it's not a terribly natural style of programming in R.

**Comment by hadley** [comment]
i.e. I don't see a big win over just writing the function yourself:

``` r
my_fun <- function(x) {
  if (x > 2) {
    x * 10
  } else {
    x
  }
}

purrr::map_dbl(1:5, my_fun)
#> [1]  1  2 30 40 50
```

<sup>Created on 2022-08-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
