### ISSUE TITLE
Document how to map on all combinations

### ISSUE THREAD

**Issue by davidsjoberg** [tidyverse/purrr#660]
Hi,

I was struggling to explain to co-worker why `map2` does not work like a double for loop. Wouldn't it be handy to combine some `purrr` functions to make all possible combinations map function. I couldn't find a way to this using standard `purrr` syntax. My take:

``` r
library(tidyverse)
library(glue)

combo <- function(.l, .f, ...){
  .l <- .l %>% 
    set_tidy_names(quiet = T) %>% 
    cross_df()
  
  pmap(.l, .f, ...)
}

# lists with different lengths
fruits <- fruit[c(19, 37)]
dessert <- c("cupcake", "pie")
person <- starwars$name[c(1, 4, 10)]

# lists into combo
combo(list(fruits, dessert, person),
      ~glue("I want {..1} {..2}, {..3}!"))
#> [[1]]
#> I want cloudberry cupcake, Luke Skywalker!
#> 
#> [[2]]
#> I want honeydew cupcake, Luke Skywalker!
#> 
#> [[3]]
#> I want cloudberry pie, Luke Skywalker!
#> 
#> [[4]]
#> I want honeydew pie, Luke Skywalker!
#> 
#> [[5]]
#> I want cloudberry cupcake, Darth Vader!
#> 
#> [[6]]
#> I want honeydew cupcake, Darth Vader!
#> 
#> [[7]]
#> I want cloudberry pie, Darth Vader!
#> 
#> [[8]]
#> I want honeydew pie, Darth Vader!
#> 
#> [[9]]
#> I want cloudberry cupcake, Obi-Wan Kenobi!
#> 
#> [[10]]
#> I want honeydew cupcake, Obi-Wan Kenobi!
#> 
#> [[11]]
#> I want cloudberry pie, Obi-Wan Kenobi!
#> 
#> [[12]]
#> I want honeydew pie, Obi-Wan Kenobi!
```

<sup>Created on 2019-03-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by rcorty** [comment]
I also couldn't figure out how to do this in a natural way.

**Comment by jennybc** [comment]
I feel like the existing functions in the tidy verse + glue come together so nicely to do this already that I question the need to add anything.

``` r
library(tidyverse)
library(glue)
#> 
#> Attaching package: 'glue'
#> The following object is masked from 'package:dplyr':
#> 
#>     collapse

# lists with different lengths
fruits <- fruit[c(19, 37)]
dessert <- c("cupcake", "pie")
person <- starwars$name[c(1, 4, 10)]

lst(fruits, dessert, person) %>% 
  cross_df() %>% 
  glue_data("I want {fruits}, {dessert}, {person}!")
#> I want cloudberry, cupcake, Luke Skywalker!
#> I want honeydew, cupcake, Luke Skywalker!
#> I want cloudberry, pie, Luke Skywalker!
#> I want honeydew, pie, Luke Skywalker!
#> I want cloudberry, cupcake, Darth Vader!
#> I want honeydew, cupcake, Darth Vader!
#> I want cloudberry, pie, Darth Vader!
#> I want honeydew, pie, Darth Vader!
#> I want cloudberry, cupcake, Obi-Wan Kenobi!
#> I want honeydew, cupcake, Obi-Wan Kenobi!
#> I want cloudberry, pie, Obi-Wan Kenobi!
#> I want honeydew, pie, Obi-Wan Kenobi!
```

<sup>Created on 2019-04-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by davidsjoberg** [comment]
Thanks, that's a much nicer solution to my example!

However, my main issue was using `map` functions over all possible combinations of lists/vectors in general. The combo of `lst`, `cross_df` and `pmap` works great, but it has an abstract syntax.

Understanding how `pmap` works and to find a function that constructs a data frame with correct structure is more advanced than the question implies: applying a function over all combinations of inputs / double for-loop in purr.

**Comment by rcorty** [comment]
The code Jenny posted is the way to apply a function to all combos of input.  I don’t think you’re going to find anything simpler.

**Comment by davidsjoberg** [comment]
Could be the case :) Maybe I was explaining it badly in when I taught newcomers to R. Thanks for your answers! Keep up the great work with tidyverse and purrr!

**Comment by jennybc** [comment]
> double for-loop ... Maybe I was explaining it badly in when I taught newcomers to R

I think this example really highlights something that I would embrace when teaching newcomers: often you get a solution that's easier to digest and extend later by expressing the complexity explicitly in a data structure (vs in logic, e.g. those nested `for` loops). R is, after all, a very data-focused and functional language.

I think the explicit formation of that data frame, which you can inspect, before figuring out how to tackle the "one string per row" part, is great for newcomers. In contrast, if you develop the "nested `for` loop" mentality, this object never even exists and you just have to imagine the state of the world in the innermost part of your loop.

**Comment by davidsjoberg** [comment]
I'll take your word for it! And thank you for you elebaration about education. There is a fine balance between having functions that do a lot for you (for free) and deeper understanding of how functions work, especially in corporate training when time is scarse. However, I agree that explicit is usually better than implicit! I'll keep that in mind next time :)

**Comment by lionel-** [comment]
We're deprecating `cross()` and `cross_df()` but it'd be nice to document this pattern with `tidyr::expand_grid()`.

**Comment by jennybc** [comment]
Today's issue triage notifications made me re-read this thread and #763, which has overlap with this.

Could this become a vignette? It feels like too much to cram into the docs for `tidyr::expand_grid()`. That would also only be found by people who already have the idea of making that data frame in the first place.

I am being self-congratulatory but it feels like this would be a good start to such a vignette (quoting from just above)

> Often you get a solution that's easier to digest and extend later by expressing the complexity explicitly in a data structure (vs in logic, e.g. those nested for loops). R is, after all, a very data-focused and functional language.
>
> I think the explicit formation of that data frame, which you can inspect, before figuring out how to tackle the "one string per row" part, is great for newcomers. In contrast, if you develop the "nested for loop" mentality, this object never even exists and you just have to imagine the state of the world in the innermost part of your loop.

**Comment by lionel-** [comment]
If there is enough content for a vignette that would be great. Otherwise it could be a FAQ page.

**Comment by janithwanni** [comment]
Is this issue open to be taken up for solving? I had faced this same issue recently and would like to write a vignette for this problem.

**Comment by hadley** [comment]
I now think this is out of scope for purrrr, since it falls an the documentation space that lies in between multiple packages. We don't currently have a good home for such docs, but @batpigandme is working on it.
