### ISSUE TITLE
pmap transposing list of tibbles

### ISSUE THREAD

**Issue by jhrcook** [tidyverse/purrr#665]
Hello,

I have found a very strange problem where using `pmap` on a list of 3-1x4 tibbles is "transposed" into a list of 4 lists of length 3. 

```r
library(tidyverse)

# prints the input
print_input <- function(...) {
    vals <- unlist(rlang::list2(...))
    print(vals)
    return(NULL)
}

# make a tibble with a column of 1x4 tibbles
single_tib <- tibble(A=1, B=2, C=3, D=4)
main_tib <- tibble(grp = c("ABC", "DEF", "GHI"),
                   tibs = list(single_tib, single_tib, single_tib))

# 'map' works as expected
main_tib %>%
    mutate(col_a = purrr::map(tibs, print_input))
#> A B C D
#> 1 2 3 4
#> A B C D
#> 1 2 3 4
#> A B C D
#> 1 2 3 4

# 'pmap' transposes the input
main_tib %>%
    mutate(col_a = purrr::pmap(tibs, print_input))
#> [1] 1 1 1
#> [1] 2 2 2
#> [1] 3 3 3
#> [1] 4 4 4
```

Hopefully someone can shed some light on why this is happening?

Thank you,
Josh Cook

**Comment by batpigandme** [comment]
From the [`pmap()`](https://purrr.tidyverse.org/reference/map2.html) docs:

> `pmap()` and `pwalk()` allow you to provide any number of arguments in a list. Note that a data frame is a very important special case, in which case `pmap()` and `pwalk()` apply the function `.f` to each row. 

I think you might have two sets of semantics working here. In the `mutate()` call, you're working column-wise, as you usually do, but `pmap()` is applying the function along the list column that you've specified (which each has length 4). 

This doesn't fix it, but I'm getting slightly different results to the ones you are (I've also added a `pmap()` directly over the `tibs` column, so you can see what that output looks like):
``` r
library(tidyverse)

# prints the input
print_input <- function(...) {
  vals <- unlist(rlang::list2(...))
  print(vals)
  return(NULL)
}

# make a tibble with a column of 1x4 tibbles
single_tib <- tibble(A=1, B=2, C=3, D=4)
main_tib <- tibble(grp = c("ABC", "DEF", "GHI"),
                   tibs = list(single_tib, single_tib, single_tib))

# 'map' works as expected
main_tib %>%
  mutate(col_a = purrr::map(tibs, print_input))
#> A B C D 
#> 1 2 3 4 
#> A B C D 
#> 1 2 3 4 
#> A B C D 
#> 1 2 3 4
#> # A tibble: 3 x 3
#>   grp   tibs             col_a 
#>   <chr> <list>           <list>
#> 1 ABC   <tibble [1 × 4]> <NULL>
#> 2 DEF   <tibble [1 × 4]> <NULL>
#> 3 GHI   <tibble [1 × 4]> <NULL>

# 'pmap' transposes the input
main_tib %>%
  mutate(col_a = purrr::pmap(tibs, print_input))
#> [1] 1 1 1
#> [1] 2 2 2
#> [1] 3 3 3
#> [1] 4 4 4
#> Error: Column `col_a` must be length 3 (the number of rows) or one, not 4

purrr::pmap(main_tib$tibs, print_input)
#> [1] 1 1 1
#> [1] 2 2 2
#> [1] 3 3 3
#> [1] 4 4 4
#> $A
#> NULL
#> 
#> $B
#> NULL
#> 
#> $C
#> NULL
#> 
#> $D
#> NULL
```

<sup>Created on 2019-04-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by lionel-** [comment]
Thanks for the troubleshooting @batpigandme
