### ISSUE TITLE
Function request: safely for walk varients 

### ISSUE THREAD

**Issue by AHoerner** [tidyverse/purrr#666]
I am trying to write a function to apply an arbitrary function (subject to a (data, ...) structure for its arguments, with data coercible to a data frame) to a set of files which are read from files, modified by the function, and then written back to files. This rather awkward construction is because many of these files are quite large -- collectively more than 40 GB -- so I can not hold all of them in memory at once. In addition, even fairly straightforward operations can be quite time consuming. So if my function bombs for some reason, I want a record of how and why and which one, but I do not want the whole sequence of files and computations to crash.

As I understand them, the current set of purrr analogs to try() -- safely(), possibly(), & quietly() -- all produce the complete output from the various purrr iteration functions as a single list object. This will I think often be inappropriate for long-running jobs that produce large objects or very large numbers of objects as output. It would be nice to have the informative "output, messages, warnings" structure of quietly() available for the walk family of functions that do not naturally reduce their output to a single object. Perhaps with an additional output for the iteration number or, for the case of a named input list, the iteration name, to assist in matching the errors with the relevant results.

**Comment by lionel-** [comment]
Perhaps you could just write a custom adverb that returns `NULL` when there was no error, and then `compact()` after `map()`?

On-the-fly filtering doesn't fit the `walk()` family I think, and is generally out of scope for purrr. It is more relevant to a package like https://github.com/lionel-/flowery.

**Comment by AHoerner** [comment]
I don't think this is correct. The issue is that walk functions, unlike map functions, do not return a single object, and that is why you use them instead of a map function. Walk functions return, as side effects, a bunch of objects that I am saving, or printing or whatever. But the safely, etc., functions take all those objects and bundle them back together into one big object. That is fine for the map functions that are already doing that -- safely does not make big objects appreciably bigger.  But one reason to use walk is precisely to avoid this bundling process, and safely does not need to impose it, and it does not make sense for it to do so. 

I also think that flowery, like !!, is a very cool computer science thing that people who are not primarily programmers will regard as additional mental load relative to the current connection approach. But everybody who uses purrr uses walk. Try your flowery documentation on some R users who are not programmers and see how many of them understand it after one read-through. I'm not saying it is not worth doing. I think most of the high-level programmers in R took the whole quasi-quotation thing into their hearts and use it effectively, and I'm sure that group will only grow with time. But that is a minority of R users, while walk/safely should be available to everybody.

**Comment by lionel-** [comment]
`walk()` is a wrapper around `for()`, the caller is entirely responsible for the side effects. It wouldn't be appropriate for a walk variant to save part of the outputs.

> Try your flowery documentation on some R users who are not programmers

This does not make sense because flowery is an experimental package. In any case this isn't about flowery, the point is that filtering maps are a problem domain on their own and as such are probably out of scope for purrr. The same way that rolling maps are now taken care of in the slide package.

**Comment by AHoerner** [comment]
We seem to be talking past each other and I am not sure why. Walk
repeatedly calls the user-defined function to produce side effects, whether
they are saved files or plots or whatever. Walk does not save them. Walk
does not combine them. But safely combines the outputs of the user-supplied
function and any error messages into a list, a single r object, as big as
all the output objects combined. A walk-appropriate safely would just have
error messages and success messages, with some name or number index so you
know which response goes with which object. A safely version appropriate to
walk would keep the part where it  saves the error messages and the part
where it goes to the next one instead of crashing, but drop the part where
it combines all of the supposedly side-effect outputs into a list.

I was using walk with a list of file names and a function that read these
gigundous census files, modified each one and saved it, but would crash on
certain files where the file wasn't structured in quite the way I expected.
That is the sort of case safely and its siblings were made for. And walk
let me do that with a large number of big files, one at a time. But I
finally had to run those files by hand, one at a time, because running them
without safely kept crashing on individual problematic files, and running
them with safely _always_ crashed because even though it properly skipped
over the problem files, the combined object was like 80 gigs. I could not
get the intended benefits of safely because of the mismatch between the
provided safely output (one object) and the desired walk output (many
objects).

Walk produces both error messages and the wrapped function outputs as side
effects. Whether there are errors or not, walk normally produces a side
effect object, action, or message message for each time through the loop,
and no list. But safely (and quietly and possibly) grab all those side
effects -- not just the error messages -- and combines them into a list,
which eliminates the distinctive feature of walk. You might as well use
map, if you are going to put all the outputs into a list.

frustrating.

**Comment by lionel-** [comment]
A `walk()` variant should not capture any output.

Maybe we could have logging adverbs, one of which would install calling handlers to save the errors in a given object. Since the log object would be modified by reference, R6 might be best. Not sure this fits in purrr, but this seems similar in scope to the `insistently()` adverb and the rate limiters.

**Comment by hadley** [comment]
I think a pragmatic way to solve this might be to be provide some adverb had logical flags for capturing results, output, messages, warnings, error, .... Then for your use case instead of `safely(f)`, you'd call `something(f, error = TRUE)`

**Comment by lionel-** [comment]
It seems there's a trade off between an output adverb which will preserve locations and names of the input and a logging adverb which loses the relationship between the output and the input.

**Comment by hadley** [comment]
Given that this request hasn't come up again, and there's a fairly simple work around (modify your function to return `NULL`), and that we're trying to make purrr simpler in order to make it more maintainable, I'm going to close this issue.
