### ISSUE TITLE
Guidelines/best practices on exporting adverb-wrapped functions from packages

### ISSUE THREAD

**Issue by sheffe** [tidyverse/purrr#668]
`insistently()` and `safely()` have been lifesavers for my team, particularly in solving problems where low failure rates over large-scale API call queues and read/write operations would break long-running processes. Interacting with AWS S3 from R is much easier now.

Are there any recommendations/best practices for including adverb-wrapped functions in packages? Since the release of `insistently()` I’ve never called (eg) the `aws.s3::put_object()` function directly. Every script starts with creating wrappers for `insist_*`. I’d like to move the wrapped functions to an internal package, and maybe propose to include an insistent option in the main package. However, I haven’t seen any packages that export safe_* or insistent_* function variants to date, and that’s a good sign I'm planning to do something without full understanding of the side effects.

(First time filing an issue here -- thank you! `purrr` is the single largest productivity boost I've had in >10 years of writing R code...)

**Comment by moodymudskipper** [comment]
I have no authority on good practices but maybe if you're going to package it it would be nice to keep all arguments (as purrr adverbs return a functions with `...` formal only), and do something like this (untested) : 

```
#' insistent_put_object
#'
#' @inheritParams aws.s3::put_object
#' @inheritParams purrr::insistently
#' @export
insistent_put_object<- function (
  file, 
  object, 
  bucket, 
  multipart = FALSE, 
  acl = c("private", 
          "public-read", "public-read-write", "aws-exec-read", 
          "authenticated-read", "bucket-owner-read", "bucket-owner-full-control"), 
  headers = list(), 
  ...,
  rate = rate_backoff(),
  quiet = TRUE) {
  
  if(missing(object)) object = file
  purrr::insistently(inaws.s3::put_object, ate, quiet)(file, object, bucket, multipart, acl, headers, ...)
}
```

More generally I would say that you're good to go with : 

* create a function with arguments from both your input function and your adverb
* deal with missingness with tests or by changing defaults if it's acceptable
* if it's a quoting function, do a bit of *rlang* or `substitute` magic (not relevant here I think).
* call adverb and manufactured function, don't forget to name args that come after `...` (or name all)
* if it's a function with side effects you might want to use `eval.parent` (not relevant here either afaik)
* maybe include both functions in @seealso and a note in the description

**Comment by lionel-** [comment]
The main thing is to avoid assigning the functions in your namespace at build time. If you assign at build time, this might cause issues when purrr is updated and your package isn't. The functions you have created in the package will contain the old source code, and might even refer to functions that no longer exist in the purrr namespace.

To assign the functions at build time, do it from the `.onLoad()` hook of your package:

```r
#' My function
#' @export
insist_my_function <- function(...) "dummy"

my_function <- function(...) {
  # Actual implementation
}

.onLoad <- function(lib, pkg) {
  my_function <<- purrr::insistently(my_function)
}
```

**Comment by sheffe** [comment]
Thank you, this is very clear! Using .onLoad for patterns like this is a useful concept in general.

**Comment by lawu-mdsol** [comment]
@lionel- In your snippet above, why do you define `insist_my_function` twice?

Also, if I wanted to add additional functionality to the insistently version of a function, e.g. a tryCatch that logs an error, is it still recommended to define this function in the `.onLoad()` hook? Something like:

```
.onLoad <- function(lib, pkg) {
  insist_my_function <<- tryCatch({purrr::insistently(my_function)
}
```

**Comment by lionel-** [comment]
> why do you define insist_my_function twice?

The dummy definition is a place for the roxygen2 documentation. It also allows some rudimentary static analysis, if only by the readers of the code.

> Also, if I wanted to add additional functionality to the insistently version of a function, e.g. a tryCatch that logs an error, is it still recommended to define this function in the .onLoad() hook? Something like:

You can put your wrapper outside of `.onLoad()`, only the `insistently()` call needs to be done at load time. You can equivalently call `insistently()` inside of your wrapper instead of in `.onLoad()`, if it's only used there. Then the insistent version will be created each time your wrapper is run instead of only once per session. Both approaches will work correctly, the main thing is not to call `insistently()` at build time.

**Comment by lawu-mdsol** [comment]
Thanks @lionel-, that's very helpful.
