### ISSUE TITLE
Access row as a list or vector in pmap formulas

### ISSUE THREAD

**Issue by lahvak** [tidyverse/purrr#670]
This is either a feature request or a documentation fix request.  It is possible similar functionality already exists, but I have not been able to find any information about it.

I would like to map a formula over rows of a data frame, where the formula consumes the rows as lists or vectors.  For example, currently I can do this:

```r
df <- data.frame(x = rnorm(20, mean=5, sd = 7),
                           y = rnorm(20, mean=13, sd = 2),
                           z = rnorm(20, mean=8, rnowm = 5))

expected <- c(5, 13, 8)

pmap_dbl(df, ~sum((c(..1, ..2, ..3) - expected)^2/expected)) 
```
That works fine for 3 columns like in the example, but it will become really unwieldy with a 10 or even 20 columns.  I would like to be able to do something like

```r
pmap_dbl(df, ~sum((.row - expected)^2/expected))
```
where the `.row` would stand for `c(..1, ..2, ... as many items as needed to have the whole row)`,

An example why I think this would be helpful can be found at https://space.lahvak.space/2019/04/14/tidyverse-rows-as-vectors/

Again, perhaps this is already possible, and I was just unable to find out how to do it.

**Comment by cderv** [comment]
Hi, 

this may not be well known but you have in purrr some function that help you compose new ones to lift their domain: the `lift_*` family. 
Those function can be leverage to use in `pmap_*` functions to takes dots and works on several argument. 
In your example, you can do that: 
1. Create a function that works on vector
2. Leverage the `lift_vd()` function so this function works with dots arguments.

``` r
# 1. create a function that works with a vector
my_fun <- function(vec, expected = c(5, 13, 8)) {
  sum((vec - expected)^2/expected)
}

# your example
df <- data.frame(x = rnorm(20, mean=5, sd = 7),
                 y = rnorm(20, mean=13, sd = 2),
                 z = rnorm(20, mean=8, sd = 5))

expected <- c(5, 13, 8)

# makes this function to work with dots to use in pmap_dbl
# using lift_vd(). provide default arg expected to match your calculation.
purrr::pmap_dbl(df, purrr::lift_vd(my_fun, expected = expected)) 
#>  [1] 24.7118904  7.3488294 15.6941519  4.0707958  4.1639817  0.7434461
#>  [7]  1.2086112  8.9067403  5.8822233  5.4236643  1.9520933 24.7351863
#> [13] 17.5709846  4.9640579  0.3442724 12.4197407  3.2570185  2.3143054
#> [19]  5.3077868  9.5703512

# it work also with 4 columns
df <- data.frame(
  w = rnorm(20, mean=3, sd = 6),
  x = rnorm(20, mean=5, sd = 7),
  y = rnorm(20, mean=13, sd = 2),
  z = rnorm(20, mean=8, sd = 5)
)

expected <- c(3, 5, 13, 8)
purrr::pmap_dbl(df, purrr::lift_vd(my_fun, expected = expected))
#>  [1] 20.292318 11.671653 18.171534 80.040796  3.972051  2.131301 68.935173
#>  [8] 10.706261 41.431165 78.219363 16.180529 28.083015  8.345527  8.044456
#> [15] 53.382100 69.653737  7.904755  7.859222 19.109326 35.099628
```

you can also create your own function that takes `…`. (what `lift_vd()` does for you)

``` r
my_fun2 <- function(..., expected = c(5, 13, 8)) {
  # get the ... in a list
  dot <- rlang::dots_list(...)
  # simply as vector
  as_vec <- purrr::simplify(dot)
  # calculate on the vector
  sum((as_vec - expected)^2/expected)
}
# apply easily on the df with four columns
purrr::pmap_dbl(df, my_fun2, expected = expected)
#>  [1] 20.292318 11.671653 18.171534 80.040796  3.972051  2.131301 68.935173
#>  [8] 10.706261 41.431165 78.219363 16.180529 28.083015  8.345527  8.044456
#> [15] 53.382100 69.653737  7.904755  7.859222 19.109326 35.099628
```

<sup>Created on 2019-04-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

This may not be well known, documented and advertise. There is one example of using `lift_ld` with `pmap` in [the `lift_*` family help page](https://purrr.tidyverse.org/reference/lift.html)

hope it helps !

**Comment by lahvak** [comment]
@cderv  Thanks, I did not know about the `lift_` family at all!  This is really useful.

In this case, however, it seems that the solution is actually really simple, though.  Instead of the he `.row` syntax that I was suggesting, one can use `c(...)`.  I thin I tried to use jut `...` which did nit work.  This works:

``` r
library(tidyverse)
df <- data.frame(x = rnorm(20, mean=5, sd = 7),
                 y = rnorm(20, mean=13, sd = 2),
                 z = rnorm(20, mean=8, sd = 5))

expected <- c(5, 13, 8)

pmap_dbl(df, ~sum((c(..1, ..2, ..3) - expected)^2/expected)) 
#>  [1]  8.383351  6.427798 11.507360 15.890579  1.743626 28.996590 27.620684
#>  [8] 15.859395 41.748707  7.393365  1.083350  4.216655  1.661820  5.264918
#> [15]  5.928870  7.995829  1.352299 14.596915 11.892104 10.448865

pmap_dbl(df, ~sum((c(...) - expected)^2/expected)) 
#>  [1]  8.383351  6.427798 11.507360 15.890579  1.743626 28.996590 27.620684
#>  [8] 15.859395 41.748707  7.393365  1.083350  4.216655  1.661820  5.264918
#> [15]  5.928870  7.995829  1.352299 14.596915 11.892104 10.448865
```

<sup>Created on 2019-04-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
