### ISSUE TITLE
Add as_mapper.quosure()?

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/purrr#672]
To support APIs that take a mapping expression and pass it on to purrr.

The example below attemts to implement a tidy interface around the mutate-map idiom. For some reason I can't work out an implementation that uses the existing `as_mapper.default()` .

I'm aware that this interface requires explicit quoting of all non-data objects, but this restriction doesn't feel too bad.

@lionel-: Is there a better existing solution I'm missing?

``` r
library(tidyverse)

as_mapper_quosure <- function(quo) {
  expr <- rlang::quo_get_expr(quo)

  rlang::new_function(alist(... = , . = ..1, .x = ..1, .y = ..2), expr)
}

mutate_map_dbl <- function(.data, col, ...) {
  col <- rlang::enexpr(col)

  quos <- rlang::enquos(..., .named = TRUE)
  stopifnot(length(quos) == 1)

  new_column <- rlang::sym(names(quos))

  expr <- as_mapper_quosure(quos[[1]])

  .data %>%
    mutate(!!new_column := map_dbl(!!col, expr))
}

iris %>%
  nest(-Species) %>%
  mutate_map_dbl(data, mean_petal_width = mean(.$Petal.Width))
#> # A tibble: 3 x 3
#>   Species    data              mean_petal_width
#>   <fct>      <list>                       <dbl>
#> 1 setosa     <tibble [50 × 4]>            0.246
#> 2 versicolor <tibble [50 × 4]>            1.33 
#> 3 virginica  <tibble [50 × 4]>            2.03
```

<sup>Created on 2019-05-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by lionel-** [comment]
If we were to add a working method it should probably call `eval_tidy()` because the quosure might contain nested quosures. But I think I'd rather make it an error until we discover this is more generally needed.

**Comment by lionel-** [comment]
Thanks for the suggestion. This would probably not be very useful, and this confuses me a bit. Also it'd be weird to have data-masking expressions using the same function signature as formula lambdas.
