### ISSUE TITLE
imap2_*, ipmap_* possible?

### ISSUE THREAD

**Issue by dan-reznik** [tidyverse/purrr#678]
these would be nice additions... for imap2_* .z could be the index, but for ipmap_* you could say, use ..999 for example, or make it be ..1 on both cases (breaking compatibility w/ imap, but that's ok)

**Comment by lionel-** [comment]
I'm not sure I like the multiplication of functions this would imply. In any case a `ipmap()` function would likely be too cryptic.

**Comment by lionel-** [comment]
Thanks for the suggestion! It might not be worth making the API more complex. Let's keep thinking about it.
