### ISSUE TITLE
`map2` throws empy list when `.y` argument is NULL

### ISSUE THREAD

**Issue by joelgombin** [tidyverse/purrr#679]
See this reprex:

```r
library(purrr)
alist <- list("bla") 
alist %>% 
  map_chr(~ .)
#> [1] "bla"
alist %>% 
  map2(.y = NULL, ~ .x)
#> list()
alist %>% 
  map2(.y = alist, ~ .x)
#> [[1]]
#> [1] "bla"
```

This may be related to #199 ?

**Comment by lionel-** [comment]
I think we'd now make it an error rather than recycling to length zero. We now generally treat `NULL` as an absence of argument rather than as an empty vector. cc @hadley

**Comment by hadley** [comment]
Agreed

**Comment by hadley** [comment]
Hmmm, I could argue this either way for `map2()`. In any case, I think we should just apply the standard rules (i.e. #878) and see what falls out.
