### ISSUE TITLE
improved print method for class `purrr_function_partial` 

### ISSUE THREAD

**Issue by lorenzwalthert** [tidyverse/purrr#681]
Currently, the printing method does print the pre-filled arguments, but one cannot see which arguments were not pre-filled and may nevertheless apply (i.e. default arguments) or which are missing:

``` r
f <- function(a = 44, b = NA, x, y) NULL

(f_with_x_prefilled <- purrr::partial(f, x = 3))
#> <partialised>
#> function (...) 
#> f(x = 3, ...)
```

<sup>Created on 2019-06-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I think a more verbose printing method could be helpful when using many arguments, some with defaults, some pre-filled. Like this: 

```r
#> <partialised f()>
#> pre-filled     : x = 3
#> active defaults: a = 44, b = NA 
#> undeclared     : y
#> dots           : [none]
```

Would you consider adding such a feature?

**Comment by lionel-** [comment]
Probably not in this form because it is non-standard and probably confusing.

**Comment by lorenzwalthert** [comment]
Ok. I see it's quite different from the status quo. What about extending the current print method like this?

```r
#> <partialised>
#> function (a = 44, b y) 
#> f(a, b, x = 3, y)
```

This would not be such a dramatic change to the current implementation.

**Comment by lionel-** [comment]
I think I've considered this but ran into issues that I can't remember. This would be a nice to have if the argument passing works reliably, and the partialised function can still `substitute()` or `enquo()` its arguments correctly.

**Comment by lionel-** [comment]
We can't reuse the formals of the function without breaking support for NSE functions. I have added an explanation in the documentation:

```r
#' `partial()` creates a function that takes `...` arguments. Unlike
#' [compose()] and other function operators like [negate()], it
#' doesn't reuse the function signature of `.f`. This is because
#' `partial()` explicitly supports NSE functions that use
#' `substitute()` on their arguments. The only way to support those is
#' to forward arguments through dots.
```
