### ISSUE TITLE
Unquote-splicing magrittr pronoun in `exec()` doesn’t work

### ISSUE THREAD

**Issue by huftis** [tidyverse/purrr#686]
The `exec()` function is supposed to support quasiquotation, including unquote-splicing. It works if the argument that is unquote-spliced is a normal variable, but if it’s a ‘dot’ object in a pipe, an error message is shown instead. Reprex:

```r
library(purrr)
x = list(1:3, 5:6)
exec(expand.grid, !!!x) # This works
#>   Var1 Var2
#> 1    1    5
#> 2    2    5
#> 3    3    5
#> 4    1    6
#> 5    2    6
#> 6    3    6
x %>% exec(expand.grid, !!!.) # This results in error
#> Can't create call to non-callable object
```

**Comment by lionel-** [comment]
This will be solved by https://github.com/tidyverse/magrittr/issues/191

**Comment by lionel-** [comment]
There is a workaround: `x %>% { exec(expand.grid, !!!.) }`

**Comment by lionel-** [comment]
Closing as this will be taken care of in the next version of magrittr.
