### ISSUE TITLE
dplyr dependency 

### ISSUE THREAD

**Issue by CorradoLanera** [tidyverse/purrr#692]
I'm writing a package which uses `purrr::imap_dfc()` in a test for a function. I have imported **purrr** because I used other functions from it elsewhere in the package. On the other hand, for this package, I don't "need" any **dplyr**'s functions.

Locally, neither **testthat** and **CMD check** return any errors.

On the other hand, I got an error on Travis because of **dplyr**:
```
abort("`map2_dfc()` requires dplyr")
```

This happened because **dplyr** is not a dependency of my package (and I think it shouldn't, maybe it can be suggested, even if there isn't any explicit call to any **dplyr**'s functions anywhere: it is used only indirectly, by **purrr::imap_dfc()**, in a test).

I read some other related issues (#35, #328), but I didn't understand the policy clearly, nor if you are in the process of removing all the **dplyr** dependencies from **purrr**, and my issue is only temporary.

So, what are your current suggestions to fix it? Should I have to declare **dplyr** under imports?

**Comment by lionel-** [comment]
If you'd like to use `_df` functions you need to add dplyr to `Imports`. We'll change this by a vctrs dependency in the next release.

**Comment by CorradoLanera** [comment]
Ok, thank you!
