### ISSUE TITLE
Feature request: select autofill after unnesting

### ISSUE THREAD

**Issue by petyaracz** [tidyverse/purrr#698]
I would like to have RStudio autofill with select() to work on input that was piped through an unnest().

In RStudio, `select()`allows for autofill for colnames. Handy when I have a zillion columns.

```{r }
iris %>% 
  select(
    Se[I press tab, Sepal.Length/Sepal.Width come up]
  )
```

Currently, this does not work for an unnested dataframe if the unnest happens in the same series of pipes.

```{r }

nested_iris = iris %>% 
  group_by(Species) %>% 
  nest()

nested_iris %>% 
  unnest() %>% 
  select(
    Se[I press tab, nothing comes up]
  )

```
 
This feature already exists for mutate(), compare:

```{r }


iris = iris %>% 
  mutate(
    new_column = 'new_column'
  ) %>% 
  select(
    new_c[I press tab, new column comes up]
  )


```

**Comment by cderv** [comment]
I wonder if this should be open in [RStudio Repo](https://github.com/rstudio/rstudio) as a feature request as it concerns RStudio IDE and not purrr directly. 🤔

**Comment by jennybc** [comment]
Agree with @cderv re: where this would have to be implemented. Even if it had to do with a package, it would be tidyr (or dplyr) not purrr. But yeah this is an IDE matter. And, I suspect, unlikely to happen because it's considerably harder than the `select()` case.
