### ISSUE TITLE
Handle MTS with map and lapply

### ISSUE THREAD

**Issue by edoardo-oliveri-sdg** [tidyverse/purrr#699]
`map` handles `mts` objects differently from `lapply`. 
Is it on purpose?

```r
require(purrr)

class(EuStockMarkets)
#> [1] "mts"    "ts"     "matrix"

l <- lapply(EuStockMarkets, class)
m <- map(EuStockMarkets, class)

unlist(l)
#>  DAX  SMI  CAC FTSE 
#> "ts" "ts" "ts" "ts" 

table(unlist(m))
#> numeric 
#>    7440 
```

Personally, I find `lapply` handling more useful. Arguable I guess.

Details:
```r
R.version$version.string
# [1] "R version 3.5.2 (2018-12-20)"
packageVersion("purrr")
# [1] ‘0.3.2’

**Comment by cderv** [comment]
FWIW, I get exactly the same with lapply and map
``` r
library(purrr)
packageVersion("purrr")
#> [1] '0.3.2'
class(EuStockMarkets)
#> [1] "mts"    "ts"     "matrix"

l <- lapply(EuStockMarkets, class)
m <- map(EuStockMarkets, class)

str(l, list.len = 10)
#> List of 7440
#>  $ : chr "numeric"
#>  $ : chr "numeric"
#>  $ : chr "numeric"
#>  $ : chr "numeric"
#>  $ : chr "numeric"
#>  $ : chr "numeric"
#>  $ : chr "numeric"
#>  $ : chr "numeric"
#>  $ : chr "numeric"
#>  $ : chr "numeric"
#>   [list output truncated]
str(m, list.len = 10)
#> List of 7440
#>  $ : chr "numeric"
#>  $ : chr "numeric"
#>  $ : chr "numeric"
#>  $ : chr "numeric"
#>  $ : chr "numeric"
#>  $ : chr "numeric"
#>  $ : chr "numeric"
#>  $ : chr "numeric"
#>  $ : chr "numeric"
#>  $ : chr "numeric"
#>   [list output truncated]

identical(l, m)
#> [1] TRUE
identical(unlist(l), unlist(m))
#> [1] TRUE
table(unlist(l))
#> 
#> numeric 
#>    7440
table(unlist(m))
#> 
#> numeric 
#>    7440
```

<sup>Created on 2019-08-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I am on R 3.6.1 though - not sure it have some impacts

**Comment by edoardo-oliveri-sdg** [comment]
My bad... it happens if you have `forecast` attached.

```r
require(forecast)
require(purrr)
class(EuStockMarkets)
l <- lapply(EuStockMarkets, class)
m <- map(EuStockMarkets, class)


unlist(l)
table(unlist(m))
```
If it's not relevant, close it.

**Comment by cderv** [comment]
Oh it is relevant and the source of the behavior you see. 

When forecast is loaded, `zoo` is loaded and `zoo` has a `as.list.ts()` methods. The difference between `lapply` and `map` is that `lapply(X,...) ` calls a `as.list(X)` (see [source](https://github.com/wch/r-source/blob/635a211ecc1e695ad97085d1171cfa4e3067c929/src/library/base/R/lapply.R#L25)
```r
function (X, FUN, ...) 
{
  FUN <- match.fun(FUN)
  if (!is.vector(X) || is.object(X)) 
    X <- as.list(X)
  .Internal(lapply(X, FUN))
}
```
And `zoo:::as.list.ts` transform the input before the lapply, what `map` does not do. If you apply a `as.list` before the `map`, you get the correct result you want.

``` r
library(zoo)
#> 
#> Attachement du package : 'zoo'
#> The following objects are masked from 'package:base':
#> 
#>     as.Date, as.Date.numeric
packageVersion("zoo")
#> [1] '1.8.6'
library(purrr)
packageVersion("purrr")
#> [1] '0.3.2'
class(EuStockMarkets)
#> [1] "mts"    "ts"     "matrix"
l <- lapply(EuStockMarkets, class)
m <- map(EuStockMarkets, class)

identical(l, m)
#> [1] FALSE

# zoo:::as.list.ts transform the input data
str(EuStockMarkets, 1)
#>  Time-Series [1:1860, 1:4] from 1991 to 1999: 1629 1614 1607 1621 1618 ...
#>  - attr(*, "dimnames")=List of 2
str(as.list(EuStockMarkets), 1)
#> List of 4
#>  $ DAX : Time-Series [1:1860] from 1991 to 1999: 1629 1614 1607 1621 1618 ...
#>  $ SMI : Time-Series [1:1860] from 1991 to 1999: 1678 1688 1679 1684 1687 ...
#>  $ CAC : Time-Series [1:1860] from 1991 to 1999: 1773 1750 1718 1708 1723 ...
#>  $ FTSE: Time-Series [1:1860] from 1991 to 1999: 2444 2460 2448 2470 2485 ...

# map works as expected now - lapply does it internally without being explicit.
m <- map(as.list(EuStockMarkets), class)
identical(l, m)
#> [1] TRUE
unlist(l)
#>  DAX  SMI  CAC FTSE 
#> "ts" "ts" "ts" "ts"
unlist(m)
#>  DAX  SMI  CAC FTSE 
#> "ts" "ts" "ts" "ts"
table(unlist(m))
#> 
#> ts 
#>  4
```

<sup>Created on 2019-08-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I don't think that `purrr` should handle those time series cases. This is one of the advantage I see in purrr : to always do what it is suppose and not _internaly_ do something else. Now, I am not a time serie expert and maybe that is something `purrr` should handle. 

Hope it helps.

**Comment by lionel-** [comment]
Christophe is right, this is because of zoo.

The fact that loading zoo causes this is very bad:

- A package should only implement a method if it owns the class or the generic. zoo does not own the generic `as.list()` which belongs to `base::` nor the `ts` class which was introduced in `stats::`.

- `as.list()` should generally return a list as long as the input. This invariant should be observed: `length(as.list(x)) === length(x)`. The zoo method does not obey the invariant.
