### ISSUE TITLE
compose should propagate all arguments to all functions

### ISSUE THREAD

**Issue by vspinu** [tidyverse/purrr#705]
Currently composed function passes its arguments to the first function only. This is not very useful, nor particularly meaningful. There is no reason why first function should be special in this regard. 

IMO the signature of compose should be ... and it should propagate all arguments to each function. 

A more involved implementation could filter arguments passed to composed function to match the signature of each function but this might be an overkill.

``` r
library(purrr)
tt <- compose(function(x, a = 1, ...) list_modify(x, a = a),
              function(x, b = 1, ...) list_modify(x, b = b),
              .dir = "forward")
tt(list(), a = 2, b = 2)
#> $a
#> [1] 2
#> 
#> $b
#> [1] 1
```

<sup>Created on 2019-09-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
This was on purpose. This is useful because we get the full function signature in the resulting function. I don't find it very meaningful to forward dots to arbitrary functions, since it only works as a special case.

**Comment by vspinu** [comment]
Signature can be an union of individual signatures and filter the args per function. I doubt this is very difficult but would result in a powerful composition system. 

>  since it only works as a special case.

It's an important special case. How about checking if each function's signature has `...` and passing through all arguments if so?

**Comment by hadley** [comment]
I think unfortunately `compose()` is already quite complex so adding this is unlikely to be worth the effort. I think unlink other FP languages, `compose()` is considerably more complex and has to make more tradeoffs.
