### ISSUE TITLE
aggregate identically named items

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/purrr#708]
When converting from xml for instance we might end up with a list featuring duplicate names, and it's a bit painful to deal with with current tools (unless I'm missing something).

R is not well equipped to deal with duplicate names, the *tidyverse* likes it even less, either imposing name repair or just failing (e.g. `dplyr::mutate_all()`), so I think it would make sense to have a function to preprocess this type of data.

At first I thought it might be an additional feature of `purrr::compact()`, as its also reducing the length by handling "anomalies", but I'm not sure if it goes well with its current `.p` feature (it might also be more of a *tidyr¨* thing ? I wasn't sure).

In my idea the function would take : 
* a list (incl. data frame)  
* a `combine()` aggregation function to apply on sets of identically named elements
* a `unname` boolean to optionally unname the dots fed to `combine()`.

I think having different defaults for data frame and bare list makes sense so by default on a list we'd just wrap the identically named elements in a list, and on a data.frame we'd repair the names and pack the columns.

Please find below sample data and a function draft : 

``` r
test_list <-
  list(0,
       a= 1, 
       a =2,
       b = c(3:4), 
       b = (5:6),
       c = list(7,8), 
       c = list(9,10),
       y = 11,
       z= NULL,
       12)

test_df <- tibble::as_tibble(test_list[-c(1,9,10)],.name_repair = "minimal")

compact2 <- function(
  x, 
  combine = if(is.data.frame(x)) tibble::tibble else list, 
  unname = rlang::is_bare_list(x)){
  combine <- rlang::as_function(combine)
  nms <- rlang::names2(x)
  # logical indices of named duplicates
  dupes_lgl <- duplicated(nms) & nms != ""
  # unique non empty names
  dupe_nms <- unique(nms[dupes_lgl])
  # replace first instance by combined value
  for(nm in dupe_nms){
    # subset of unnamed elements
    x_nm <- x[names(x) == nm]
    if(unname)
      x_nm <- unname(x_nm)
    else
      x_nm <- tibble::repair_names(x_nm)
    x[[nm]] <- do.call(combine, x_nm)
  }
  # ditch other instances
  x[dupes_lgl] <- NULL
  x
}
  
compact2(test_list)
#> [[1]]
#> [1] 0
#> 
#> $a
#> $a[[1]]
#> [1] 1
#> 
#> $a[[2]]
#> [1] 2
#> 
#> 
#> $b
#> $b[[1]]
#> [1] 3 4
#> 
#> $b[[2]]
#> [1] 5 6
#> 
#> 
#> $c
#> $c[[1]]
#> $c[[1]][[1]]
#> [1] 7
#> 
#> $c[[1]][[2]]
#> [1] 8
#> 
#> 
#> $c[[2]]
#> $c[[2]][[1]]
#> [1] 9
#> 
#> $c[[2]][[2]]
#> [1] 10
#> 
#> 
#> 
#> $y
#> [1] 11
#> 
#> $z
#> NULL
#> 
#> [[7]]
#> [1] 12

compact2(test_list, c)
#> [[1]]
#> [1] 0
#> 
#> $a
#> [1] 1 2
#> 
#> $b
#> [1] 3 4 5 6
#> 
#> $c
#> $c[[1]]
#> [1] 7
#> 
#> $c[[2]]
#> [1] 8
#> 
#> $c[[3]]
#> [1] 9
#> 
#> $c[[4]]
#> [1] 10
#> 
#> 
#> $y
#> [1] 11
#> 
#> $z
#> NULL
#> 
#> [[7]]
#> [1] 12

compact2(test_list, ~sum(unlist(.)))
#> [[1]]
#> [1] 0
#> 
#> $a
#> [1] 1
#> 
#> $b
#> [1] 7
#> 
#> $c
#> [1] 15
#> 
#> $y
#> [1] 11
#> 
#> $z
#> NULL
#> 
#> [[7]]
#> [1] 12

compact2(test_df)
#> # A tibble: 2 x 4
#>     a$a   $a1   b$b   $b1 c$c       $c1           y
#>   <dbl> <dbl> <int> <int> <list>    <list>    <dbl>
#> 1     1     2     3     5 <dbl [1]> <dbl [1]>    11
#> 2     1     2     4     6 <dbl [1]> <dbl [1]>    11
```

<sup>Created on 2019-09-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
I think this function would be too specialised for purrr. Note that the next generation of flatten and squash functions will feature a `.name_spec` argument, as in `vctrs::vec_c()`.

**Comment by moodymudskipper** [comment]
A reciprocal function to `unsquash()` or `flatten()` could also solve the issue I guess.

With `repair_name` we're losing information, that we might keep partially in form of prefixes but this is not robust, and we're storing structured information in strings and it feels like we're breaking the data before fixing it.

This would be a somewhat tidy way using suffixes to solve the default data frame case :

```
nms <- names(test_df)
nms <- nms[duplicated(nms)]
args <- map(set_names(c("a","b","c")),~expr(starts_with(!!.)))
test_df %>% 
  repair_names %>% 
  pack(!!!args)
```

The default list case could be solved as follow :

```
nms       <- setdiff(allNames(test_list),"")
test_list[nms] <- tapply(test_list[nms] , nms, function(x) if (length(x) > 1) list(unname(x)) else x)
test_list[names(nms) %in% test_list][duplicated(nms)] <- NULL
```

**Comment by hadley** [comment]
This definitely feels too specialised for purrrr for me, especially given that since creating this issue we've put a lot of effort into better duplicate name handling across the tidyverse.
