### ISSUE TITLE
Catch up with git tags and releases

### ISSUE THREAD

**Issue by lorenzwalthert** [tidyverse/purrr#709]
There are [Github releases](https://github.com/tidyverse/purrr/releases) and git tags until 0.3.2. Any plan to catch up? Because I find it quite practical to install an older version of a package via remotes 
``` r
remote::install_github("tidverse/purrr@v0.4.0")
``` 

or similar and I think it's generally considered good practice.

**Comment by lionel-** [comment]
The last released version is 0.4.0.

**Comment by lionel-** [comment]
oops 0.3.2

**Comment by lorenzwalthert** [comment]
haha ups yes I also just messed with rlang versions :-)
