### ISSUE TITLE
Idea for a more specialised row split

### ISSUE THREAD

**Issue by Shians** [tidyverse/purrr#714]
I would like to see a specialised row split function for better compatibility with tidy data. The use case would be to set up some tasks in a data.frame and running `map_*` on it. For example

```r
library(purrr)

row_split <- function(x, name_by = NULL) {
    if (is.null(name_by)) {
        list_names <- rownames(x)
    } else {
        list_names <- x[[name_by]]
    }

    setNames(split(x, seq_len(nrow(x))), list_names)
}

tasks <- data.frame(
    task_id = paste0("task_", 1:3),
    par1 = LETTERS[1:3],
    par2 = 1:3
)

map_chr(
    row_split(tasks, name_by = "task_id"),
    function(x) { paste0(x$par1, x$par2) }
)
```

Does anyone think this would be useful? Would it be appropriate for the purrr package or any other tidyverse packages?

**Comment by jennybc** [comment]
I think what you are looking for may already exist in this family of functions: `dplyr::group_map()`, `group_modify()`, etc. Or, if you think not, it would be helpful to explain what the difference is.

**Comment by Shians** [comment]
Thanks for pointing me to `group_map()` Jenny, wouldn't have thought to look inside dplyr for that functionality.

I think the difference here is that the dplyr family of functions require a function that returns a data frame as arguments, whereas my proposal allows arbitrary return values and also enables the use of the richer expressions in purrr of `map_chr()`, `map_lgl()`, etc... 

Secretly this is a ploy to get something nice I can use with `parallel::mclapply()`.

**Comment by jennybc** [comment]
I'm still don't understand what `rowsplit()` does that `group_split()` cannot, with row number as `name_by`.

**Comment by Shians** [comment]
It can name the list elements by a column where `group_split()` cannot. It is less verbose than `group_split(rowwise(tasks))` and returns less complicated objects which take up significantly less space when printed out.

```r
> row_split(tasks, name_by = "task_id")
$task_1
  task_id par1 par2
1  task_1    A    1

$task_2
  task_id par1 par2
2  task_2    B    2

$task_3
  task_id par1 par2
3  task_3    C    3
```

```r
> group_split(rowwise(tasks))
[[1]]
Source: local data frame [1 x 3]
Groups: <by row>

# A tibble: 1 x 3
  task_id par1   par2
  <fct>   <fct> <int>
1 task_1  A         1

[[2]]
Source: local data frame [1 x 3]
Groups: <by row>

# A tibble: 1 x 3
  task_id par1   par2
  <fct>   <fct> <int>
1 task_2  B         2

[[3]]
Source: local data frame [1 x 3]
Groups: <by row>

# A tibble: 1 x 3
  task_id par1   par2
  <fct>   <fct> <int>
1 task_3  C         3

attr(,"ptype")
Source: local data frame [0 x 3]
Groups: <by row>

# A tibble: 0 x 3
# … with 3 variables: task_id <fct>, par1 <fct>, par2 <int>
```

**Comment by jennybc** [comment]
> It can name the list elements by a column where group_split() cannot. It is less verbose than group_split(rowwise(tasks)) and returns less complicated objects which take up significantly less space when printed out.

I think most of the things you resist are done intentionally in the Tidyverse paradigm. For example, storing info about the split as list names is a specific anti-pattern that we are trying to discourage. That is, the mere existence of names isn't that harmful (the user can add them if they want), but it's a very unfavourable place to actually _store_ information, in general. The differences you see in printing are largely intentional differences between how a grouped tibble and an ungrouped data frame print (it's sort of apples to oranges).

In case it's useful, I have a repository of worked examples doing row-wise or row-oriented work with purrr with, e.g. `pmap()`, which avoids the need to split the data frame into single-row pieces:

https://github.com/jennybc/row-oriented-workflows

**Comment by Shians** [comment]
I see, if setting list names is an anti-pattern then this function has no purpose. Thanks Jenny.
