### ISSUE TITLE
Using `modify_at()` for removing elements

### ISSUE THREAD

**Issue by echasnovski** [tidyverse/purrr#716]
Recently on Twitter there was a discussion about a tidy way of removing vector elements given their names ([this tweet](https://twitter.com/skyetetra/status/1187221129162711040) in particular).
I suggested `modify_at(x, names_to_remove, ~NULL)`, but it failed to work with multiple elements (thanks to [this tweet](https://twitter.com/EFromTheWest/status/1188126879787687937) from EFromTheWest user):
``` r
x <- list(a = 10, b = 15, c = 18, d = 9)
names_to_drop <- c("a", "b", "c")
purrr::modify_at(x, names_to_drop, ~NULL)
#> $b
#> [1] 15
#> 
#> $d
#> [1] 9
```

<sup>Created on 2019-10-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This seems to be because internally `modify_at()` uses `modify_if()`, which in turn is implemented with iterative modification based on integer indexes (see [these lines](https://github.com/tidyverse/purrr/blob/a8ec9032058e81c20f688523cbf129e0aaf22efd/R/modify.R#L154-L160)). This approach fails to work if elements are removed as a result of modification.

This issue is created to notify about this possible confusion and, probably, for you to consider supporting this behavior.

**Comment by lionel-** [comment]
We _could_ support this via `rlang::zap()`. However I'm not sure that we should allow the result of `modify_` functions to have a different size than the output.

**Comment by hadley** [comment]
We're generally going to move away from the `_at()` functions (#874) which means that we won't be adding any new features to them.
