### ISSUE TITLE
purrr::partial seems to ignore .env argument  for purrr > 0.2.5

### ISSUE THREAD

**Issue by lorenzwalthert** [tidyverse/purrr#717]
This is the anticipated behavior I guess
``` r
# purrr v0.2.5
env <- rlang::empty_env()
add <- function(x, y) {
  print(rlang::env_parent())
  x + y
}

add1 <- purrr::partial(add, x = 1, .env = env)
add1(2)
#> Error in add(x = 1, ...): could not find function "add"
```

<sup>Created on 2019-11-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Then, with `v0.3.0`
``` r
# purrr v0.3
env <- rlang::empty_env()
add <- function(x, y) {
  print(rlang::env_parent())
  x + y
}

add1 <- purrr::partial(add, x = 1, .env = env)
#> Warning: The `.env` argument is soft-deprecated as of purrr 0.3.0.
#> This warning is displayed once per session.
add1(2)
#> <environment: R_GlobalEnv>
#> [1] 3
```

<sup>Created on 2019-11-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

When looking at the [source code](https://github.com/tidyverse/purrr/blob/master/R/partial.R#L132), I think the problem is that `.env` is not in `...` when in ` purrr::partial(add, x = 1, .env = env)` and hence not in `args`, so it won't be spliced: 
```r
partial <- function(.f,
                    ...,
                    .env = NULL,
                    .lazy = NULL,
                    .first = NULL) {
  args <- enquos(...)
  # ... 
  call <- call_modify(call2(fn), ... = , !!!args)
  # ...
}
```

**Comment by lionel-** [comment]
As the warning indicates, `.env` is deprecated.
