### ISSUE TITLE
Unexpected behavior when passing to 'pmap' a formula like anonymous function

### ISSUE THREAD

**Issue by paulponcet** [tidyverse/purrr#721]
Consider the following data.frame: 

    df <- data.frame(x = 1, y = NA)

As expected we have: 

    purrr::pmap(df, sum)
    #> [[1]]
    #> [1] NA

However, I would expect to obtain the same result when I run: 

    purrr::pmap(df, ~ sum(.))
    #> [[1]]
    #> [1] 1

which is not the case. This latter result seems to relate to the following behavior: 

    sum(c(1, NA)) 
    #> NA
    sum(1, NA)
    #> NA
    sum2 <- rlang::as_function(~ sum(.))
    sum2(c(1, NA))
    #> NA
    sum2(1, NA)
    #> 1

**Comment by moodymudskipper** [comment]
It is the expected behavior, `pmap` loops on elements of the first argument, and passes these as arguments to `.f`. 

In the case you think is problematic, you're using `.`, which is the first argument passed to `.f`, which in this case is `1`.

This will work as you expect : 

    purrr::pmap(df, ~ sum(...))

and this might help you understand : 

```
purrr::pmap(df, ~ {
  print(.)  # or print(.x) or print(..1)
  print(.y) # or print(..2)
  sum(...)
  })
#> [1] 1
#> [1] NA
#> [[1]]
#> [1] NA
```

**Comment by lionel-** [comment]
As @moodymudskipper mentioned, pmap works rowwise on data frames (and square lists, i.e. lists containing vectors of equal sizes) and then applies the function on each row by calling the equivalent of `do.call()`. This means that all columns become a single argument.

This is all very complicated and confusing and we'll probably move away from pmap patterns. I suggest using `slide()` from @DavisVaughan's package https://github.com/DavisVaughan/slide. It's a rowwise map which maps the rows to the first argument. This seems to match your intuition @paulponcet:

```r
df <- data.frame(x = 1, y = NA)
slide::slide(df, sum)
#> [[1]]
#> [1] NA

slide::slide(df, ~ sum(.))
#> [[1]]
#> [1] NA
```
