### ISSUE TITLE
FR: Generating a vctrs::list_of with map

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/purrr#722]
Usually when using `map()` one produces a list where each element has the same type, basically the definition of `vctrs::list_of`. So, it might be quite nice to directly produce such a list, e.g. via an argument `.ptype` (though this might break too much existing code already) or adding a new `map_*` function with a `.ptype` argument.

**Comment by lionel-** [comment]
yup, integration of vctrs and purrr is planned for sometimes in 2020.
