### ISSUE TITLE
Partial and default values defined in terms of other arguments

### ISSUE THREAD

**Issue by tvatter** [tidyverse/purrr#743]
Usually, default values can be defined in terms of other arguments. But it does not seem to be the case with `partial`. A simple MWE to illustrate:

```r
library(purrr)

my_plus <- function(x, y) x + y

my_plus_default <- function(x) my_plus(x, y = rep(0, length(x)))
my_plus_partial <- partial(my_plus, ... = , y = rep(0, length(x)))

my_plus_default(x = 1:10) #OK
my_plus_partial(x = 1:10) #NOTOK
```

Is there something that I am missing? If I understand the documentation correctly, using `... = ` should ensure that the partialized argument is passed after the other one. But then why is it that the other (named) argument is not found in the environment where the partialized argument is evaluated?

**Comment by lionel-** [comment]
Unfortunately it would be difficult to support this.

**Comment by lionel-** [comment]
Reopening as I think we can fix this problem by abandoning support for a corner case (dots coming from multiple environments).

**Comment by lionel-** [comment]
To support this we need to reuse the function signature of the function passed as input to `partial()`. However, if we do this, we lose support for NSE functions. Those only work if arguments are forwarded through dots.

**Comment by tvatter** [comment]
Then probably the fact that it does not work should be documented, because this doesn't seem like an absurd use-case.

**Comment by lionel-** [comment]
Added a note.

**Comment by tvatter** [comment]
Thanks!
