### ISSUE TITLE
Row-wise use of function "which" on a dataframe using pmap

### ISSUE THREAD

**Issue by aubryvetepi** [tidyverse/purrr#744]
For each row of my data frame (vector), I am trying to find the vector index at which the maximum value appears for the first time.

I would like to be able to reproduce what I am able to do below using apply, but using pmap instead.

I am getting an "unused arguments" error but cannot figure out how to fix it. 

```r
data <- tibble::tribble(
  ~ var1, ~ var2,  ~ var3, ~ var4, ~ var5,
  1,  2,  5,  5,  5,
  2,  10,  10,  8,  2,
  22,   5,  12,  8,  13
)


apply(data, 1, function(x) min(which(x==max(x))))
#> [1] 3 2 1

purrr::pmap_dbl(data, function(x) min(which(x==max(x))))
#> Error in .f(var1 = .l[[1L]][[i]], var2 = .l[[2L]][[i]], var3 = .l[[3L]][[i]], : unused arguments (var1 = .l[[1]][[i]], var2 = .l[[2]][[i]], var3 = .l[[3]][[i]], var4 = .l[[4]][[i]], var5 = .l[[5]][[i]])
```

**Comment by jennybc** [comment]
You are confronting the "signature problem" described here:

https://github.com/jennybc/row-oriented-workflows/blob/master/ex09_row-summaries.md#how-to-use-an-arbitrary-function-inside-pmap

`pmap()` needs a function that takes "dots", as opposed to a single or primary vector/list argument `x`. I.e. a row's worth of data is presented to the `pmap()`'d function as "loose parts", not packaged into a single object. The `purrr::lift_*()` family of functions helps to convert between these different interfaces.

Incidentally, you might also like to know about the base R functions `which.min()` and `which.max()`.


``` r
library(tidyverse)

data <- tibble::tribble(
  ~ var1, ~ var2,  ~ var3, ~ var4, ~ var5,
       1,      2,       5,      5,      5,
       2,     10,      10,      8,      2,
      22,      5,      12,      8,     13
)

pmap_int(data, lift_vd(which.max))
#> [1] 3 2 1
```

<sup>Created on 2020-02-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by aubryvetepi** [comment]
Hi Jenny,

Thanks for your quick response!
I knew there had to be a way, I just did not which way or how to find it.
I can foresee that the lift family of function will be very helpful to me:
us epidemiologists often find ourselves needing to work rowwise on our data.

Have a great day,

Pascale
