### ISSUE TITLE
`when()` is incompatible with named logical scalar

### ISSUE THREAD

**Issue by salim-b** [tidyverse/purrr#745]
The [documentation](https://purrr.tidyverse.org/reference/when.html) about `purrr::when()` says:

> Validity of the conditions are tested with `isTRUE`, or equivalently with `identical(condition, TRUE)`.

This is kind of a contradiction in itself – `isTRUE(condition)` and `identical(condition, TRUE)` are _not_ the same.

It also bears practical issues when working with _named_ logical scalars (as returned by `fs::file_exists()` for example).

To illustrate the problem, consider the following reprex:

``` r
library(magrittr)

# unnamed logical scalar is fine
lgl <- TRUE
lgl %>% purrr::when(. ~ "yep!", ~ "nooooo...!")
#> [1] "yep!"

# named logical scalar is NOT
names(lgl) <- "muahahaha"
lgl %>% purrr::when(. ~ "yep!", ~ "nooooo...!")
#> [1] "nooooo...!"

# or regarding the "equivalently" statement in the doc
identical(lgl, TRUE)
#> [1] FALSE

# obvious workaround is to manually wrap condition in `isTRUE()`
lgl %>% purrr::when(isTRUE(.) ~ "yep!", ~ "nooooo...!")
#> [1] "yep!"
```

<sup>Created on 2020-02-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
> This is kind of a contradiction in itself – isTRUE(condition) and identical(condition, TRUE) are not the same.

They used to be the same in older R versions.

**Comment by lionel-** [comment]
We should probably mark `when()` as questioning and remove from the reference.

**Comment by salim-b** [comment]
> They used to be the same in older R versions.

I see. So could `when()` be updated to rely on `isTRUE()` instead of `identical()`?

> We should probably mark `when()` as questioning and remove from the reference.

Why? Honestly, I like (and use) `when()` a lot... 😶

**Comment by lionel-** [comment]
It doesn't really fit in the package, nor in our recommended practice. I don't think we'd deprecate it without a recommended alternative though. Marking as questioning and internal is more about reducing the visibility of the function.

> I see. So could when() be updated to rely on isTRUE() instead of identical()?

Probably we'd use vctrs coercion to logical instead of `is_true()`.

**Comment by salim-b** [comment]
> Marking as questioning and internal is more about reducing the visibility of the function.

Well, but there's a reason why you want to "reduce the visibility of the function"...

> It doesn't really fit in the package, nor in our recommended practice. I don't think we'd deprecate it without a recommended alternative though.

And here comes that reason... :wink:

I'd appreciate if my code relying on `when()` would continue to work when you deprecate `when()`, i.e. it would be cool if it would stay in the package. And maybe internally rely on that "recommended alternative" after being deprecated.
