### ISSUE TITLE
documentation for pmap should mention fuzzy matching

### ISSUE THREAD

**Issue by stschiff** [tidyverse/purrr#750]
I was pretty confused when I found out how pmap function parameter matching really works. Here is a simple example that works as expected:

```R
library(magrittr)
t <- list(a = c(1,2,3), b = c(4,5,6))
purrr::pmap(t, function(a, b) {a - b}) %>% unlist()
```

Output: `[1] -3 -3 -3`

You can also switch around the arguments in the function and it still works, because it's matching by name:
```R
purrr::pmap(t, function(b, a) {a - b}) %>% unlist()
```
with the same output as above.

However, it also works if I change the names of the arguments like so:
```R
purrr::pmap(t, function(alpha, beta) {alpha - beta}) %>% unlist()
```

This is not `purrr` suddenly knowing greek, but it's matching only the beginning of the variable name. Shouldn't that throw and error and not work, to be safe?

In contrast, this _doesn't_ work:
```R
purrr::pmap(t, function(first, second) {first - second}) %>% unlist()
```
Output:
```
Error in .f(a = .l[[1L]][[i]], b = .l[[2L]][[i]], ...) : 
  unused arguments (a = .l[[1]][[i]], b = .l[[2]][[i]])
```

because apparently `purrr::pmap` refuses to match by position when the list is named.

I think there are two confusing things here that should be improved in the docs:
1) function parameter matching does _not_ work by order of arguments if the list columns are named. This is a good thing, but it did not become clear to me from the documentation.
2) function parameter matching by name doesn't require the names to be exactly the same, just starting with the same name. This is weird. At the minimum it should be documented, even better in my view would be to throw an error if the names are not exactly matching.

**Comment by jennybc** [comment]
> This is not purrr suddenly knowing greek, but it's matching only the beginning of the variable name. Shouldn't that throw and error and not work, to be safe?

This is a general property of R, not `purrr::pmap()`.

``` r
f <- function(alpha, beta) alpha - beta

f(a = 4, b = 3)
#> [1] 1
```

<sup>Created on 2020-04-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

Many useRs set these options in `.Rprofile`, so this sort of code doesn't slip by:

``` r
options(
    warnPartialMatchArgs   = TRUE,
    warnPartialMatchAttr   = TRUE,
    warnPartialMatchDollar = TRUE
  )
```

to alert you to such situations. `usethis::use_partial_warnings()` is a nice helper to get yourself sorted out.

**Comment by stschiff** [comment]
OK I see. Thanks for clarifying.
