### ISSUE TITLE
list_modify doesn't work when attempting to insert tibble

### ISSUE THREAD

**Issue by dan-reznik** [tidyverse/purrr#755]
Imagine you have a simple 2-level list as follows:

```{r}
 my_l <- list(a=1, b=list(x=c(2,3), y=c(3,4)))
``` 

If I attempt to coerce the `b` element to a tibble, list_modify maintains it as a list!

```{r}
my_l_mod <- list_modify(my_l,b=as_tibble(my_l$b)))
my_l_mod$b %>% class
```
"list" # wish this was a tibble!

Note the base-R way works:

```{r}
my_l_mod$b <- as_tibble(my_l$b)
my_l_mod$b %>% class
```
"data.frame"....

Help / fix appreciated

**Comment by lionel-** [comment]
I'm not sure this is possible without making it a big breaking change. To follow your intuition, we'd have to treat data frames as non-lists:

```r
x <- list(
  a = 1,
  b = list(x = 1:2)
)

out <- list_modify(x, b = data.frame(y = 3:4))

# Result if data frames are not treated as lists
str(out)
#> List of 2
#>  $ a: num 1
#>  $ b:'data.frame':	2 obs. of  1 variable:
#>   ..$ y: int [1:2] 3 4
```

But that's not how they are currently treated. They are treated as lists:

```r
str(out)
#> List of 2
#>  $ a: num 1
#>  $ b:List of 2
#>   ..$ x: int [1:2] 1 2
#>   ..$ y: int [1:2] 3 4
```

Also note how the contents of the RHS was poured into the LHS. And the LHS is a list, so it wouldn't make sense for it to become a data frame.

However, I do wonder about what should happen when the roles are reversed. It seems to me that if we're updating a data frame in the LHS, we should preserve its type. That's not currently the case:

```r
y <- list(
  a = 1,
  b = data.frame(x = 1:2)
)

out <- list_modify(x, b = list(y = 3:4))

str(out)
#> List of 2
#>  $ a: num 1
#>  $ b:List of 2
#>   ..$ x: int [1:2] 1 2
#>   ..$ y: int [1:2] 3 4
```

We should probably fix this.

**Comment by lionel-** [comment]
Another thing we need to consider is whether we want to use `vctrs::vec_is_list(x) || is.data.frame(x)` as a stopping condition for the recursion. I think it'd make sense, but that'd be a breaking change as well. Linear models returned by `lm()` wolud be treated as scalars in that case.

**Comment by hadley** [comment]
Lets solve this via #822
