### ISSUE TITLE
Reexport rep_named from rlang?

### ISSUE THREAD

**Issue by hriebl** [tidyverse/purrr#756]
Just a minor request: Given that rep_along is already reexported from rlang, how about reexporting rep_named as well? I was surprised it is not currently reexported, as rep_along and rep_named are documented on the same help page.

**Comment by lionel-** [comment]
I think from now on this sort of vector-oriented functions will be reexported from the [funs](https://github.com/tidyverse/funs) package rather than from purrr, which should focus on higher order functions. Do you feel the same way @hadley?

**Comment by hadley** [comment]
Yeah, I _think_ so.
