### ISSUE TITLE
cross_df doesnt preserve ordered factor type.

### ISSUE THREAD

**Issue by reisner** [tidyverse/purrr#760]
`purrr::cross_df` doesnt preserve a column type when one columns is an ordered factor. Before the function, the column is an ordered factor, afterwards it is just a plain factor. 

---

Example:

```r
all_days = c("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat")
all_days_f = factor(all_days, ordered = TRUE, levels = all_days)
all_hours = 0:23
ll = list(DayOfWeek = all_days_f, HourOfDay = all_hours)
class(ll$DayOfWeek)
 # [1] "ordered" "factor"
df = purrr::cross_df(ll)
class(df$DayOfWeek)
 # [1] "factor"
```

**Comment by lionel-** [comment]
If you use `tidyr::expand_grid()` instead, it works correctly:

```r
out <- tidyr::expand_grid(!!!ll)
class(out$DayOfWeek)
#> [1] "ordered" "factor"
```

I think we'll just deprecate `cross_df()`, and probably `cross()` too. They are super slow too.

**Comment by reisner** [comment]
@lionel- Thanks! I actually ended up using `expand_grid` anyways! I agree, I think `cross_df` isnt needed, and led me down the wrong rabbithole :)

**Comment by lionel-** [comment]
Agreed, the deprecation is tracked in #768.
