### ISSUE TITLE
purrr and Graph

### ISSUE THREAD

**Issue by bebersb** [tidyverse/purrr#762]
I just ran into some strange problem when igraph and purrr are loaded at the same time: 

library(purrr)
library(igraph)

g <- graph( c(1,2, 1,2, 1,2, 2,3, 3,4) )
E(g)$weight <- 1:5
simplify(g)

This returns:

Fehler in adjacent_vertices(x, i, mode = if (directed) "out" else "all") : 
  At iterators.c:759 : Cannot create iterator, invalid vertex id, Invalid vertex id

Detaching purrr with
detach("package:purrr", unload=TRUE)

Solves the problem.

I have no clue what the issue is. But maybe it is interesting to know. 

All the best. Thanks for your great work!

BE

**Comment by batpigandme** [comment]
When you attach either package, do you get a warning about a namespace conflict?

**Comment by batpigandme** [comment]
Yes, there are namespace conflicts. I can get it to work by using prefix/`::` notation. 
``` r
library(purrr)
library(igraph)
#> 
#> Attaching package: 'igraph'
#> The following objects are masked from 'package:purrr':
#> 
#>     compose, simplify
#> The following objects are masked from 'package:stats':
#> 
#>     decompose, spectrum
#> The following object is masked from 'package:base':
#> 
#>     union

g <- graph( c(1,2, 1,2, 1,2, 2,3, 3,4) )
E(g)$weight <- 1:5
igraph::simplify(g)
#> IGRAPH 01bb3d7 D-W- 4 3 -- 
#> + attr: weight (e/n)
#> + edges from 01bb3d7:
#> [1] 1->2 2->3 3->4
```
<sup>Created on 2020-05-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
