### ISSUE TITLE
map_df() removes milliseconds when reading a csv file.

### ISSUE THREAD

**Issue by bastianilso** [tidyverse/purrr#764]
Hi,

We use timestamps with milliseconds in the format `HH:mm:ss.ffff` a lot in our CSV files.
I have attached one such CSV file as example: [sampleLog_2020-05-13 10-30-10.0167.zip](https://github.com/tidyverse/purrr/files/4633049/sampleLog_2020-05-13.10-30-10.0167.zip)

With the following import:
```r
df2<-list.files(pattern = "^sample.*.csv") %>% 
  map_df(~read_csv(.))
```
the milliseconds which were present in the CSV file is no longer present in `df2`.

![image](https://user-images.githubusercontent.com/3967945/82026489-1979e800-9693-11ea-8392-0d078600e3e5.png)

**Comment by lionel-** [comment]
Is this `readr::read_csv()` issue? I see the same output with `read_csv()` outside of map-df.

(A minimalistic reprex with synthetic data would be great.)

**Comment by bastianilso** [comment]
@lionel-  running `df2<-read.csv("sampleLog_2020-05-13 10-30-10.0167.csv")` works fine for me.
![image](https://user-images.githubusercontent.com/3967945/82032002-ee939200-969a-11ea-9b81-3ff2d095f975.png)
sry, was in a rush, just though i would report it but yea, removing `map_df()` from the equation seems to fix the issue, hence my report..

**Comment by lionel-** [comment]
In this example you're using `base::read.csv()` rather than `readr::read_csv()`.

**Comment by bastianilso** [comment]
@lionel-  ah yea you are right I did not realize. In that case, I see what you mean, it does indeed look like the faulty part is `read_csv` from `readr` - sorry for wasting your time!

**Comment by lionel-** [comment]
No worries
