### ISSUE TITLE
Behaviour of map_*() when handling NULL results

### ISSUE THREAD

**Issue by DanChaltiel** [tidyverse/purrr#772]
I was wondering about the behavior of `map_*()` functions when `.f` returns `NULL`.

Here is an example to illustrate my point:

```r
library(tidyverse)
x=1
y=2
z=3
attr(x, "label") = "foo"
attr(y, "label") = "bar"
l=list(x=x,y=y,z=z)
map(l, attr, which="label", exact=TRUE)
#> $x
#> [1] "foo"
#> 
#> $y
#> [1] "bar"
#> 
#> $z
#> NULL
map_chr(l, attr, which="label", exact=TRUE)
#> Error: Result 3 must be a single string, not NULL of length 0
c(x="foo", y="bar", z=NULL) #alternative output 1
#>     x     y 
#> "foo" "bar"
c(x="foo", y="bar", z=NA) #alternative output 2
#>     x     y     z 
#> "foo" "bar"    NA
```

As for now, the error message is very clear about `NULL`not being an acceptable result.

However, I find disturbing the fact that `map()` returns a result while `map_chr()` throws an error. I was expecting either one of both presented alternative output.

The former (`NULL`), seems the most logical as it fully respects the initial input. However, the length of the result being shorter than the one of the input might be a substantial problem.

The latter (`NA`) still makes sense and does not present such an issue, which perhaps makes it a better compromise.

Of course, there might be a warning thrown each time this behavior is triggered, with an option to mute it. 

For instance, you could consider something like this:

```r
map_chr(l, attr, which="label", exact=TRUE)
#>     x     y     z 
#> "foo" "bar"    NA
#> Warning: Result 3 was NULL or of length 0, it was replaced by NA
map_chr(l, attr, which="label", exact=TRUE, .warn_null=FALSE)
#>     x     y     z 
#> "foo" "bar"    NA
```

**Comment by lionel-** [comment]
> However, I find disturbing the fact that map() returns a result while map_chr() throws an error. I was expecting either one of both presented alternative output.

`map()` returns a list which can contain any object, including `NULL`. `map_chr()` returns a character vector and so `.f` must return a size 1 character vector.
