### ISSUE TITLE
Clarification of argument `...` Additional arguments passed on to the mapped function

### ISSUE THREAD

**Issue by ramiromagno** [tidyverse/purrr#780]
As per the documentation page of `map` I would expect the following code not to throw an error:

``` r
library(purrr)

f <- function(a, b) {
  a + b
}

map(1:3, .f = ~ f(b = .x), a = 1)
#> Error in f(b = .x): argument "a" is missing, with no default
```

So my expectation was wrong.

Would you reckon that some extra clarification on how the *`...` Additional arguments* interact with the `.f` specification (function or formula) would help preventing wrong expectations here?

I posted this issue originally as a stackoverflow question: https://stackoverflow.com/questions/63207276/how-to-use-purrrmap-not-to-be-iterated-additional-arguments#63207321

**Comment by lionel-** [comment]
I've added this note:

```
#' Note that formula functions conceptually take dots (that's why you
#' can use `..1` etc). They silently ignore additional arguments that
#' are not used in the formula expression.
```

I'm ambivalent about including too many details like this though, there's enough material about corner cases to make any help page daunting.
