### ISSUE TITLE
map2 vs pmap

### ISSUE THREAD

**Issue by iamnicogomez** [tidyverse/purrr#793]
Hi Purrr devs,

Perhaps I'm missing some of the nuance with map2(), but in my opinion the fundamental goal of map2() (to apply a function on a list of paired arguments) is much more congruent with the goal of pmap() (to apply a function on a list of grouped arguments). In keeping with the tidyverse styling of scoped and specific-case functions, map2() could more clearly be named pmap2() and pmap2_xx(). I feel strongly about this after having spent way too long trying to use map() which I thought was the "n arguments" version of map2(). Apologies if I missed a similar suggestion on the issue page.

Thanks for your consideration,
Nico

**Comment by lionel-** [comment]
They are very related, but we decided 6 years ago to go with `map2()`. Note that `map()` directly takes a vector to map over and `map2()` directly takes two vectors to map over. By contrast, `pmap()` takes a list of vectors to map over. So there's some consistency that your proposal wouldn't have.
