### ISSUE TITLE
Clarification on using `safely` in a package

### ISSUE THREAD

**Issue by tjtnew** [tidyverse/purrr#795]
Would it be possible to clarify the usage of `safely` within a package.  Reading the [documentation](https://purrr.tidyverse.org/reference/faq-adverbs-export.html) it discusses using the `.onload` hook to prevent problems when `purrr` is updated but is it not preferable to instead create explicit wrapper functions, e.g.

```r
fun1 <- function(x) {
    x^2
}

# this would need to be done with .onLoad
fun2 <- purrr::safely(fun1)

# is there a problem with doing the following instead and exporting?
fun3 <- function(x) purrr::safely(fun1)(x)
```

This may be a misunderstanding on my part, so it would be great to get clarification.

**Comment by lionel-** [comment]
The `fun3()` pattern is a good option as well. The main thing is to create an indirection and avoid assigning the function in your namespace at build time.

**Comment by tjtnew** [comment]
Cheers - Do you want a PR for the [documentation](https://purrr.tidyverse.org/reference/faq-adverbs-export.html)?

**Comment by lionel-** [comment]
That'd be great, thanks!

**Comment by tjtnew** [comment]
Cool.  All done
