### ISSUE TITLE
Option to preserve `accumulate()` length when `.init` is specified

### ISSUE THREAD

**Issue by kbzsl** [tidyverse/purrr#802]
Is it possible to add an extra flag for inhibiting the length extension when `.init` is specified for `accumulate` function?

Rationale: there are situations when the `.init` is an important input value, but the result of the first accumulate step (having the value of the `.init`) is not required, just the subsequent values. 
This side effect of incrementing the length  makes it infeasible to use with tibbles.

For example, the subsetting works, but the legibility is questionable: 

```r
library(tidyverse)

numbers =  c(1, 2, 3)
numbers_df <- tibble(n = numbers)

numbers_df %>% 
  mutate(acc_init = accumulate(n, `+`, .init = 1000))
#> Error: Problem with `mutate()` input `acc_init`.
#> x Input `acc_init` can't be recycled to size 3.
#> i Input `acc_init` is `accumulate(n, `+`, .init = 1000)`.
#> i Input `acc_init` must be size 3 or 1, not 4.

numbers_df %>% 
  mutate(acc_init = accumulate(n, `+`, .init = 1000)[-1])
#> # A tibble: 3 x 2
#>       n acc_init
#>   <dbl>    <dbl>
#> 1     1     1001
#> 2     2     1003
#> 3     3     1006

```
I think that a separate flag makes sense, because I assume that there are other cases when the extended length is preferred.

**Comment by lionel-** [comment]
What would you call this argument? 

I think that's a case where composition makes more sense. Otherwise we'll have an argument that only applies when `.init` is supplied. And a general `drop_first` that would apply in all cases doesn't seem useful.

We could just add an example in the doc to show how to subset out the init element with `[`.

**Comment by kbzsl** [comment]
Yes, you are right. That flag would make sense only if the `.init` parameter is used. Unfortunately, I don’t have any good name for this flag.

My personal opinion is that the need to use the subsetting is not really in line with the tidy principles/manifesto (design for humans).
I consider that you are in the best position to decide how to handle this issue and I can accept that you will end up with documenting the subsetting.

**Comment by huftis** [comment]
Regarding the name, how about `skip_init`? Then it’s clear that it will only have an effect **if** one supplies an `.init` value. BTW, I too think this feature would be useful.

**Comment by lionel-** [comment]
> My personal opinion is that the need to use the subsetting is not really in line with the tidy principles/manifesto (design for humans)

purrr is in the middle between a data-analysis and a programming package. I would consider reduce and accumulate to be more on the programming side.

> Regarding the name, how about .skip_init? Then it’s clear that it will only have an effect if one supplies an .init value.

Agreed that this would be a good name.

**Comment by hadley** [comment]
Another option would be to have something like `.first` that works like `.init` but isn't included in the results. And you'd be able to use only one of `.init` or `.first`. But it's hard to know what you'd call this.

**Comment by hadley** [comment]
Given that the workaround is so simple (add `[-1]`) and coming up with a good specification for this behaviour is hard, I think it's easiest to leave `accumulate()` as is.
