### ISSUE TITLE
rename(...) for lists?

### ISSUE THREAD

**Issue by mmuurr** [tidyverse/purrr#804]
Sometimes I have a need to _selectively_ rename elements in a list. `rlang::set_names` with a conditional in the renaming function can handle this, but is pretty ugly. `dplyr::rename` (and `rename_with`) has a much cleaner syntax ... is it worth implementing `rename` for lists and placing that implementation in purrr (since `dplyr::rename` is a generic)?

The only issue I can see is how to handle duplicate names, since lists don't have the unique-colname constraint ... my bias tends to skew to 'buyer-beware' and if someone tries to rename a name that already appears _n_ times, then they should get that new name back out _n_ times.

For a motivating use case, consider JSON data received from some external API. Often a preceding underscore in a field's key indicates 'specialness' somehow, e.g. `_type`. It might be useful to combine a list-aware rename with other purrr manipulators (or `rapply`) to quickly convert those to R's convention for 'specialness', `.type` (since the leading underscore makes accessing those elements a bit harder in R).

**Comment by lionel-** [comment]
We are not implementing list methods for dplyr verbs at the moment. However you can easily implement this function for yourself. It handles duplicate names and will work for any input with `[` and `names()` methods:

```r
my_rename <- function(.x, ..., .strict = TRUE) {
  pos <- tidyselect::eval_rename(quote(c(...)), .x, strict = .strict)
  names(.x)[pos] <- names(pos)
  .x
}

my_rename(list(a = 1, a = 2), b = a)
#> $b
#> [1] 1
#>
#> $b
#> [1] 2
```

Taken from `tidyselect:::rename()`. See also `tidyselect:::select()`.
