### ISSUE TITLE
pass dots to anonymous function?

### ISSUE THREAD

**Issue by mkoohafkan** [tidyverse/purrr#812]
I'm getting some weird behavior when trying to pass `...` arguments to anonymous functions, i.e., functions specified using `~`. I initially ran into this issue using `slider::slide2()` but I am reproducing the issue with `map2()` so I'm thinking the issue has to do with `as_mapper()`. The issue crops up when trying wrapping a function around `map()`, e.g. this reprex:

```r
library(purrr)

# a silly function
test_fun = function(x, mask, a = 5) {
  x[mask] = a
  x
}
# using map2_dbl
bar1 = function(x, mask, ...) {
  map2_dbl(x, mask, test_fun, ...)
}
# using map2_dbl and ~ function
bar2 = function(x, mask, ...) {
  map2_dbl(x, mask, ~ test_fun(.x, .y, ...))
}

set.seed(42)
xs = rnorm(10)
mk = as.logical(rbinom(10, 1, 0.5)) 

bar1(xs, mk, a = 3)
## [1]  3.0000000 -0.5646982  3.0000000  3.0000000  0.4042683  3.0000000
## [7]  1.5115220  3.0000000  2.0184237  3.0000000bar2(xs, mk)

bar2(xs, mk, a = 3)
## Error in test_fun(.x, .y, ...) : unused argument (TRUE)
```

In more complex cases I have gotten weird results where it appears that the components of `...` are getting mixed up or erroneously recycled from the initial two arguments. Is passing `...` to anonymous functions as in `bar2()` simply a no-go?

**Comment by hadley** [comment]
Minimal reprex:

``` r
x <- 1:5

fun1 <- function(x, mask, a = 5) {
  x[mask] <- a
  x
}
fun2 <- purrr::as_mapper(~ fun1(.x, .y, ...))

fun1(x, 1:3, 0)
#> [1] 0 0 0 4 5
fun2(x, 1:3, 0)
#> Error in fun1(.x, .y, ...): unused arguments (1:3, 0)
```

<sup>Created on 2022-08-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

The problem is somewhat obvious if you look at `fun2`:

```
> fun2
<lambda>
function (..., .x = ..1, .y = ..2, . = ..1) 
fun1(.x, .y, ...)
attr(,"class")
[1] "rlang_lambda_function" "function" 
```

The problem is that `.x` and `.y` end up passed in twice because they're not removed from `...`

I'd say this is a fundamental limitation of `as_mapper()` and we should just briefly document that it's a bad idea to use it with `...`
