### ISSUE TITLE
Add support for non-recursive version of `list_modify`

### ISSUE THREAD

**Issue by vspinu** [tidyverse/purrr#822]
Sometimes recursion is not needed when modifying lists. Would be nice to have `recursive = TRUE` argument to `list_modify` and `list_merge`. Or maybe a bit more control over which objects should be considered atomic. For instance, one often it's useful to treat `data.frames` as atomic.

```
> a <- list(x = data.frame(one = 1, two = 2))
> b <- list(x = data.frame(three = 3))
> list_modify(a, b)
# current
$x
  one two three
1   1   2     3
# desired
$x
  three
1     3
```

**Comment by hadley** [comment]
Agreed, I think this is what I usually want.
