### ISSUE TITLE
`map_dfr(..., .id='colname')` should return empty DF with one column when input is empty list

### ISSUE THREAD

**Issue by meowcat** [tidyverse/purrr#824]
Brief description of the problem

```r
library(tidyyverse)
map_dfr(list(), ~.x, .id = "test")
```
This returns a 0x0 tibble. However, I rely downstream on a column "test" existing (this is the only column that's guaranteed to exist). I would expect the result to be a 0x1 tibble with a column called "test", since the result of `map_dfr` with lists of different-named element + `.id` is a dataframe with the union of all columns plus the ID column:

```
list(list(a=1, b=2), list(a=1, c=3)) %>% map_dfr(~.x)
list(list(a=1, b=2), list(a=1, c=3)) %>% map_dfr(~.x, .id = "col")
```
Therefore, with zero columns, this should be the union of all columns (none) plus the ID column.

**Comment by hadley** [comment]
Root cause is probably a vctrs issue. Reprex:

``` r
purrr::map_dfr(list(), ~.x, .id = "test")
#> # A tibble: 0 × 0
vctrs::vec_rbind(.names_to = "test")
#> data frame with 0 columns and 0 rows
```

<sup>Created on 2022-08-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
Now tracking in vctrs.
