### ISSUE TITLE
map_dfr return a prototype when there are no iterations

### ISSUE THREAD

**Issue by zeehio** [tidyverse/purrr#832]
`map_dfr` returns a zero-column data frame if the input iterable has length zero. It would be nice to be able to provide a prototype as an argument, to guarantee some columns are always present in the output, even in corner cases where the input is empty.

```r
library(purrr)

y <- map_dfr(1, function(x) data.frame(x=1))
"x" %in% colnames(y) # This is TRUE
#> [1] TRUE

y <- map_dfr(integer(0L), function(x) data.frame(x=1))
"x" %in% colnames(y) # I would  like to provide a prototype to map_df so this becomes TRUE as well.
#> [1] FALSE
```

For instance

```r
y <- map_dfr(integer(0L), function(x) data.frame(x=1), .ptype = data.frame(x=numeric(0)))
"x" %in% colnames(y) # This would be TRUE
```

Would you think this feature would make sense?

Thanks for your time

**Comment by hadley** [comment]
Part of #758 since we'll solve this by passing along `.ptype`.
