### ISSUE TITLE
Issue with pmap when first column of tibble is a date

### ISSUE THREAD

**Issue by karjamatti** [tidyverse/purrr#833]
It seems that pmap doesn't work when the first column of a tibble is a date column. The issue vanishes if the columns are rearranged.

I came across this issue when trying to hash each row of a tibble using digest, but for simplicity the reprex below is simplest I could think of.

```r
purrr::pmap(tibble::tibble(x = 1, y = 'foo', date = lubridate::ymd('2020-01-01')), ~length(c(...)))
# [[1]]
# [1] 3

purrr::pmap(tibble::tibble(date = lubridate::ymd('2020-01-01'), x = 1, y = 'foo'), ~length(c(...)))
# Error in as.Date.numeric(e) : 'origin' must be supplied
```

The error in the reprex was different from the original one I got, which was this:
```r
# Error: Problem with `mutate()` input `hash_key`.
# x character string is not in a standard unambiguous format
# i Input `hash_key` is `purrr::pmap_chr(., ~digest::digest(c(...)))`.
```

This one also disappeared when rearranging the columns so that the first columns was something else than the date.

**Comment by hadley** [comment]
This looks like a base R bug let to me:

``` r
df <- tibble::tibble(date = as.Date('2020-01-01'), x = 1, y = 'foo')
c(df[[1]], df[[2]], df[[3]])
#> Error in as.Date.numeric(e): 'origin' must be supplied
```

<sup>Created on 2022-08-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
