### ISSUE TITLE
Function that needs reference to calling env doesn't work when partialised

### ISSUE THREAD

**Issue by jimjam-slam** [tidyverse/purrr#834]
In [a recent StackOverflow question](https://stackoverflow.com/questions/68310354/partialised-glue-function-does-not-work-when-called-in-different-environment/68310565), I mentioned that I was trying to partialise [`glue::glue`](https://glue.tidyverse.org/reference/glue.html) in a project I'm working on so that we can use agreed-on delimiters without having to tell glue about them all the time.

But when we go to use the partialised function inside another function, it stops working:

``` r
library(purrr)
library(glue)

glue_query <- partial(glue, .open = "<<", .close = ">>")

# case 1: use partialised function in same scope
x <- 15
glue_query("There are <<x>> apples here!")
#> There are 15 apples here!

# case 2: use partialised function in different scope
myfunc_partialised <- function(y) {
  glue_query("The thing I called y is actually <<y>>")
}
myfunc_partialised(15)
#> Error in eval(parse(text = text, keep.source = FALSE), envir): object 'y' not found

# case 3: use function directly
myfunc_regular <- function(z) {
  glue("The thing I called z is actually <<z>>", .open = "<<", .close = ">>")
}
myfunc_regular(15)
#> The thing I called z is actually 15

# case 4 (suggested workaround): manually wrap function
glue_query2 <- function(..., .open = "<<", .close = ">>", .envir=parent.frame()) {
  glue(..., .open=.open, .close=.close, .envir=.envir)
}
myfunc_wrapped <- function(a) {
  glue_query2("The thing I called a is actually <<a>>")
}
myfunc_wrapped(15)
#> The thing I called a is actually 15
```

<sup>Created on 2021-07-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

`glue` has an argument, `.envir = parent.frame()`, that controls where the expressions are evaluated. My sense is that in case 2 (partialised), the environment in which the partialisation was defined is probably the one being selected, instead of the _calling_ environment. Is there an obvious way I should modify `glue` to account for partialisation, or is this unexpected behaviour in `partial`?

**Comment by hadley** [comment]
`partial()` can only do so much, and I think that this is one of the cases that it can't handle, and manually wrapping the function is the way to go.
