### ISSUE TITLE
Print changing behaviour of map function 

### ISSUE THREAD

**Issue by oduilln** [tidyverse/purrr#835]
I am trying to map a a list of strings in order to loop through all columns of a data frame and perform some dplyr functions. I am done something similar before, using a combination of enquo and !! in order to evaluate the columns of the data frame by using a string stored as a variable.

However, print seems to be altering how map functions. See below, the first code block does not work as I thought it would. However, by printing first it works, and I can't figure out why. Why is print affecting how map runs? 

```r
library(purrr)
library(dplyr)

df <- tibble(
  Column_A = 1:10,
  Column_B = 11:20,
  Column_C = letters[1:10],
)

# Error
names(df) %>%
  purrr::map(.f = ~ {
    column <- dplyr::enquo(.x)
    count(df, !! column)
  })

# Works 
names(df) %>%
  purrr::map(.f = ~ {
    print(.x)
    column <- dplyr::enquo(.x)
    count(df, !! column)
  })
```

Error code for first block:
```r
> names(df) %>%
+   purrr::map(.f = ~ {
+     column <- dplyr::enquo(.x)
+     count(df, !! column)
+   })
 Error: Must group by variables found in `.data`.
* Column `..1` is not found.
Run `rlang::last_error()` to see where the error occurred. 
```

``` r
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_Ireland.1252  LC_CTYPE=English_Ireland.1252   
[3] LC_MONETARY=English_Ireland.1252 LC_NUMERIC=C                    
[5] LC_TIME=English_Ireland.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] forcats_0.5.1   stringr_1.4.0   dplyr_1.0.6     purrr_0.3.4     readr_1.4.0     tidyr_1.1.3    
[7] tibble_3.1.2    ggplot2_3.3.3   tidyverse_1.3.1

loaded via a namespace (and not attached):
 [1] tidyselect_1.1.1 xfun_0.24        haven_2.4.1      colorspace_2.0-2 vctrs_0.3.8     
 [6] generics_0.1.0   utf8_1.2.1       rlang_0.4.11     pillar_1.6.1     glue_1.4.2      
[11] withr_2.4.2      DBI_1.1.1        dbplyr_2.1.1     modelr_0.1.8     readxl_1.3.1    
[16] lifecycle_1.0.0  munsell_0.5.0    gtable_0.3.0     cellranger_1.1.0 rvest_1.0.0     
[21] zip_2.1.1        evaluate_0.14    knitr_1.33       markdown_1.1     fansi_0.4.2     
[26] highr_0.9        broom_0.7.6      Rcpp_1.0.7       scales_1.1.1     backports_1.2.1 
[31] jsonlite_1.7.2   fs_1.5.0         hms_1.1.0        stringi_1.6.2    openxlsx_4.2.4  
[36] grid_4.0.2       compare_0.2-6    cli_2.5.0        tools_4.0.2      magrittr_2.0.1  
[41] crayon_1.4.1     pkgconfig_2.0.3  ellipsis_0.3.2   xml2_1.3.2       reprex_2.0.0    
[46] lubridate_1.7.10 assertthat_0.2.1 httr_1.4.2       rstudioapi_0.13  R6_2.5.0        
[51] compiler_4.0.2  
```

**Comment by jennybc** [comment]
I've reworked the example a bit, but first I show that the method you say "works" does not actually work. There's no explicit error, but I believe the result isn't what you want.

``` r
library(tidyverse)

dat <- tibble(
  y = rep(letters[1:3], each = 2),
  z = rep(letters[4:5], each = 3)
)

# no, this does not work; there's no error, but result is nonsensical
names(dat) %>%
  map(.f = ~ {
    print(.x)
    column <- enquo(.x)
    count(dat, !! column)
  })
#> [1] "y"
#> [1] "z"
#> [[1]]
#> # A tibble: 1 × 2
#>   `"y"`     n
#>   <chr> <int>
#> 1 y         6
#> 
#> [[2]]
#> # A tibble: 1 × 2
#>   `"z"`     n
#>   <chr> <int>
#> 1 z         6
```

<sup>Created on 2021-09-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

You have the variable names as strings, so the correct way to quote or "defuse" them (in tidy eval terminology), is to use `ensym()`. The reason you see things working differently with and without `print(.x)` is because `print()` is having the side effect of forcing `.x`. Here's a working version of what you're trying to do:

``` r
names(dat) %>%
  map(.f = ~ {
    force(.x)
    column <- ensym(.x)
    count(dat, !! column)
  })
#> [[1]]
#> # A tibble: 3 × 2
#>   y         n
#>   <chr> <int>
#> 1 a         2
#> 2 b         2
#> 3 c         2
#> 
#> [[2]]
#> # A tibble: 2 × 2
#>   z         n
#>   <chr> <int>
#> 1 d         3
#> 2 e         3
```

I suspect there are other ways of expressing this that have a more natural feel, but I haven't had enough ☕️ yet for that.

**Comment by oduilln** [comment]
Yes you're right, looks like I didn't have enough coffee either! That's exactly what I was looking for, thank you!

I think my knowledge of closures might be too basic to understand what's happening here, but what does force do within the context of map exactly? Does it allow the programmer to use '.x' as if it were a variable within a function?

**Comment by jennybc** [comment]
I checked in here with today's ☕️ and was able to come up with an example of a more natural way to express this. Quoting and unquoting seems like inessential weirdness here and is only getting forced on you by the decision to use `dplyr::count()`. You want a frequency table for different columns, yeah? I think mapping a vector-expecting function over the columns of the data frame is a better way to approach this, e.g. use `forcats::fct_count()`:

``` r
library(tidyverse)

dat <- tibble(
  y = rep(letters[1:3], each = 2),
  z = rep(letters[4:5], each = 3)
)

dat %>% 
  map(fct_count)
#> $y
#> # A tibble: 3 × 2
#>   f         n
#>   <fct> <int>
#> 1 a         2
#> 2 b         2
#> 3 c         2
#> 
#> $z
#> # A tibble: 2 × 2
#>   f         n
#>   <fct> <int>
#> 1 d         3
#> 2 e         3
```

<sup>Created on 2021-09-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

(Terminology wise, re: forcing, this is about forcing a *promise* (not a closure).)

**Comment by oduilln** [comment]
Perfect, that is even better. Thanks again~!
