### ISSUE TITLE
Could map_dbl return empty vector for empty elements (revival)?

### ISSUE THREAD

**Issue by DanChaltiel** [tidyverse/purrr#841]
Hi,

This is a revival of #337:

> Use `.default = NA`
> _Originally posted by @hadley in https://github.com/tidyverse/purrr/issues/337#issuecomment-311067457_

In fact, applying the closing comment does not solve the original question:

``` r
unlist(lapply(list(1), function(x) x[-1]))
#> numeric(0)
purrr::map_dbl(list(1), ~ .x[-1])
#> Error: Result 1 must be a single double, not a double vector of length 0
purrr::map_dbl(list(1), ~ .x[-1], .default=-99)
#> Error: Result 1 must be a single double, not a double vector of length 0
```

<sup>Created on 2021-10-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

It seems that `.default` is working when the result is `NULL` but not if the result is of length 0.

It would be very convenient if this were the case.

**Comment by hadley** [comment]
Since that issue was originally filed, I think the distinction between `NULL` and length-0 vectors has become even more clear to us, and I don't think we want to change the scope of `.default`.
