### ISSUE TITLE
inconsistent behaviors between map() and lapply() applied to function with dots ...

### ISSUE THREAD

**Issue by ShixiangWang** [tidyverse/purrr#844]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

I got a bug report and found that a line of code containing `purrr::map` not work anymore https://github.com/openbiox/UCSCXenaShiny/commit/62565003fbf5f5736b62b31560154c5c0c2aff96. I have to rewrite to fix the issue. Here I provide a minimal example for discussing this. I don't know if this is a bug or a decision made by purrr developers.

```r
inside = function(x, ...) {
  print(list(...))
}

outside = function(...) {
  purrr::map(list(1:10), ~ inside(., ...))
  invisible()
}

outside(type = "sum")
#> [[1]]
#>  [1]  1  2  3  4  5  6  7  8  9 10

outside2 = function(...) {
  lapply(list(1:10), function(x) inside(x, ...))
  invisible()
}

outside2(type = "sum")
#> $type
#> [1] "sum"
```

**Comment by lionel-** [comment]
This is expected in `~` lambdas in order to support `..1`, `..2`, etc. Either use `function(x) x` or R 4.1 syntax `\(x) x`.

**Comment by ShixiangWang** [comment]
@lionel- Thanks, I got it.
