### ISSUE TITLE
Use pmap to iterate rowwise without unpacking list columns?

### ISSUE THREAD

**Issue by LukasWallrich** [tidyverse/purrr#846]
I have a tibble including list columns, and would have expected pmap to iterate over it row-wise like it would over any dataframe. Instead, it somewhat unnests the rows (retaining single-item lists), which increases the number of rows and makes it hard to reassemble results. Not sure whether that is a bug or a behavior that is just unexpected.

A minimum example where I would have expected the two calls to pmap to return the same output:

``` r
library(purrr)
library(tibble)
pmap(mtcars[1:3, ], ~tibble(...)$mpg)
#> [[1]]
#> [1] 21
#> 
#> [[2]]
#> [1] 21
#> 
#> [[3]]
#> [1] 22.8
#> 


mtcars$list <- rep(list(list("a", 1)), 32)
pmap(mtcars[1:3, ], ~tibble(...)$mpg)
#> [[1]]
#> [1] 21 21
#> 
#> [[2]]
#> [1] 21 21
#> 
#> [[3]]
#> [1] 22.8 22.8
#> 

```

<sup>Created on 2021-12-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by jeremy-r-ansell** [comment]
I think this behaviour is simply due to the difference in how `[[` works for lists compared with atomic vectors. Whilst indexing an atomic vector with `[[` produces a length-1 atomic vector, the extracted element from a list could be any length and has a depth that is less than the original list (in the sense of `purrr::vec_depth`). This is why your list-column has lost a level of "nestedness" in the newly constructed tibbles.

Some examples to hopefully illustrate the reason for this:
``` r
library(purrr)
library(tibble)

# Create a 1-row data frame with a list column
df <- tibble(x = 1, y = list(list("a", TRUE)))
df
#> # A tibble: 1 x 2
#>       x y         
#>   <dbl> <list>    
#> 1     1 <list [2]>

# Calculate a result with pmap
result <- pmap_dfr(df, tibble)
result
#> # A tibble: 2 x 2
#>       x y        
#>   <dbl> <list>   
#> 1     1 <chr [1]>
#> 2     1 <lgl [1]>

# Column y has indeed lost one level of "nestedness" in the list column, and the
# result has more rows that the original due to vector recycling. This is
# equivalent to removing the outer `list()` call in the creation of column y:
identical(
  result,
  tibble(x = 1, y = list("a", TRUE))
)
#> [1] TRUE

# We also get an equivalent result by constructing a tibble from the first
# elements of df$x and df$y:
identical(
  result,
  tibble(x = df$x[[1]], y = df$y[[1]])
)
#> [1] TRUE
```

<sup>Created on 2022-07-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
Thanks @jeremy-r-ansell!

**Comment by LukasWallrich** [comment]
Thanks for this explanation @jeremy-r-ansell! That makes sense, but means it is rather fiddly to get pmap to actually iterate over the original rows, which seems to be its point ("apply the function .f to each row")? Anyway, your explanation helped me find a workaround that I wanted to share here in case anyone else stumbles across this ...

``` r
library(tidyverse)
df <- tibble(a = 1:2, b = 2:3, 
             c = list(c("a", "b"), c("d", "e")))

res <- df %>%
  rowwise() %>%
  mutate(across(where(is.list), ~ list(list(.x)))) %>%
  pmap_dfr(function(...) {
    tibble(...)
  })

identical(df, res)
#> [1] TRUE
```

<sup>Created on 2022-08-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
@LukasWallrich what are you trying to do? Using `across()` with `pmap()` is a surprising combination.

**Comment by LukasWallrich** [comment]
I have a tibble that specifies analyses to conduct on a larger dataset, including filter and selection conditions of variable lengths - and then want to iterate through these analyses. Currently, I am using something like the below- which works, but is not particularly clean.

``` r
library(tidyverse)
data(diamonds)
analyses <- tibble(min_price = c(300, 400), cuts = list(c("Ideal", "Premium"), c("Fair", "Ideal")))

analyses %>%
  rowwise() %>%
  mutate(across(where(is.list), ~ list(list(.x)))) %>%
  pmap_dfr(function(...) {
    current <- tibble(...)
    diamonds %>% filter(price > current$min_price, as.character(cut) %in% unlist(current$cuts)) %>% summarise(n())
  })
#> # A tibble: 2 × 1
#>   `n()`
#>   <int>
#> 1 35342
#> 2 23095
```

<sup>Created on 2022-08-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by LukasWallrich** [comment]
Thank you - very helpful!
