### ISSUE TITLE
ikeep: analogous to imap, make .y available to predicate function

### ISSUE THREAD

**Issue by torbjorn** [tidyverse/purrr#848]
Would it be feasible to also have an `ikeep`, that would be to `keep` what `imap` is to `map`.

```r

my_numbers <- structure( 1:26, .Names=letters )

my_numbers %>% ikeep( ~ .x > 20 | .y %in% c("a","b","c") )

```

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I think it's out of scope for this purrr: developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
