### ISSUE TITLE
The problem in extract the col from matrix and $

### ISSUE THREAD

**Issue by felixhell2004** [tidyverse/purrr#850]
It's very interesting that we had found a problem about extracting the list from a data.frame.
Our purpose is to split the string. And we extract the list from data.frame k by "$" and k[,2]. But the output result like row 2 are different. The result in pathways is match our expetation. But the result in pathways2 is not split as demand. It just like split the string
as random.

```r
# insert reprex here
library(data.table)
library(tidyverse)
fread("http://rest.kegg.jp/list/pathway/mmu",header = F)->k
name_rmends <- function(.x) {
  .x %>%str_locate_all(" - ")%>%.[[1]]->jk
  jk[nrow(jk),]%>%.[1]%>%{.-1}%>%str_sub(.x, end =.)%>%return
}# getname
k[,2]%>%map(~name_rmends(.x))%>%unlist()%>%cbind(k[,1])->pathways2# getname
k$V2%>%map(~name_rmends(.x))%>%unlist()%>%cbind(k[,1])->pathways# getname

```
Can someone help us?

**Comment by stanstrup** [comment]
`k[,2]` gives a data.frame/data.table; not a string. That is because data.table do not convert to a vector when you subset to a single column. That is a good thing for consistency.
`as.data.frame(k)[,2]` or `(k)[[2]]` would behave as you expect.
