### ISSUE TITLE
safely causes error in glm

### ISSUE THREAD

**Issue by izahn** [tidyverse/purrr#852]
Calling a `safe` version of `glm` fails when using the `offset` argument.

```r
library(purrr)
library(tibble)

set.seed(7) ## doesn't matter just for reproducibility
exd <- tibble(x = rnorm(10),
              y = sample(0:1, 10, TRUE),
              w = rnorm(10))

## works
glm(y ~ x, offset=exd$w, family = quasibinomial, data=exd)
## doesn't work
safeglm <- safely(glm)
safeglm(y ~ x, offset=exd$w, family = quasibinomial, data=exd)
#$result
#NULL
#
#$error
#<simpleError in eval(extras, data, env): ..2 used in an incorrect context, no ... to look in>
```

**Comment by hadley** [comment]
Unfortunately the way that many base R modelling functions perform non-standard evaluation is not compatible with purrr.

**Comment by hadley** [comment]
It's a problem with `glm`, not with purrr.

**Comment by izahn** [comment]
Even so, I think mentioning it in the purrr documentation would be useful, no?

**Comment by hadley** [comment]
I don't think maintaining a list of functions that don't work with specific purrr functions is a useful strategy.

**Comment by izahn** [comment]
I trust your judgment on that of course. I really don't think doing nothing is an appropriate response though. If tidyverse adverbs don't work with base modeling functions that is a major limitation that needs to be either fixed or at least communicated to users, otherwise we'll continue to run into this issue and blame the tidyverse for it.
