### ISSUE TITLE
can insistently capture root cause error? (feature request)

### ISSUE THREAD

**Issue by papageorgiou** [tidyverse/purrr#859]
"insistently() and possibly() are a useful combination"  - from purrr documentation

The combination of safely + insistently I would argue could also be very useful IF insistently captured the root cause error not just that "the function failed after retrying X times"

Then we can have a system that gives a function multiple chances to succeed but if this doesn't happen we can control the output via safely's otherwise parameter  +  we keep a record of why the function failed. I would see this as a complete and effective way to work with APIs and R/tidyverse. Thanks.

**Comment by hadley** [comment]
Do you have a specific example of what you're trying to do?

**Comment by papageorgiou** [comment]
Hi Hadley! thanks for the reply.

My use case is to call a Google api multiple times to request historical search volume data

I think this use case is generalisable for any api workflow that involves:

-calling an api multiple times e.g. call a weather forecast api separately for each location 
-having the option to retry based on some logic when the request fails
-when the error persists and the retries are exhausted keeping track of the specific error message
- plus keeping all the information in a tidy dataframe. 

To give you a visual idea of what the desired outcome would look like...
![retries](https://user-images.githubusercontent.com/7238261/186174023-8582e107-f571-4be4-a569-e6a44e5f3fda.png)

Also in case it helps: what I am referring to is similar to the retry parameter of python library tenacity
https://github.com/jd/tenacity   from section Error handling: 
"While callables that "timeout" retrying raise a RetryError by default, we can reraise the last attempt's exception if needed with reraise=True"

I am sure there are more ways in R or python to achieve the same result but it would be nice to have the option with safely + insistently  

Thank you.

**Comment by hadley** [comment]
This feels more like something you need implemented at the HTTP layer, i.e. https://httr2.r-lib.org/reference/req_retry.html.
