### ISSUE TITLE
purrr::when doesn't evaluate first condition

### ISSUE THREAD

**Issue by agilebean** [tidyverse/purrr#861]
For some reason, `purrr::when` doesn't seem to evaluate the first condition.
See here several cases with the example data from `purrr::case_when`.

```r
x <- 35

purrr::when(
  x %% 35 == 0 ~ "fizz buzz",
  x %% 5 == 0 ~ "fizz",
  x %% 7 == 0 ~ "buzz",
  TRUE ~ "no buzz"
)
# should give "fizz buzz" but gives
"fizz"

purrr::when(
  x %% 5 == 0 ~ "fizz",
  x %% 7 == 0 ~ "buzz",
  TRUE ~ "no buzz"
)
# should give "fizz" but gives
"buzz"

purrr::when(
  x %% 7 == 0 ~ "buzz",
  TRUE ~ "no buzz"
)
# should give "buzz" but gives
"no buzz"
```
Side notes:

1. All conditions evaluate to TRUE.
2. The same behavior happens when TRUE is omitted in the last condition. 
3. The same behavior happens when x is a vector (e.g. `x <- 1:100`)

### Is this a bug??

It could be a bug because having only one condition throws this error message:

```r
purrr::when(
  x %% 7 == 0 ~ "buzz"
)
Error: At least one matching condition is needed.

# However, case_when behaves as expected
dplyr::case_when(
  x %% 7 == 0 ~ "buzz"
)
"buzz"

```
Any ideas?

**Comment by jennybc** [comment]
You should provide x itself as the first argument.

**Comment by agilebean** [comment]
@jennybc OMG 
I wrongly assumed it had the same signature as `case_when`...
Thanks!

**Comment by jennybc** [comment]
`purrr::when()` is marked as "questioning" and it's pretty hard to learn that it even exists. I would avoid writing any new code that uses it. I didn't even know it existed until I saw this issue.

https://github.com/tidyverse/purrr/issues/745#issuecomment-585219577

**Comment by agilebean** [comment]
@jennybc got it. The reason i was looking into it was because I realized that `switch()` is dangerous to use as it does NOT check the conditions but just uses indeces. So I wanted to look at all alternatives. I also hoped to find an alternative that avoids writing the whole condition (like `x == 1`) but just requires the value to be matched (`1`).

**Comment by agilebean** [comment]
@jennybc I found one use case where `purrr::when()` could be handier than `dplyr::case_when`:
When you pipe in a dataframe from which you call a column name.

This deviates actually from the documentation because `x` should be the value to be matched, not the encompassing dataframe, but in comes in handy.

I cannot think of an elegant way to express this with `case_when`, can you?

See:

```
  result.table <- data_set %>%
    purrr::when(
      stat_type == "levened" ~ {

        unnest(., levened) %>%
          select(grouping, F.levene = `F value`, p.levene = `Pr(>F)`) %>%
          filter(!is.na(F.levene))

      },
      stat_type == "shapiroed" ~ {

        unnest(., shapiroed) %>%
          select(grouping, W = statistic, p.shapiro = p.value)

      },
      stat_type == "kruskaled" ~ {

        unnest(., kruskaled) %>%
          select(grouping, K = statistic, p.kruskal = p.value)

      },
      stat_type == "dunned" ~ {

        unnest(., dunned) %>%
          mutate(`eta-squared` = statistic^2 / (n1 + n2)) %>%
          select(grouping, group1, group2,
                 z = statistic, `eta-squared`,
                 p, p.adj, p.adj.signif
                 ) %>%
          unite("groups", c(group1, group2), sep = "~")

      },
      TRUE ~ {
        # covers bartletted, flignered, brownforsythed
        unnest(., stat_type, names_repair = "minimal") %>%
          select(grouping, statistic, p.value)
      }
    ) %>%
    {
      if (!is.null(grouping)) {

        dplyr::arrange(., across(grouping))
      } else {
        .
      }
    }
```
