### ISSUE TITLE
Example code in splice does not run

### ISSUE THREAD

**Issue by mccroweyclinton-EPA** [tidyverse/purrr#869]
The example code included in the roxygen2 notes from splice throws an error when this example code is ran. Please refer to 
 ?purrr::splice() 

```r
inputs <- list(arg1 = "a", arg2 = "b")

# splice() concatenates the elements of inputs with arg3
splice(inputs, arg3 = c("c1", "c2")) %>% str()
list(inputs, arg3 = c("c1", "c2")) %>% str()
c(inputs, arg3 = c("c1", "c2")) %>% str()
```

**Comment by lionel-** [comment]
`splice()` is marked with the "questioning" lifecycle badge because it's a part of the API we were unsure about. I think we should now look into deprecating it if possible. Or move to "superseded" if not.
