### ISSUE TITLE
Add examples to `purrr::keep()` and `purrr::map()` on how to negate the predicate

### ISSUE THREAD

**Issue by IndrajeetPatil** [tidyverse/purrr#872]
Because this is a nested function call, the users will need to use an anonymous function. Will be good to also include an example in the docs for the beginners.

![image](https://user-images.githubusercontent.com/11330453/185970219-27fb4113-266a-46a8-97f4-3f04b3f98c4d.png)

**Comment by hadley** [comment]
Looks like there are already plenty of examples using anonymous functions, so these don't feel particularly pressing to me.

**Comment by IndrajeetPatil** [comment]
But the issue is not about adding examples for anonymous functions, but rather negating the predicate, which requires using the anonymous function. 

And I couldn't find any example that demonstrates that. I think this will be good to have for beginners.

**Comment by TimTeaFan** [comment]
I also think this is something beginners usually get wrong. In the beginning I found myself wondering why `keep(x, !is.numeric)` wasn‘t working as expected. The error message `invalid argument type` might also be hard to understand.
