### ISSUE TITLE
Reconsider `can_simplify()` in `list_simplify()`

### ISSUE THREAD

**Issue by hadley** [tidyverse/purrr#935]
From 

```R
list_check_all_vectors(x, call = error_call)
can_simplify <- all(list_sizes(x) == 1L)
```

From https://github.com/tidyverse/purrr/pull/909#discussion_r968896274

**Comment by DavisVaughan** [comment]
```r
can_simplify <- list_all_vectors(x) && all(list_sizes(x) == 1L)
```

this also probably works

**Comment by DavisVaughan** [comment]
another place where `list_all_vectors(x, size = 1L)` would be useful

**Comment by hadley** [comment]
We can't require the input be a list of vectors because we currently assume that `accumulate()` silently fails to simplify in that case.
