### ISSUE TITLE
FR: multiple-position and multilevel subsetting of lists

### ISSUE THREAD

**Issue by ramiromagno** [tidyverse/purrr#977]
Hi Lionel and Hadley,

As always, thanks for the amazing packages.

I was just wondering, in Mathematica I can subset a list (an expression really, in Mathematica everything is an expression :) ) using multiple indices at different levels of a list.

![snap](https://user-images.githubusercontent.com/19862384/197317286-59ed76f3-de7d-4297-9811-063586523c6f.png)

Could `pluck`/`chuck` be extended to handle multiple indices at multiple levels?

(taking as an example code from the Examples' section of `pluck()`)
```R
library(purrr)

obj1 <- list("a", list(1, elt = "foo"))
obj2 <- list("b", list(2, elt = "bar"))
x <- list(obj1, obj2)
```

Can we make `pluck(x, 1:2, 2)` return 
```R
list(list(1, elt = "foo"), list(2, elt = "bar"))
```

**Comment by hadley** [comment]
I think this is out of scope for `pluck()`; I'd suggest using it with `map2()` instead.
