### ISSUE TITLE
Behavior of `map_*()` with `NULL` inputs

### ISSUE THREAD

**Issue by philiporlando** [tidyverse/purrr#982]
I'm trying to understand the behavior of `map_*()` when `NULL` values are present within the `.x` param.

```r
map_lgl(NULL, is.null)
# logical(0)

is.null(NULL)
# [1] TRUE
```
Should we expect `map_lgl()` to return `logical(0)` when `is.null(NULL)` returns `TRUE`? 

When applying `map_lgl()` to a vector, it appears to drop the `logical(0)` from the return vector altogether. Four elements are provided, but only three are returned.
```r
map_lgl(c(NULL, TRUE, 123, "ABC"), is.null)
# [1] FALSE FALSE FALSE
```

I'm still digging through the issues within this repo for more guidance and will close this if I find anything. Any insight here is also appreciated!

**Comment by hadley** [comment]
`logical(0)` means a logical of length 0.

**Comment by hadley** [comment]
That might be a bit of a terse answer — take a look at the results with `str()` to see if that makes it more clear what's happening.

**Comment by philiporlando** [comment]
Thanks for the feedback. Learning that `NULL` cannot exist within a vector helped me understand why we are seeing `logical(0)` returned in the first example, and only three elements in the second. It's simply getting skipped by `purrr::map_lgl()` because it doesn't actually exist.

```r
length(c(NULL))
# [1] 0
```
