### ISSUE TITLE
Error when trying to install dev version of purrr

### ISSUE THREAD

**Issue by werkstattcodes** [tidyverse/purrr#995]
I can't install the dev version of purrr, and it seems i am not the only one (see RStudio/Posit community [post](https://community.rstudio.com/t/cant-install-dev-version-of-purrr/151882/4)).

When trying to install the dev version with the CRAN version already being installed, it get the error below:

```
devtools::install_github("tidyverse/purrr")
Using github PAT from envvar GITHUB_PAT
Initiating curl with CURL_SSL_BACKEND: openssl
Downloading GitHub repo tidyverse/purrr@HEAD
✔  checking for file 'C:\Users\Roland\AppData\Local\Temp\Rtmpa2YcUz\remotes1acc14ee61d6\tidyverse-purrr-7788b48/DESCRIPTION' (503ms)
─  preparing 'purrr': (2.6s)
✔  checking DESCRIPTION meta-information ... 
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts (412ms)
─  checking for empty or unneeded directories
   Removed empty directory 'purrr/man/macros'
─  building 'purrr_0.9000.0.9000.tar.gz'
   Warning: file 'purrr/cleanup' did not have execute permissions: corrected
   Warning: file 'purrr/configure' did not have execute permissions: corrected
Installing package into ‘C:/Users/Roland/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
* installing *source* package 'purrr' ...
ERROR: cannot remove earlier installation, is it in use?
* removing 'C:/Users/Roland/AppData/Local/R/win-library/4.2/purrr'
* restoring previous 'C:/Users/Roland/AppData/Local/R/win-library/4.2/purrr'
Warning in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) :
  problem copying C:\Users\Roland\AppData\Local\R\win-library\4.2\00LOCK-purrr\purrr\libs\x64\purrr.dll to C:\Users\Roland\AppData\Local\R\win-library\4.2\purrr\libs\x64\purrr.dll: Permission denied
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/Roland/AppData/Local/Temp/Rtmpa2YcUz/file1acc146e24cc/purrr_0.9000.0.9000.tar.gz’ had non-zero exit status

```

When removing the purrr folder and installing the dev version 'from scratch' I get this error:

```
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'purrr'
```

Many thanks.

**Comment by hadley** [comment]
You're getting that error because you're (a) on windows and (b) trying to install purrr when it's already loaded in an R session. You'll need to restart R/RStudio (and close any other R/RStudio instances that you have open) and try again.

**Comment by werkstattcodes** [comment]
Many thanks for getting back to me.
This was my first thought as well, and I restarted R/RStudio/VSCode/Windows... but I keep getting the first error message from above.
When deleting the purrr folder, and then trying to install the dev version, I get the above mentioned "Error in loadNamespace" message.

If not mistaken (.packages()) would show me that purrr is loaded.
```
> (.packages())
[1] "stats"     "graphics"  "grDevices" "utils"     "datasets"  "methods"  
[7] "base" 
```

**Comment by hadley** [comment]
See my follow up in the community thread and the updated readme.

**Comment by gwd666** [comment]
Not the same but maybe related issue.    
I am currently having issues installing `purrr 1.0.0` from source on a Windows 10 machine for R-4.1.3 version.    
It will only build the package (from source) for the architecture of the active R session ie if I am running R 64 bit it will build 64-bit DLL and vice versa. Which means that other packages that have a (even 2nd degree etc) `purrr` dependency will now "also" fail `multiarch` builds, erroring on the missing other architecture DLL.    
I can work around this for now eg by `devtools::install_local(INSTALL_opts = c("--no-multiarch"))` but my guess is that this is more a bug than a feature of the WIndows OS `purrr` installation process?
